export const EFFECT_CATEGORIES = Object.freeze([
  'all',
  'capture',
  'explosion',
  'lightning',
  'portal',
  'glitch',
  'magic',
  'smoke',
  'fire',
  'ice',
  'water',
  'energy',
  'impact',
  'celebration',
  'emoji',
  'ambient',
  'misc',
]);

export const EFFECT_CATEGORY_LABELS = Object.freeze({
  all: 'All',
  capture: 'Capture',
  explosion: 'Explosion',
  lightning: 'Lightning',
  portal: 'Portal',
  glitch: 'Glitch',
  magic: 'Magic',
  smoke: 'Smoke',
  fire: 'Fire',
  ice: 'Ice',
  water: 'Water',
  energy: 'Energy',
  impact: 'Impact',
  celebration: 'Celebration',
  emoji: 'Emoji',
  ambient: 'Ambient',
  misc: 'Misc',
});
