// Generated by scripts/animations/import_assets.py. Do not edit by hand.
// Metro requires literal require() calls, so the reviewed selection is emitted here.

export const GENERATED_EFFECTS = {
  "acid_splash_01": {
    ...{"id":"acid_splash_01","name":"Acid Splash","category":"water","tags":["capture","acid","splash","impact"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":14,"fps":20,"visualScale":1.25,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/acid-splash/grid/sprite-sheet.png","requirePath":"../../assets/effects/water/acid_splash_01.png","fileSize":7775,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/water/acid_splash_01.png"),
  },
  "arcane_parry_01": {
    ...{"id":"arcane_parry_01","name":"Arcane Parry","category":"magic","tags":["capture","arcane","magic","impact"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":4,"frameCount":16,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/arcane-parry/grid/sprite-sheet.png","requirePath":"../../assets/effects/magic/arcane_parry_01.png","fileSize":17059,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/magic/arcane_parry_01.png"),
  },
  "crescent_slash_01": {
    ...{"id":"crescent_slash_01","name":"Crescent Slash","category":"impact","tags":["capture","slash","energy","impact"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":2,"frameCount":10,"fps":20,"visualScale":1.35,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/crescent-slash/grid/sprite-sheet.png","requirePath":"../../assets/effects/impact/crescent_slash_01.png","fileSize":2891,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/impact/crescent_slash_01.png"),
  },
  "earth_rupture_01": {
    ...{"id":"earth_rupture_01","name":"Earth Rupture","category":"impact","tags":["capture","earth","rupture","debris"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":4,"frameCount":20,"fps":20,"visualScale":1.15,"visualOffsetY":-0.1,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/earth-rupture/grid/sprite-sheet.png","requirePath":"../../assets/effects/impact/earth_rupture_01.png","fileSize":16182,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/impact/earth_rupture_01.png"),
  },
  "electric_impact_01": {
    ...{"id":"electric_impact_01","name":"Electric Impact","category":"lightning","tags":["capture","electric","lightning","shockwave","impact"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":14,"fps":20,"visualScale":1.25,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/electric-impact/grid/sprite-sheet.png","requirePath":"../../assets/effects/lightning/electric_impact_01.png","fileSize":8615,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/lightning/electric_impact_01.png"),
  },
  "ember_jet_01": {
    ...{"id":"ember_jet_01","name":"Ember Jet","category":"fire","tags":["capture","fire","ember","projectile"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":14,"fps":20,"visualScale":1.2,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/ember-jet/grid/sprite-sheet.png","requirePath":"../../assets/effects/fire/ember_jet_01.png","fileSize":7121,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/fire/ember_jet_01.png"),
  },
  "frost_nova_01": {
    ...{"id":"frost_nova_01","name":"Frost Nova","category":"ice","tags":["capture","ice","frost","nova"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":13,"fps":20,"visualScale":1.2,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/frost-nova/grid/sprite-sheet.png","requirePath":"../../assets/effects/ice/frost_nova_01.png","fileSize":6079,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/ice/frost_nova_01.png"),
  },
  "magical_projectile_01": {
    ...{"id":"magical_projectile_01","name":"Magical Projectile","category":"magic","tags":["capture","magic","orb","projectile"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":12,"fps":20,"visualScale":2,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/magical-projectile/grid/sprite-sheet.png","requirePath":"../../assets/effects/magic/magical_projectile_01.png","fileSize":4463,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/magic/magical_projectile_01.png"),
  },
  "radiant_heal_01": {
    ...{"id":"radiant_heal_01","name":"Radiant Heal","category":"celebration","tags":["capture","radiant","heal","holy","victory"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":14,"fps":20,"visualScale":1.15,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/radiant-heal/grid/sprite-sheet.png","requirePath":"../../assets/effects/celebration/radiant_heal_01.png","fileSize":9541,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/celebration/radiant_heal_01.png"),
  },
  "solar_shrapnel_01": {
    ...{"id":"solar_shrapnel_01","name":"Solar Shrapnel","category":"energy","tags":["capture","solar","shrapnel","impact","fire"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":14,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/solar-shrapnel/grid/sprite-sheet.png","requirePath":"../../assets/effects/energy/solar_shrapnel_01.png","fileSize":7805,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/energy/solar_shrapnel_01.png"),
  },
  "spectral_bloom_01": {
    ...{"id":"spectral_bloom_01","name":"Spectral Bloom","category":"magic","tags":["capture","spectral","bloom","portal","magic"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":4,"frameCount":16,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/spectral-bloom/grid/sprite-sheet.png","requirePath":"../../assets/effects/magic/spectral_bloom_01.png","fileSize":11413,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/magic/spectral_bloom_01.png"),
  },
  "void_implosion_01": {
    ...{"id":"void_implosion_01","name":"Void Implosion","category":"energy","tags":["capture","void","implosion","dark","portal"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":14,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/void-implosion/grid/sprite-sheet.png","requirePath":"../../assets/effects/energy/void_implosion_01.png","fileSize":9147,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/energy/void_implosion_01.png"),
  },
  "warm_explosion_01": {
    ...{"id":"warm_explosion_01","name":"Warm Explosion","category":"explosion","tags":["capture","explosion","fire","impact"],"frameWidth":96,"frameHeight":96,"columns":5,"rows":3,"frameCount":15,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\pvfx-foundry-thirteen-spritesheets.zip::PVFX-Foundry-Thirteen-0.1.0/effects/warm-explosion/grid/sprite-sheet.png","requirePath":"../../assets/effects/explosion/warm_explosion_01.png","fileSize":9000,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"foundry","originalName":"sprite-sheet.png"},
    source: require("../../assets/effects/explosion/warm_explosion_01.png"),
  },
  "fire_column_01": {
    ...{"id":"fire_column_01","name":"Fire Column","category":"fire","tags":["capture","fire","flame"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"visualScale":1.4,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::11_fire_spritesheet.png","requirePath":"../../assets/effects/fire/fire_column_01.png","fileSize":49572,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"11_fire_spritesheet.png"},
    source: require("../../assets/effects/fire/fire_column_01.png"),
  },
  "nebula_burst_01": {
    ...{"id":"nebula_burst_01","name":"Nebula Burst","category":"celebration","tags":["capture","nebula","stars","particles"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::12_nebula_spritesheet.png","requirePath":"../../assets/effects/celebration/nebula_burst_01.png","fileSize":153165,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"12_nebula_spritesheet.png"},
    source: require("../../assets/effects/celebration/nebula_burst_01.png"),
  },
  "vortex_red_01": {
    ...{"id":"vortex_red_01","name":"Red Vortex","category":"portal","tags":["capture","vortex","portal","red"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::13_vortex_spritesheet.png","requirePath":"../../assets/effects/portal/vortex_red_01.png","fileSize":104181,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"13_vortex_spritesheet.png"},
    source: require("../../assets/effects/portal/vortex_red_01.png"),
  },
  "sunburn_ring_01": {
    ...{"id":"sunburn_ring_01","name":"Sunburn Ring","category":"energy","tags":["capture","solar","ring","fire"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::16_sunburn_spritesheet.png","requirePath":"../../assets/effects/energy/sunburn_ring_01.png","fileSize":55652,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"16_sunburn_spritesheet.png"},
    source: require("../../assets/effects/energy/sunburn_ring_01.png"),
  },
  "freezing_bloom_01": {
    ...{"id":"freezing_bloom_01","name":"Freezing Bloom","category":"ice","tags":["capture","ice","frost","snow","particles"],"frameWidth":100,"frameHeight":100,"columns":10,"rows":10,"frameCount":100,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::19_freezing_spritesheet.png","requirePath":"../../assets/effects/ice/freezing_bloom_01.png","fileSize":202938,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"19_freezing_spritesheet.png"},
    source: require("../../assets/effects/ice/freezing_bloom_01.png"),
  },
  "magic_spell_01": {
    ...{"id":"magic_spell_01","name":"Magic Spell","category":"magic","tags":["capture","magic","spell","particles"],"frameWidth":100,"frameHeight":100,"columns":9,"rows":9,"frameCount":81,"fps":30,"visualScale":1.7,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::1_magicspell_spritesheet.png","requirePath":"../../assets/effects/magic/magic_spell_01.png","fileSize":53077,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"1_magicspell_spritesheet.png"},
    source: require("../../assets/effects/magic/magic_spell_01.png"),
  },
  "magic_bubbles_01": {
    ...{"id":"magic_bubbles_01","name":"Magic Bubbles","category":"magic","tags":["capture","magic","bubbles","particles"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"visualScale":1.6,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::20_magicbubbles_spritesheet.png","requirePath":"../../assets/effects/magic/magic_bubbles_01.png","fileSize":35396,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"20_magicbubbles_spritesheet.png"},
    source: require("../../assets/effects/magic/magic_bubbles_01.png"),
  },
  "magic_infinity_01": {
    ...{"id":"magic_infinity_01","name":"Magic Infinity","category":"magic","tags":["capture","magic","infinity","portal"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::2_magic8_spritesheet.png","requirePath":"../../assets/effects/magic/magic_infinity_01.png","fileSize":145952,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"2_magic8_spritesheet.png"},
    source: require("../../assets/effects/magic/magic_infinity_01.png"),
  },
  "blue_fire_01": {
    ...{"id":"blue_fire_01","name":"Blue Fire","category":"fire","tags":["capture","blue","fire","magic"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"visualScale":1.55,"visualOffsetX":-0.1,"visualOffsetY":-0.2,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::3_bluefire_spritesheet.png","requirePath":"../../assets/effects/fire/blue_fire_01.png","fileSize":43393,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"3_bluefire_spritesheet.png"},
    source: require("../../assets/effects/fire/blue_fire_01.png"),
  },
  "fire_spin_01": {
    ...{"id":"fire_spin_01","name":"Fire Spin","category":"fire","tags":["capture","fire","spin","ring"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":64,"fps":30,"visualScale":1.5,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::7_firespin_spritesheet.png","requirePath":"../../assets/effects/fire/fire_spin_01.png","fileSize":67792,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"7_firespin_spritesheet.png"},
    source: require("../../assets/effects/fire/fire_spin_01.png"),
  },
  "explosion_orange_01": {
    ...{"id":"explosion_orange_01","name":"Orange Pixel Explosion","category":"explosion","tags":["capture","explosion","pixel","impact"],"frameWidth":32,"frameHeight":32,"columns":11,"rows":1,"frameCount":11,"fps":15,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Super Pixel Effects Mini Pack 1.zip::Super Pixel Effects Mini Pack 1/spritesheet/fx1_explosion_small_orange/spritesheet.png","requirePath":"../../assets/effects/explosion/explosion_orange_01.png","fileSize":3984,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"super_mini","originalName":"spritesheet.png"},
    source: require("../../assets/effects/explosion/explosion_orange_01.png"),
  },
  "electric_burst_01": {
    ...{"id":"electric_burst_01","name":"Violet Electric Burst","category":"lightning","tags":["capture","electric","lightning","burst"],"frameWidth":72,"frameHeight":72,"columns":16,"rows":1,"frameCount":16,"fps":15,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Super Pixel Effects Mini Pack 1.zip::Super Pixel Effects Mini Pack 1/spritesheet/fx2_electric_burst_large_violet/spritesheet.png","requirePath":"../../assets/effects/lightning/electric_burst_01.png","fileSize":16312,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"super_mini","originalName":"spritesheet.png"},
    source: require("../../assets/effects/lightning/electric_burst_01.png"),
  },
  "impact_shock_01": {
    ...{"id":"impact_shock_01","name":"Ground Impact Shock","category":"impact","tags":["capture","impact","shockwave","earth"],"frameWidth":140,"frameHeight":50,"columns":7,"rows":1,"frameCount":7,"fps":15,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Super Pixel Effects Mini Pack 1.zip::Super Pixel Effects Mini Pack 1/spritesheet/fx2_impact_shock_large_brown/spritesheet.png","requirePath":"../../assets/effects/impact/impact_shock_01.png","fileSize":11916,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"super_mini","originalName":"spritesheet.png"},
    source: require("../../assets/effects/impact/impact_shock_01.png"),
  },
  "bomb_blast_01": {
    ...{"id":"bomb_blast_01","name":"Bomb Blast","category":"explosion","tags":["capture","bomb","explosion","smoke","steal"],"frameWidth":128,"frameHeight":80,"columns":10,"rows":1,"frameCount":10,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\explosion pack 1.zip::explosion pack 1/Explosions pack/explosion-1-c/spritesheet.png","requirePath":"../../assets/effects/explosion/bomb_blast_01.png","fileSize":7578,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"ansimuz_explosions","originalName":"spritesheet.png"},
    source: require("../../assets/effects/explosion/bomb_blast_01.png"),
  },
  "fall_leaf_01": {
    ...{"id":"fall_leaf_01","name":"Autumn Leaf","category":"ambient","tags":["ambient","leaf","autumn"],"frameWidth":20,"frameHeight":16,"columns":4,"rows":1,"frameCount":4,"fps":8,"loop":true,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\ELR-WindyLeafs.zip::ELR-WindyLeafs/ELR_FallLeaf.png","requirePath":"../../assets/effects/ambient/fall_leaf_01.png","fileSize":327,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"leaves","originalName":"ELR_FallLeaf.png"},
    source: require("../../assets/effects/ambient/fall_leaf_01.png"),
  },
  "spring_leaf_01": {
    ...{"id":"spring_leaf_01","name":"Spring Leaf","category":"ambient","tags":["ambient","leaf","spring"],"frameWidth":20,"frameHeight":16,"columns":4,"rows":1,"frameCount":4,"fps":8,"loop":true,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\ELR-WindyLeafs.zip::ELR-WindyLeafs/ELR_SpringlLeaf.png","requirePath":"../../assets/effects/ambient/spring_leaf_01.png","fileSize":331,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"leaves","originalName":"ELR_SpringlLeaf.png"},
    source: require("../../assets/effects/ambient/spring_leaf_01.png"),
  },
  "winter_leaf_01": {
    ...{"id":"winter_leaf_01","name":"Winter Leaf","category":"ambient","tags":["ambient","leaf","winter"],"frameWidth":20,"frameHeight":16,"columns":4,"rows":1,"frameCount":4,"fps":8,"loop":true,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\ELR-WindyLeafs.zip::ELR-WindyLeafs/ELR_WinterlLeaf.png","requirePath":"../../assets/effects/ambient/winter_leaf_01.png","fileSize":331,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"leaves","originalName":"ELR_WinterlLeaf.png"},
    source: require("../../assets/effects/ambient/winter_leaf_01.png"),
  },
  "reaction_love": {
    ...{"id":"reaction_love","name":"Love","category":"emoji","tags":["reaction","love"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetLove.png","requirePath":"../../assets/effects/emoji/reaction_love.png","fileSize":3040,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetLove.png"},
    source: require("../../assets/effects/emoji/reaction_love.png"),
  },
  "reaction_happy": {
    ...{"id":"reaction_happy","name":"Laughing","category":"emoji","tags":["reaction","laughing"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetLaughing.png","requirePath":"../../assets/effects/emoji/reaction_happy.png","fileSize":3090,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetLaughing.png"},
    source: require("../../assets/effects/emoji/reaction_happy.png"),
  },
  "reaction_wow": {
    ...{"id":"reaction_wow","name":"OMG","category":"emoji","tags":["reaction","omg"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetOMG.png","requirePath":"../../assets/effects/emoji/reaction_wow.png","fileSize":3745,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetOMG.png"},
    source: require("../../assets/effects/emoji/reaction_wow.png"),
  },
  "reaction_respect": {
    ...{"id":"reaction_respect","name":"Ok","category":"emoji","tags":["reaction","ok"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetOk.png","requirePath":"../../assets/effects/emoji/reaction_respect.png","fileSize":3898,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetOk.png"},
    source: require("../../assets/effects/emoji/reaction_respect.png"),
  },
  "reaction_brutal": {
    ...{"id":"reaction_brutal","name":"Mind Blown","category":"emoji","tags":["reaction","headblown"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetHeadblown.png","requirePath":"../../assets/effects/emoji/reaction_brutal.png","fileSize":4149,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetHeadblown.png"},
    source: require("../../assets/effects/emoji/reaction_brutal.png"),
  },
  "reaction_rival": {
    ...{"id":"reaction_rival","name":"Angry","category":"emoji","tags":["reaction","angry"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetAngry.png","requirePath":"../../assets/effects/emoji/reaction_rival.png","fileSize":3840,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetAngry.png"},
    source: require("../../assets/effects/emoji/reaction_rival.png"),
  },
  "reaction_vibes": {
    ...{"id":"reaction_vibes","name":"Lit","category":"emoji","tags":["reaction","lit"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetLit.png","requirePath":"../../assets/effects/emoji/reaction_vibes.png","fileSize":3966,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetLit.png"},
    source: require("../../assets/effects/emoji/reaction_vibes.png"),
  },
  "reaction_idea": {
    ...{"id":"reaction_idea","name":"Idea","category":"emoji","tags":["reaction","idea"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetIdea.png","requirePath":"../../assets/effects/emoji/reaction_idea.png","fileSize":4022,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetIdea.png"},
    source: require("../../assets/effects/emoji/reaction_idea.png"),
  },
  "reaction_exclamation": {
    ...{"id":"reaction_exclamation","name":"Exclamation","category":"emoji","tags":["reaction","exclamation"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetExclamation.png","requirePath":"../../assets/effects/emoji/reaction_exclamation.png","fileSize":2381,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetExclamation.png"},
    source: require("../../assets/effects/emoji/reaction_exclamation.png"),
  },
  "reaction_crying": {
    ...{"id":"reaction_crying","name":"Crying","category":"emoji","tags":["reaction","crying"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetCrying.png","requirePath":"../../assets/effects/emoji/reaction_crying.png","fileSize":3097,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetCrying.png"},
    source: require("../../assets/effects/emoji/reaction_crying.png"),
  },
  "reaction_question": {
    ...{"id":"reaction_question","name":"Question","category":"emoji","tags":["reaction","question"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetQuestion.png","requirePath":"../../assets/effects/emoji/reaction_question.png","fileSize":2641,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetQuestion.png"},
    source: require("../../assets/effects/emoji/reaction_question.png"),
  },
  "reaction_speechless": {
    ...{"id":"reaction_speechless","name":"Speechless","category":"emoji","tags":["reaction","speechless"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetSpeechless.png","requirePath":"../../assets/effects/emoji/reaction_speechless.png","fileSize":2583,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetSpeechless.png"},
    source: require("../../assets/effects/emoji/reaction_speechless.png"),
  },
  "reaction_sleepy": {
    ...{"id":"reaction_sleepy","name":"Sleepy","category":"emoji","tags":["reaction","sleepy"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetSleepy.png","requirePath":"../../assets/effects/emoji/reaction_sleepy.png","fileSize":3175,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetSleepy.png"},
    source: require("../../assets/effects/emoji/reaction_sleepy.png"),
  },
  "reaction_frustrated": {
    ...{"id":"reaction_frustrated","name":"Frustrated","category":"emoji","tags":["reaction","frustrated"],"frameWidth":32,"frameHeight":32,"columns":5,"rows":4,"frameCount":16,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\emojiPackI.zip::20250405emoticons-SheetFrustrated.png","requirePath":"../../assets/effects/emoji/reaction_frustrated.png","fileSize":2239,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"tiny_rpg","originalName":"20250405emoticons-SheetFrustrated.png"},
    source: require("../../assets/effects/emoji/reaction_frustrated.png"),
  },
  "protection_circle_01": {
    ...{"id":"protection_circle_01","name":"Protection Circle","category":"magic","tags":["capture","ward","shield","seal"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":61,"fps":30,"visualScale":1.8,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::8_protectioncircle_spritesheet.png","requirePath":"../../assets/effects/magic/protection_circle_01.png","fileSize":53784,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"8_protectioncircle_spritesheet.png"},
    source: require("../../assets/effects/magic/protection_circle_01.png"),
  },
  "weapon_hit_01": {
    ...{"id":"weapon_hit_01","name":"Weapon Hit","category":"impact","tags":["capture","hit","impact","strike"],"frameWidth":100,"frameHeight":100,"columns":6,"rows":6,"frameCount":31,"fps":30,"visualScale":1.8,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::10_weaponhit_spritesheet.png","requirePath":"../../assets/effects/impact/weapon_hit_01.png","fileSize":6515,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"10_weaponhit_spritesheet.png"},
    source: require("../../assets/effects/impact/weapon_hit_01.png"),
  },
  "phantom_cross_01": {
    ...{"id":"phantom_cross_01","name":"Phantom Cross","category":"magic","tags":["capture","phantom","spectral","residue"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":61,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::14_phantom_spritesheet.png","requirePath":"../../assets/effects/magic/phantom_cross_01.png","fileSize":30395,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"14_phantom_spritesheet.png"},
    source: require("../../assets/effects/magic/phantom_cross_01.png"),
  },
  "fel_spell_01": {
    ...{"id":"fel_spell_01","name":"Fel Spell","category":"magic","tags":["capture","corruption","acid","spread"],"frameWidth":100,"frameHeight":100,"columns":10,"rows":10,"frameCount":91,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::17_felspell_spritesheet.png","requirePath":"../../assets/effects/magic/fel_spell_01.png","fileSize":263943,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"17_felspell_spritesheet.png"},
    source: require("../../assets/effects/magic/fel_spell_01.png"),
  },
  "midnight_01": {
    ...{"id":"midnight_01","name":"Midnight","category":"magic","tags":["capture","dark","night","storm"],"frameWidth":100,"frameHeight":100,"columns":8,"rows":8,"frameCount":61,"fps":30,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Free Pixel Effects Pack.zip::18_midnight_spritesheet.png","requirePath":"../../assets/effects/magic/midnight_01.png","fileSize":134851,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"free_pixel","originalName":"18_midnight_spritesheet.png"},
    source: require("../../assets/effects/magic/midnight_01.png"),
  },
  "boom_mid_01": {
    ...{"id":"boom_mid_01","name":"Mid Boom","category":"explosion","tags":["capture","explosion","chain"],"frameWidth":64,"frameHeight":64,"columns":8,"rows":1,"frameCount":8,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\explosion pack 1.zip::explosion pack 1/Explosions pack/explosion-1-b/spritesheet.png","requirePath":"../../assets/effects/explosion/boom_mid_01.png","fileSize":3110,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"ansimuz_explosions","originalName":"spritesheet.png"},
    source: require("../../assets/effects/explosion/boom_mid_01.png"),
  },
  "boom_large_01": {
    ...{"id":"boom_large_01","name":"Large Boom","category":"explosion","tags":["capture","explosion","chain","large"],"frameWidth":128,"frameHeight":128,"columns":4,"rows":3,"frameCount":12,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\explosion pack 1.zip::explosion pack 1/Explosions pack/explosion-1-d/Sprites/explosion-d*.png","requirePath":"../../assets/effects/explosion/boom_large_01.png","fileSize":7622,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"ansimuz_explosions","originalName":"boom_large_01"},
    source: require("../../assets/effects/explosion/boom_large_01.png"),
  },
  "boom_huge_01": {
    ...{"id":"boom_huge_01","name":"Huge Boom","category":"explosion","tags":["capture","explosion","chain","finale"],"frameWidth":192,"frameHeight":192,"columns":6,"rows":4,"frameCount":22,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\explosion pack 1.zip::explosion pack 1/Explosions pack/explosion-1-e/Sprites/explosion-e*.png","requirePath":"../../assets/effects/explosion/boom_huge_01.png","fileSize":7419,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"ansimuz_explosions","originalName":"boom_huge_01"},
    source: require("../../assets/effects/explosion/boom_huge_01.png"),
  },
  "emote_note_01": {
    ...{"id":"emote_note_01","name":"Note Balloon","category":"emoji","tags":["capture","emote","balloon","note"],"frameWidth":32,"frameHeight":32,"columns":8,"rows":2,"frameCount":9,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Icons emote.zip::Icons emote/Center/12 - Note.png","requirePath":"../../assets/effects/emoji/emote_note_01.png","fileSize":2558,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"icons_emote","originalName":"12 - Note.png"},
    source: require("../../assets/effects/emoji/emote_note_01.png"),
  },
  "emote_sleeping_01": {
    ...{"id":"emote_sleeping_01","name":"Sleeping Balloon","category":"emoji","tags":["capture","emote","balloon","sleeping"],"frameWidth":32,"frameHeight":32,"columns":8,"rows":2,"frameCount":9,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Icons emote.zip::Icons emote/Center/10 - Sleeping.png","requirePath":"../../assets/effects/emoji/emote_sleeping_01.png","fileSize":2128,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"icons_emote","originalName":"10 - Sleeping.png"},
    source: require("../../assets/effects/emoji/emote_sleeping_01.png"),
  },
  "emote_dots_01": {
    ...{"id":"emote_dots_01","name":"Dots Balloon","category":"emoji","tags":["capture","emote","balloon","dots"],"frameWidth":32,"frameHeight":32,"columns":8,"rows":2,"frameCount":9,"fps":14,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Icons emote.zip::Icons emote/Center/09 - Dots.png","requirePath":"../../assets/effects/emoji/emote_dots_01.png","fileSize":1778,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"icons_emote","originalName":"09 - Dots.png"},
    source: require("../../assets/effects/emoji/emote_dots_01.png"),
  },
  "attack_up_01": {
    ...{"id":"attack_up_01","name":"Attack Up Aura","category":"magic","tags":["capture","aura","buff","character"],"frameWidth":128,"frameHeight":128,"columns":6,"rows":3,"frameCount":18,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Super Pixel Fantasy FX Pack 3 Free Version.zip::Super Pixel Fantasy FX Pack 3 Free Version/PNG/fanfx3_attack_up_large_red/frame*.png","requirePath":"../../assets/effects/magic/attack_up_01.png","fileSize":25805,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"super_pixel_fantasy","originalName":"attack_up_01"},
    source: require("../../assets/effects/magic/attack_up_01.png"),
  },
  "defense_up_01": {
    ...{"id":"defense_up_01","name":"Defense Up Aura","category":"magic","tags":["capture","aura","buff","character"],"frameWidth":128,"frameHeight":128,"columns":6,"rows":3,"frameCount":18,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Super Pixel Fantasy FX Pack 3 Free Version.zip::Super Pixel Fantasy FX Pack 3 Free Version/PNG/fanfx3_defense_up_large_blue/frame*.png","requirePath":"../../assets/effects/magic/defense_up_01.png","fileSize":23373,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"super_pixel_fantasy","originalName":"defense_up_01"},
    source: require("../../assets/effects/magic/defense_up_01.png"),
  },
  "haste_01": {
    ...{"id":"haste_01","name":"Haste Aura","category":"magic","tags":["capture","aura","buff","character"],"frameWidth":128,"frameHeight":128,"columns":6,"rows":5,"frameCount":29,"fps":20,"releaseApproved":true,"sourcePath":"C:\\Users\\user\\Desktop\\animations\\Super Pixel Fantasy FX Pack 3 Free Version.zip::Super Pixel Fantasy FX Pack 3 Free Version/PNG/fanfx3_haste_large_green/frame*.png","requirePath":"../../assets/effects/magic/haste_01.png","fileSize":38014,"densityScales":[1,2,3],"type":"sprite","sourcePackage":"super_pixel_fantasy","originalName":"haste_01"},
    source: require("../../assets/effects/magic/haste_01.png"),
  },
};
