"""Generate the server-side shop catalogue from the client cosmetics catalogue.

The backend has no cosmetics list — rarity lives in frontend/src/config/
cosmetics.js. Pricing a purchase from a client-supplied rarity would let
anyone buy a legendary for the price of a common, so the server needs its own
copy. This script derives it from the SAME source so the two can't drift, the
way cosmeticsArt.js and borderArt.js are generated.

Excluded from the shop:
  * premiumOnly items — PASER PRO exclusives. If coins could buy them the
    pass has no product left to sell.
  * 'none' entries — the empty-slot placeholders.

Run from frontend/:  python scripts/gen-shop-catalog.py
"""

import os
import re

FE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(FE, "src", "config", "cosmetics.js")
# cosmetics.js holds only part of the wardrobe: ITEMS.top/bottom/footwear are
# then push()ed full of the arrays in outfitItems.js. Reading the first file
# alone meant every outfit piece — all the bottoms and every pair of shoes —
# was equippable but could never be bought, because the server had no price
# for it.
OUTFITS = os.path.join(FE, "src", "config", "outfitItems.js")
PUSHED = {"OUTFIT_TOPS": "top", "OUTFIT_SUITS": "top",
          "OUTFIT_BOTTOMS": "bottom", "FOOTWEAR": "footwear"}
OUT = os.path.abspath(os.path.join(FE, "..", "backend", "app", "shop_catalog.py"))

# Coins by rarity. Tuned against the earn rate in coins.py (25/run, 100/level):
# a common is ~6 runs, a legendary is a real goal rather than an impulse buy.
PRICE = {"common": 150, "rare": 400, "epic": 900, "legendary": 2000}

src = open(SRC, encoding="utf-8").read()

items = []
for m in re.finditer(r"\n  (\w+): \[([\s\S]*?)\n  \],", src):
    slot, body = m.group(1), m.group(2)
    for line in body.splitlines():
        mid = re.search(r"id: '([^']+)'", line)
        if not mid:
            continue
        iid = mid.group(1)
        if iid == "none":
            continue
        if "premiumOnly" in line:
            continue                      # pass-exclusive, never coin-buyable
        rarity = (re.search(r"rarity: '(\w+)'", line) or [None, "common"])[1]
        label = (re.search(r"label: '([^']*)'", line) or [None, iid])[1]
        items.append((slot, iid, rarity, label))

osrc = open(OUTFITS, encoding="utf-8").read()
for arr, slot in PUSHED.items():
    start = osrc.find(f"export const {arr} = [")
    end = osrc.find("\n];", start)
    if start < 0 or end < 0:
        raise SystemExit(f"{arr} not found in outfitItems.js")
    for line in osrc[start:end].splitlines():
        mid = re.search(r"id: '([^']+)'", line)
        if not mid or mid.group(1) == "none" or "premiumOnly" in line:
            continue
        rarity = (re.search(r"rarity: '(\w+)'", line) or [None, "common"])[1]
        label = (re.search(r"label: '([^']*)'", line) or [None, mid.group(1)])[1]
        items.append((slot, mid.group(1), rarity, label))

by_slot = {}
for slot, iid, rarity, label in items:
    by_slot.setdefault(slot, []).append((iid, rarity, label))

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write('"""GENERATED by frontend/scripts/gen-shop-catalog.py — do not edit.\n\n'
            "Server-side mirror of the client cosmetics catalogue, used to price\n"
            "and validate coin purchases. Regenerate whenever cosmetics.js changes;\n"
            "`node scripts/check-catalog.js` verifies the two are in sync.\n"
            '"""\n\n')
    f.write("PRICE_BY_RARITY = {\n")
    for k, v in PRICE.items():
        f.write(f'    "{k}": {v},\n')
    f.write("}\n\n")
    f.write("# item_id -> (slot, rarity). Ids are unique across slots (enforced by\n"
            "# check-catalog.js), so a flat map is safe and keeps lookups simple.\n")
    f.write("SHOP_ITEMS = {\n")
    for slot in sorted(by_slot):
        f.write(f"    # --- {slot} ---\n")
        for iid, rarity, label in by_slot[slot]:
            f.write(f'    "{iid}": ("{slot}", "{rarity}"),  # {label}\n')
    f.write("}\n\n\n")
    f.write(
        "def price_of(item_id: str) -> int | None:\n"
        '    """Coin price, or None if the item isn\'t purchasable."""\n'
        "    entry = SHOP_ITEMS.get(item_id)\n"
        "    if not entry:\n"
        "        return None\n"
        "    return PRICE_BY_RARITY.get(entry[1])\n"
    )

print(f"wrote {OUT}")
print(f"{len(items)} purchasable items across {len(by_slot)} slots")
for slot in sorted(by_slot):
    print(f"  {slot}: {len(by_slot[slot])}")
