"""Generate the seeded-players cosmetics list from the client catalogue.

Sibling of gen-shop-catalog.py, and generated for the same reason: the
wardrobe lives in frontend/src/config/, the backend has no copy, and seeded
players that all wear the DEFAULT_EQUIPPED loadout are 384 identical runners
standing on a map. The seeder needs to know what exists in order to dress
them differently.

It cannot reuse shop_catalog.py. That one deliberately excludes everything
free, everything passOnly, and everything premiumOnly, because it exists to
price purchases — so it is missing `smiley`, `curtains`, `stripetee` and the
rest of the items a normal runner is actually wearing.

WHAT IS EXCLUDED HERE, and why only this:

  * premiumOnly — PASER PRO exclusives. A world where hundreds of runners
    wear the PRO-only pieces tells every new player that the reward is
    ordinary, which is exactly what the pass has to sell.

passOnly and stat-locked items ARE included. A seeded runner having earned a
25 km face or a level 20 hat is the point: those unlocks are supposed to be
visible on other people, and hiding them makes the ladder look unclimbed.

    python frontend/scripts/gen-bot-cosmetics.py

Writes backend/bot_cosmetics.py. Re-run whenever cosmetics.js, outfitItems.js
or hairSheetItems.js changes.
"""

from __future__ import annotations

import os
import re
from collections import OrderedDict

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG = os.path.join(HERE, "..", "src", "config")
OUT = os.path.join(HERE, "..", "..", "backend", "bot_cosmetics.py")

ITEM_RE = re.compile(r"\{\s*id:\s*'([^']+)'")
RARITY_RE = re.compile(r"rarity:\s*'(\w+)'")
UNLOCK_RE = re.compile(r"unlock:\s*(\w+)")


def read(name: str) -> str:
    with open(os.path.join(CONFIG, name), encoding="utf-8") as f:
        return f.read()


def parse_list(body: str) -> list:
    """Every `{ id: '...' }` in a chunk of JS, with rarity and unlock kind."""
    out = []
    for line in body.splitlines():
        m = ITEM_RE.search(line)
        if not m:
            continue
        rar = RARITY_RE.search(line)
        unl = UNLOCK_RE.search(line)
        out.append((m.group(1), rar.group(1) if rar else "common",
                    unl.group(1) if unl else "free"))
    return out


def slice_between(src: str, start: str, *ends: str) -> str:
    i = src.index(start)
    j = len(src)
    for e in ends:
        k = src.find(e, i + len(start))
        if k != -1:
            j = min(j, k)
    return src[i:j]


def main() -> int:
    cosmetics = read("cosmetics.js")
    outfits = read("outfitItems.js")
    hair = read("hairSheetItems.js")

    # The hand-written per-slot lists.
    items_block = slice_between(cosmetics, "export const ITEMS = {",
                                "export const FIRST_RUN_ITEMS")
    slots: "OrderedDict[str, list]" = OrderedDict()
    cur = None
    for line in items_block.splitlines():
        m = re.match(r"\s*(\w+):\s*\[\s*$", line)
        if m:
            cur = m.group(1)
            slots.setdefault(cur, [])
            continue
        m = ITEM_RE.search(line)
        if m and cur:
            rar = RARITY_RE.search(line)
            unl = UNLOCK_RE.search(line)
            slots[cur].append((m.group(1), rar.group(1) if rar else "common",
                               unl.group(1) if unl else "free"))

    # The generated art, merged in exactly the way cosmetics.js merges it.
    slots.setdefault("hair", []).extend(
        parse_list(slice_between(hair, "export const HAIR_SHEETS = [")))
    slots.setdefault("top", []).extend(
        parse_list(slice_between(outfits, "export const OUTFIT_TOPS = [",
                                 "export const OUTFIT_BOTTOMS")))
    slots["top"].extend(
        parse_list(slice_between(outfits, "export const OUTFIT_SUITS = [")))
    slots.setdefault("bottom", []).extend(
        parse_list(slice_between(outfits, "export const OUTFIT_BOTTOMS = [",
                                 "export const FOOTWEAR")))
    slots["footwear"] = parse_list(
        slice_between(outfits, "export const FOOTWEAR = [",
                      "export const OUTFIT_SUITS"))

    kept = OrderedDict()
    dropped = 0
    for slot, entries in slots.items():
        rows = []
        seen = set()
        for item_id, rarity, unlock in entries:
            if unlock == "premiumOnly":
                dropped += 1
                continue
            if item_id in seen or item_id == "none":
                continue
            seen.add(item_id)
            rows.append((item_id, rarity))
        if rows:
            kept[slot] = rows

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write('"""GENERATED by frontend/scripts/gen-bot-cosmetics.py'
                ' — do not edit.\n\n')
        f.write("What the seeded players are allowed to wear: the client\n"
                "wardrobe minus the PASER PRO exclusives. See the generator\n"
                'for why only those are held back.\n"""\n\n')
        f.write("# slot -> [(item_id, rarity)]\n")
        f.write("SLOT_ITEMS = {\n")
        for slot, rows in kept.items():
            f.write(f"    {slot!r}: [\n")
            for item_id, rarity in rows:
                f.write(f"        ({item_id!r}, {rarity!r}),\n")
            f.write("    ],\n")
        f.write("}\n")

    total = sum(len(v) for v in kept.values())
    print(f"wrote {os.path.normpath(OUT)}")
    print(f"  {total} items across {len(kept)} slots ({dropped} PRO exclusives held back)")
    for slot, rows in kept.items():
        print(f"    {slot:<10} {len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
