"""Measure every headwear item's UNDERSIDE from its own art, for the sky rule
in src/config/headwearFit.js: under a crown-covering hat no hair may show
above the hat's lower edge in any column the hat occupies (hair cannot grow
through a brim or out of a crown).

Per column of the hat's front art, the lowest opaque pixel is the hat's
underside there (a hat is one filled silhouette, so nothing of it hangs
below). Columns are sampled every few art px, runs of empty columns split the
outline (the gap between two ears), and each run is simplified to a polyline.
Everything is in the hat ART's own fractions (x 0..1 across the image, y 0..1
down it), so moving or resizing the hat in the Fit Studio does not stale it;
the rig places it with the hat's frame at draw time. Re-run after new or
re-drawn headwear art:

    python scripts/measure-hat-underside.py   # writes src/config/hatUndersides.json
"""
import json
import os
import subprocess

import numpy as np
from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
OUT = os.path.join(ROOT, 'src', 'config', 'hatUndersides.json')
STEP = 4            # art px between sampled columns
ALPHA = 128         # opaque enough to count as the hat
TOL = 0.004         # polyline simplification tolerance, art fractions


def catalog():
    r = subprocess.run(['node', os.path.join('scripts', 'dump-hair-headwear.js')], cwd=ROOT,
                       capture_output=True, text=True, encoding='utf8')
    if r.returncode:
        raise SystemExit(r.stderr)
    return json.loads(r.stdout)


def simplify(pts, tol):
    """Ramer-Douglas-Peucker."""
    if len(pts) < 3:
        return pts
    (x0, y0), (x1, y1) = pts[0], pts[-1]
    dx, dy = x1 - x0, y1 - y0
    norm = (dx * dx + dy * dy) ** 0.5 or 1e-9
    dists = [abs(dy * (x - x0) - dx * (y - y0)) / norm for x, y in pts[1:-1]]
    i = int(np.argmax(dists)) + 1
    if dists[i - 1] <= tol:
        return [pts[0], pts[-1]]
    return simplify(pts[:i + 1], tol)[:-1] + simplify(pts[i:], tol)


def underside(path):
    a = np.asarray(Image.open(os.path.join(ROOT, path)).convert('RGBA').getchannel('A')) > ALPHA
    h, w = a.shape
    runs, run = [], []
    cols = list(range(0, w, STEP))
    if cols[-1] != w - 1:
        cols.append(w - 1)
    for c in cols:
        col = a[:, c]
        if not col.any():
            if run:
                runs.append(run)
                run = []
            continue
        bottom = h - int(np.argmax(col[::-1]))       # one past the lowest ink
        run.append((c / w, bottom / h))
    if run:
        runs.append(run)
    out = []
    for r in runs:
        if len(r) < 2:
            continue
        # Close each run on the art's own edge columns so the outline spans
        # the whole ink, not just the sampled columns inside it.
        pts = simplify(r, TOL)
        out.append([[round(x, 4), round(y, 4)] for x, y in pts])
    return out


def main():
    cat = catalog()
    data = {}
    for it in cat['headwear']:
        if it['id'] == 'none':
            continue
        p = it.get('img') or (it.get('art') or [None])[0]
        if p:
            data[it['id']] = underside(p)
    body = {
        '_doc': 'Generated by scripts/measure-hat-underside.py, not by hand. Per headwear id: the '
                "hat's underside as polylines in its front ART's fractions (x 0..1 across, y 0..1 "
                'down), one per run of occupied columns. src/config/headwearFit.js hides hair above '
                'it under crown-covering families (the sky rule).',
        'hats': data,
    }
    with open(OUT, 'w', encoding='utf8', newline='\n') as fh:
        json.dump(body, fh, separators=(',', ':'))
        fh.write('\n')
    n = sum(len(v) for v in data.values())
    print(f'measured {len(data)} headwear items, {n} outlines -> {OUT}')


if __name__ == '__main__':
    main()
