"""Measure every border ring's inner opening — centre AND diameter — and
rewrite src/config/borderArt.js.

WHY A THIRD MEASUREMENT PASS
remeasure-border-holes.py cast rays from the ART's centre and took the median
hit radius. That fixes an ornament poking inward, but it still assumes the
opening is CONCENTRIC with the square canvas, and on the ornate tiers it is
not: prismatic's crystal crown and mythic's flame sit above the band, so the
ring is pushed to the bottom of its canvas and the opening's centre is well
below the middle. Drawing the portrait at the canvas centre then leaves a
crescent of background at the bottom of the frame and rides over the top —
the gap this script exists to kill.

THE MEASUREMENT
1. opaque = alpha > 40.
2. Flood the transparent pixels inward from the canvas edge; whatever
   transparency that flood cannot reach is ENCLOSED — the ring's opening.
3. Distance transform over the opening: its maximum locates the largest circle
   that fits inside, and that point is the opening's CENTRE.
4. From that centre, take the distance to the FARTHEST opening pixel. That is
   the circle which COVERS the whole opening — i.e. the band's inner edge.

Covering, not fitting, is the right target. PortraitBorder composites the ring
ON TOP of the portrait, so a portrait sized to the covering circle reaches the
band's inner edge at its widest point and tucks harmlessly under the frame
everywhere else. Sizing it to the inscribed circle instead — what the previous
pass effectively did — leaves the opening's wider directions uncovered, and
that bare crescent of background is the gap this script exists to kill. The
covering circle can never spill past the band, because by construction every
pixel outside it in that direction is already opaque frame.

Run from frontend/:  python scripts/measure-border-holes-3.py
"""
import os
import re

import numpy as np
from PIL import Image
from scipy import ndimage

FE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BORDERS = os.path.join(FE, "assets", "borders")
CFG = os.path.join(FE, "src", "config", "borderArt.js")

ALPHA_THR = 40
# Nudge the covering circle out by 1.5% so the portrait's rim lands just under
# the band's inner edge rather than exactly on it (anti-aliasing + rounding).
BLEED = 1.015


def measure(path):
    a = np.asarray(Image.open(path).convert("RGBA"))
    H, W = a.shape[:2]
    opaque = a[..., 3] > ALPHA_THR

    # Transparent pixels reachable from the canvas edge = the outside.
    transparent = ~opaque
    seeds = np.zeros_like(transparent)
    seeds[0, :] = seeds[-1, :] = True
    seeds[:, 0] = seeds[:, -1] = True
    seeds &= transparent
    outside = ndimage.binary_propagation(seeds, mask=transparent)

    hole = transparent & ~outside
    if not hole.any():
        raise SystemExit(f"{os.path.basename(path)}: no enclosed opening found")

    # Keep only the largest enclosed region — small trapped pockets between
    # ornaments (the gaps between prismatic's crystals) are not the opening.
    lbl, n = ndimage.label(hole)
    if n > 1:
        sizes = ndimage.sum(hole, lbl, range(1, n + 1))
        hole = lbl == (int(np.argmax(sizes)) + 1)

    dist = ndimage.distance_transform_edt(hole)
    cy, cx = np.unravel_index(int(np.argmax(dist)), dist.shape)

    ys, xs = np.nonzero(hole)
    r = float(np.sqrt(((xs - cx) ** 2 + (ys - cy) ** 2).max())) * BLEED

    return {
        "hole": round(r * 2.0 / W, 4),   # opening diameter / art width
        "cx": round(float(cx) / W, 4),   # opening centre, as a fraction of the art
        "cy": round(float(cy) / H, 4),
    }


def main():
    src = open(CFG, encoding="utf-8").read()
    entries = re.findall(
        r"(\w+): \{ src: (require\([^)]*\)),[^}]*\}", src)
    assert entries, "no border entries found"

    lines = []
    for key, req in entries:
        path = os.path.join(BORDERS, key + ".png")
        if not os.path.exists(path):
            print(f"  {key:11s} MISSING art — skipped")
            continue
        m = measure(path)
        lines.append(
            f"  {key}: {{ src: {req}, hole: {m['hole']}, "
            f"cx: {m['cx']}, cy: {m['cy']} }},")
        print(f"  {key:11s} hole {m['hole']:.4f}  centre "
              f"({m['cx']:.4f}, {m['cy']:.4f})")

    body = "\n".join(lines)
    out = re.sub(r"export const BORDER_ART = \{.*?\n\};",
                 "export const BORDER_ART = {\n" + body + "\n};",
                 src, flags=re.S)
    out = re.sub(r"^// GENERATED by.*?\n(?://.*\n)*",
                 "// GENERATED by scripts/measure-border-holes-3.py — do not hand-edit.\n"
                 "// Per tier: the circle that COVERS the ring's inner opening. `hole` is\n"
                 "// its diameter as a fraction of the square art, `cx`/`cy` its centre.\n"
                 "// The opening is NOT concentric with the canvas on the ornate tiers\n"
                 "// (crowns and flames push the band down), so PortraitBorder needs the\n"
                 "// centre as well as the size to seat a portrait without a gap.\n",
                 out, count=1, flags=re.M)
    open(CFG, "w", encoding="utf-8", newline="\n").write(out)
    print(f"\nwrote {os.path.relpath(CFG, FE)}")


if __name__ == "__main__":
    main()
