"""SUPERSEDED by scripts/measure-border-holes-3.py — do not run this.

It writes `hole` alone, and PortraitBorder now also needs the opening's CENTRE
(`cx`/`cy`): the ornate rings are not concentric with their canvas, so a hole
size on its own still leaves a gap along one edge of the frame. Running this
would strip those fields and reopen the bug. Kept only for the write-up below.

Re-measure every border ring's inner opening and rewrite borderArt.js.

WHY THIS EXISTED
PortraitBorder draws the ring at `size / hole`, so `hole` decides where the
portrait's edge lands relative to the frame. slice-borders-2.py measured it as
the BOUNDING BOX of the carved-out hole:

    ratio = min(box_width, box_height) / 1024

which is wrong for every ornate tier. The mythic wreath's flame intrudes from
the top and the gold ring's pendant from the bottom, so the box gets shorter
than the opening actually is, `min()` takes that shortened side, and the
portrait is drawn too small — a visible dark gap between the portrait and the
ring. Mythic was understated by 0.098, gold by 0.079.

THE MEASUREMENT
Cast rays from the centre and record where each first hits opaque pixels; the
opening is the MEDIAN of those radii. The median ignores both an ornament
poking inward (a few short rays) and a gap in the band (a few long ones),
which is exactly the pair of failure modes the box measure fell for.

Erring slightly large is safe here and erring small is not: PortraitBorder
composites the ring ON TOP of the portrait, so a hole read a little generous
just tucks the portrait's rim under the frame, while one read small leaves the
gap this script fixes.

Run from frontend/:  python scripts/remeasure-border-holes.py
"""
import os
import re

import numpy as np
from PIL import Image

FE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BORDERS = os.path.join(FE, "assets", "borders")
CFG = os.path.join(FE, "src", "config", "borderArt.js")
RAYS = 1440


def hole_ratio(path, rays=RAYS, alpha_thr=40):
    a = np.asarray(Image.open(path).convert("RGBA"))
    H, W = a.shape[:2]
    cy, cx = H / 2.0, W / 2.0
    opaque = a[..., 3] > alpha_thr
    limit = min(H, W) / 2.0
    radii = []
    for ang in np.linspace(0, 2 * np.pi, rays, endpoint=False):
        dy, dx = np.sin(ang), np.cos(ang)
        r = 0.0
        while r < limit:
            if opaque[int(cy + dy * r), int(cx + dx * r)]:
                break
            r += 0.5
        radii.append(r)
    return float(np.median(radii)) * 2.0 / W


def main():
    src = open(CFG, encoding="utf-8").read()
    entries = re.findall(r"(\w+): \{ src: (require\([^)]*\)), hole: ([\d.]+) \}", src)
    assert entries, "no border entries found"

    out = src
    for key, req, old in entries:
        path = os.path.join(BORDERS, key + ".png")
        if not os.path.exists(path):
            print(f"  {key:11s} MISSING art, left at {old}")
            continue
        new = round(hole_ratio(path), 4)
        out = out.replace(f"{key}: {{ src: {req}, hole: {old} }}",
                          f"{key}: {{ src: {req}, hole: {new} }}")
        print(f"  {key:11s} {old} -> {new:.4f}  ({new - float(old):+.4f})")

    out = out.replace(
        "// GENERATED by scripts/slice-borders-2.py — do not hand-edit.",
        "// GENERATED by scripts/slice-borders-2.py, holes re-measured by\n"
        "// scripts/remeasure-border-holes.py — do not hand-edit.")
    open(CFG, "w", encoding="utf-8", newline="\n").write(out)
    print(f"\nwrote {os.path.relpath(CFG, FE)}")


if __name__ == "__main__":
    main()
