"""Slice the portrait-border tier sheet and measure each ring's inner hole.

Rings are drawn tight to their own bounds, and each tier's hole is a different
fraction of its outer size (a spiked onyx ring is chunkier than a thin silver
one). PortraitBorder needs the PORTRAIT to sit exactly in that hole, so rather
than eyeballing a scale per tier we measure the hole here and emit the ratios.

Emits: assets/borders/<key>.png  +  src/config/borderArt.js
"""
import os
import numpy as np
from PIL import Image
from scipy import ndimage

SRC = r"D:\downloads\ChatGPT Image Jul 30, 2026, 04_56_54 PM.png"
FE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(FE, "assets", "borders")
os.makedirs(OUT, exist_ok=True)

# Reading order on the sheet == the tier order in config/progression.js
KEYS = ["wood", "bronze", "silver", "gold", "platinum",
        "diamond", "onyx", "ember", "prismatic", "mythic"]

im = Image.open(SRC).convert("RGB")
a = np.asarray(im).astype(int)
lum = a @ [0.299, 0.587, 0.114]
neutral = (a.max(axis=2) - a.min(axis=2)) <= 14
bg = (lum >= 238) & neutral

lab, n = ndimage.label(bg)
ids = np.unique(np.concatenate([lab[0], lab[-1], lab[:, 0], lab[:, -1]]))
outside = np.isin(lab, ids[ids != 0])
solid = ~outside

lab2, n2 = ndimage.label(ndimage.binary_closing(solid, np.ones((5, 5))))
boxes = []
for i, sl in enumerate(ndimage.find_objects(lab2), start=1):
    ys, xs = sl
    h, w = ys.stop - ys.start, xs.stop - xs.start
    if h * w < 12000 or h < 60 or w < 60:
        continue
    boxes.append((xs.start, ys.start, xs.stop, ys.stop, i))
boxes.sort(key=lambda b: (round(b[1] / 200), b[0]))
print(f"{len(boxes)} rings detected")

ratios = {}
for k, (x0, y0, x1, y1, lid) in enumerate(boxes):
    if k >= len(KEYS):
        break
    key = KEYS[k]
    comp = lab2[y0:y1, x0:x1] == lid
    rgb = np.asarray(im)[y0:y1, x0:x1]

    # The ring's centre is ENCLOSED white, so the border-connected flood above
    # never reached it. Within this ring's box, any white blob that doesn't
    # touch the box edge and is big is the hole; small ones are metal
    # highlights and must stay opaque.
    bh, bw = comp.shape
    white = bg[y0:y1, x0:x1]
    wl, wn = ndimage.label(white)
    edge_ids = set(np.unique(np.concatenate([wl[0], wl[-1], wl[:, 0], wl[:, -1]])))
    hole_mask = np.zeros_like(comp)
    for wi in range(1, wn + 1):
        if wi in edge_ids:
            continue
        blob = wl == wi
        if blob.sum() > 0.05 * bh * bw:
            hole_mask |= blob
    comp = comp & ~hole_mask
    alpha = np.where(comp, 255, 0).astype(np.uint8)

    # pad to square so the ring stays centred when scaled
    h, w = alpha.shape
    s = max(h, w)
    sq_rgb = np.zeros((s, s, 3), np.uint8)
    sq_a = np.zeros((s, s), np.uint8)
    oy, ox = (s - h) // 2, (s - w) // 2
    sq_rgb[oy:oy + h, ox:ox + w] = rgb
    sq_a[oy:oy + h, ox:ox + w] = alpha

    # the hole: transparent region containing the centre
    holes, hn = ndimage.label(sq_a == 0)
    cid = holes[s // 2, s // 2]
    if cid == 0:                      # centre covered — fall back to a default
        ratio = 0.66
    else:
        hole = holes == cid
        hys, hxs = np.where(hole)
        ratio = min(hxs.max() - hxs.min(), hys.max() - hys.min()) / s
    ratios[key] = round(float(ratio), 4)

    out = np.dstack([sq_rgb, sq_a])
    img = Image.fromarray(out, "RGBA").resize((1024, 1024), Image.LANCZOS)
    img.save(os.path.join(OUT, f"{key}.png"), optimize=True)
    print(f"  {key:11s} {w}x{h}  hole ratio {ratio:.3f}")

cfg = os.path.join(FE, "src", "config", "borderArt.js")
with open(cfg, "w", encoding="utf-8", newline="\n") as f:
    f.write(
        "// GENERATED by scripts/slice-borders.py — do not hand-edit.\n"
        "// Ring art per level tier, plus the measured HOLE RATIO: the inner\n"
        "// opening as a fraction of the (square) art. PortraitBorder scales the\n"
        "// ring by 1/ratio so the portrait fills the hole exactly, whatever the\n"
        "// tier's frame thickness.\n\n"
        "export const BORDER_ART = {\n")
    for key in KEYS:
        if key in ratios:
            f.write(f"  {key}: {{ src: require('../../assets/borders/{key}.png'), "
                    f"hole: {ratios[key]} }},\n")
    f.write("};\n\nexport default BORDER_ART;\n")
print("wrote src/config/borderArt.js")
