// GENERATED by scripts/slice-borders.py — do not hand-edit.
// Ring art per level tier, plus the measured HOLE RATIO: the inner
// opening as a fraction of the (square) art. PortraitBorder scales the
// ring by 1/ratio so the portrait fills the hole exactly, whatever the
// tier's frame thickness.

export const BORDER_ART = {
  wood: { src: require('../../assets/borders/wood.png'), hole: 0.6471 },
  bronze: { src: require('../../assets/borders/bronze.png'), hole: 0.6264 },
  silver: { src: require('../../assets/borders/silver.png'), hole: 0.6531 },
  gold: { src: require('../../assets/borders/gold.png'), hole: 0.6154 },
  platinum: { src: require('../../assets/borders/platinum.png'), hole: 0.6241 },
  diamond: { src: require('../../assets/borders/diamond.png'), hole: 0.5705 },
  onyx: { src: require('../../assets/borders/onyx.png'), hole: 0.5541 },
  ember: { src: require('../../assets/borders/ember.png'), hole: 0.5449 },
  prismatic: { src: require('../../assets/borders/prismatic.png'), hole: 0.521 },
  mythic: { src: require('../../assets/borders/mythic.png'), hole: 0.4873 },
};

export default BORDER_ART;
