// GENERATED by scripts/measure-border-holes-3.py — do not hand-edit.
// Per tier: the circle that COVERS the ring's inner opening. `hole` is
// its diameter as a fraction of the square art, `cx`/`cy` its centre.
// The opening is NOT concentric with the canvas on the ornate tiers
// (crowns and flames push the band down), so PortraitBorder needs the
// centre as well as the size to seat a portrait without a gap.

export const BORDER_ART = {
  wood: { src: require('../../assets/borders/wood.png'), hole: 0.9118, cx: 0.5117, cy: 0.4717 },
  bronze: { src: require('../../assets/borders/bronze.png'), hole: 0.8542, cx: 0.4961, cy: 0.4932 },
  silver: { src: require('../../assets/borders/silver.png'), hole: 0.8347, cx: 0.501, cy: 0.4951 },
  gold: { src: require('../../assets/borders/gold.png'), hole: 0.8156, cx: 0.5, cy: 0.4189 },
  platinum: { src: require('../../assets/borders/platinum.png'), hole: 0.801, cx: 0.502, cy: 0.4922 },
  diamond: { src: require('../../assets/borders/diamond.png'), hole: 0.7982, cx: 0.5, cy: 0.4922 },
  onyx: { src: require('../../assets/borders/onyx.png'), hole: 0.6225, cx: 0.502, cy: 0.5029 },
  ember: { src: require('../../assets/borders/ember.png'), hole: 0.6495, cx: 0.498, cy: 0.5098 },
  prismatic: { src: require('../../assets/borders/prismatic.png'), hole: 0.7662, cx: 0.502, cy: 0.5762 },
  mythic: { src: require('../../assets/borders/mythic.png'), hole: 0.8324, cx: 0.4961, cy: 0.5615 },
};

export default BORDER_ART;
