// GENERATED by scripts/slice-borders-2.py — do not hand-edit.
// Ring art per tier + the measured HOLE RATIO: the inner opening as a
// fraction of the square art. PortraitBorder scales by 1/hole so the
// portrait fills the opening exactly at any frame thickness.

export const BORDER_ART = {
  wood: { src: require('../../assets/borders/wood.png'), hole: 0.7939 },
  bronze: { src: require('../../assets/borders/bronze.png'), hole: 0.792 },
  silver: { src: require('../../assets/borders/silver.png'), hole: 0.7549 },
  gold: { src: require('../../assets/borders/gold.png'), hole: 0.7051 },
  platinum: { src: require('../../assets/borders/platinum.png'), hole: 0.7549 },
  diamond: { src: require('../../assets/borders/diamond.png'), hole: 0.7441 },
  onyx: { src: require('../../assets/borders/onyx.png'), hole: 0.5898 },
  ember: { src: require('../../assets/borders/ember.png'), hole: 0.6182 },
  prismatic: { src: require('../../assets/borders/prismatic.png'), hole: 0.6943 },
  mythic: { src: require('../../assets/borders/mythic.png'), hole: 0.6992 },
};

export default BORDER_ART;
