// GENERATED — color-variant art index (one require per palette entry).
// Regenerate with the asset pipeline script; do not hand-edit the arrays.
// Keyed by base asset name; array index = palette index in cosmetics.js.

export const ART = {
  hairM1: [require('../../assets/character/hair/hairM1_0.png'), require('../../assets/character/hair/hairM1_1.png'), require('../../assets/character/hair/hairM1_2.png'), require('../../assets/character/hair/hairM1_3.png'), require('../../assets/character/hair/hairM1_4.png'), require('../../assets/character/hair/hairM1_5.png'), require('../../assets/character/hair/hairM1_6.png'), require('../../assets/character/hair/hairM1_7.png'), require('../../assets/character/hair/hairM1_8.png'), require('../../assets/character/hair/hairM1_9.png')],
  hairM2: [require('../../assets/character/hair/hairM2_0.png'), require('../../assets/character/hair/hairM2_1.png'), require('../../assets/character/hair/hairM2_2.png'), require('../../assets/character/hair/hairM2_3.png'), require('../../assets/character/hair/hairM2_4.png'), require('../../assets/character/hair/hairM2_5.png'), require('../../assets/character/hair/hairM2_6.png'), require('../../assets/character/hair/hairM2_7.png'), require('../../assets/character/hair/hairM2_8.png'), require('../../assets/character/hair/hairM2_9.png')],
  hairM3: [require('../../assets/character/hair/hairM3_0.png'), require('../../assets/character/hair/hairM3_1.png'), require('../../assets/character/hair/hairM3_2.png'), require('../../assets/character/hair/hairM3_3.png'), require('../../assets/character/hair/hairM3_4.png'), require('../../assets/character/hair/hairM3_5.png'), require('../../assets/character/hair/hairM3_6.png'), require('../../assets/character/hair/hairM3_7.png'), require('../../assets/character/hair/hairM3_8.png'), require('../../assets/character/hair/hairM3_9.png')],
  hairM5: [require('../../assets/character/hair/hairM5_0.png'), require('../../assets/character/hair/hairM5_1.png'), require('../../assets/character/hair/hairM5_2.png'), require('../../assets/character/hair/hairM5_3.png'), require('../../assets/character/hair/hairM5_4.png'), require('../../assets/character/hair/hairM5_5.png'), require('../../assets/character/hair/hairM5_6.png'), require('../../assets/character/hair/hairM5_7.png'), require('../../assets/character/hair/hairM5_8.png'), require('../../assets/character/hair/hairM5_9.png')],
  hairM6: [require('../../assets/character/hair/hairM6_0.png'), require('../../assets/character/hair/hairM6_1.png'), require('../../assets/character/hair/hairM6_2.png'), require('../../assets/character/hair/hairM6_3.png'), require('../../assets/character/hair/hairM6_4.png'), require('../../assets/character/hair/hairM6_5.png'), require('../../assets/character/hair/hairM6_6.png'), require('../../assets/character/hair/hairM6_7.png'), require('../../assets/character/hair/hairM6_8.png'), require('../../assets/character/hair/hairM6_9.png')],
  hairM7: [require('../../assets/character/hair/hairM7_0.png'), require('../../assets/character/hair/hairM7_1.png'), require('../../assets/character/hair/hairM7_2.png'), require('../../assets/character/hair/hairM7_3.png'), require('../../assets/character/hair/hairM7_4.png'), require('../../assets/character/hair/hairM7_5.png'), require('../../assets/character/hair/hairM7_6.png'), require('../../assets/character/hair/hairM7_7.png'), require('../../assets/character/hair/hairM7_8.png'), require('../../assets/character/hair/hairM7_9.png')],
  hairM8: [require('../../assets/character/hair/hairM8_0.png'), require('../../assets/character/hair/hairM8_1.png'), require('../../assets/character/hair/hairM8_2.png'), require('../../assets/character/hair/hairM8_3.png'), require('../../assets/character/hair/hairM8_4.png'), require('../../assets/character/hair/hairM8_5.png'), require('../../assets/character/hair/hairM8_6.png'), require('../../assets/character/hair/hairM8_7.png'), require('../../assets/character/hair/hairM8_8.png'), require('../../assets/character/hair/hairM8_9.png')],
  hairM9: [require('../../assets/character/hair/hairM9_0.png'), require('../../assets/character/hair/hairM9_1.png'), require('../../assets/character/hair/hairM9_2.png'), require('../../assets/character/hair/hairM9_3.png'), require('../../assets/character/hair/hairM9_4.png'), require('../../assets/character/hair/hairM9_5.png'), require('../../assets/character/hair/hairM9_6.png'), require('../../assets/character/hair/hairM9_7.png'), require('../../assets/character/hair/hairM9_8.png'), require('../../assets/character/hair/hairM9_9.png')],
  hairM10: [require('../../assets/character/hair/hairM10_0.png'), require('../../assets/character/hair/hairM10_1.png'), require('../../assets/character/hair/hairM10_2.png'), require('../../assets/character/hair/hairM10_3.png'), require('../../assets/character/hair/hairM10_4.png'), require('../../assets/character/hair/hairM10_5.png'), require('../../assets/character/hair/hairM10_6.png'), require('../../assets/character/hair/hairM10_7.png'), require('../../assets/character/hair/hairM10_8.png'), require('../../assets/character/hair/hairM10_9.png')],
  hairW1: [require('../../assets/character/hair/hairW1_0.png'), require('../../assets/character/hair/hairW1_1.png'), require('../../assets/character/hair/hairW1_2.png'), require('../../assets/character/hair/hairW1_3.png'), require('../../assets/character/hair/hairW1_4.png'), require('../../assets/character/hair/hairW1_5.png'), require('../../assets/character/hair/hairW1_6.png'), require('../../assets/character/hair/hairW1_7.png'), require('../../assets/character/hair/hairW1_8.png'), require('../../assets/character/hair/hairW1_9.png')],
  hairW2: [require('../../assets/character/hair/hairW2_0.png'), require('../../assets/character/hair/hairW2_1.png'), require('../../assets/character/hair/hairW2_2.png'), require('../../assets/character/hair/hairW2_3.png'), require('../../assets/character/hair/hairW2_4.png'), require('../../assets/character/hair/hairW2_5.png'), require('../../assets/character/hair/hairW2_6.png'), require('../../assets/character/hair/hairW2_7.png'), require('../../assets/character/hair/hairW2_8.png'), require('../../assets/character/hair/hairW2_9.png')],
  hairW4: [require('../../assets/character/hair/hairW4_0.png'), require('../../assets/character/hair/hairW4_1.png'), require('../../assets/character/hair/hairW4_2.png'), require('../../assets/character/hair/hairW4_3.png'), require('../../assets/character/hair/hairW4_4.png'), require('../../assets/character/hair/hairW4_5.png'), require('../../assets/character/hair/hairW4_6.png'), require('../../assets/character/hair/hairW4_7.png'), require('../../assets/character/hair/hairW4_8.png'), require('../../assets/character/hair/hairW4_9.png')],
  hairW5: [require('../../assets/character/hair/hairW5_0.png'), require('../../assets/character/hair/hairW5_1.png'), require('../../assets/character/hair/hairW5_2.png'), require('../../assets/character/hair/hairW5_3.png'), require('../../assets/character/hair/hairW5_4.png'), require('../../assets/character/hair/hairW5_5.png'), require('../../assets/character/hair/hairW5_6.png'), require('../../assets/character/hair/hairW5_7.png'), require('../../assets/character/hair/hairW5_8.png'), require('../../assets/character/hair/hairW5_9.png')],
  hairW6: [require('../../assets/character/hair/hairW6_0.png'), require('../../assets/character/hair/hairW6_1.png'), require('../../assets/character/hair/hairW6_2.png'), require('../../assets/character/hair/hairW6_3.png'), require('../../assets/character/hair/hairW6_4.png'), require('../../assets/character/hair/hairW6_5.png'), require('../../assets/character/hair/hairW6_6.png'), require('../../assets/character/hair/hairW6_7.png'), require('../../assets/character/hair/hairW6_8.png'), require('../../assets/character/hair/hairW6_9.png')],
  hairW7: [require('../../assets/character/hair/hairW7_0.png'), require('../../assets/character/hair/hairW7_1.png'), require('../../assets/character/hair/hairW7_2.png'), require('../../assets/character/hair/hairW7_3.png'), require('../../assets/character/hair/hairW7_4.png'), require('../../assets/character/hair/hairW7_5.png'), require('../../assets/character/hair/hairW7_6.png'), require('../../assets/character/hair/hairW7_7.png'), require('../../assets/character/hair/hairW7_8.png'), require('../../assets/character/hair/hairW7_9.png')],
  hairW8: [require('../../assets/character/hair/hairW8_0.png'), require('../../assets/character/hair/hairW8_1.png'), require('../../assets/character/hair/hairW8_2.png'), require('../../assets/character/hair/hairW8_3.png'), require('../../assets/character/hair/hairW8_4.png'), require('../../assets/character/hair/hairW8_5.png'), require('../../assets/character/hair/hairW8_6.png'), require('../../assets/character/hair/hairW8_7.png'), require('../../assets/character/hair/hairW8_8.png'), require('../../assets/character/hair/hairW8_9.png')],
  hairW9: [require('../../assets/character/hair/hairW9_0.png'), require('../../assets/character/hair/hairW9_1.png'), require('../../assets/character/hair/hairW9_2.png'), require('../../assets/character/hair/hairW9_3.png'), require('../../assets/character/hair/hairW9_4.png'), require('../../assets/character/hair/hairW9_5.png'), require('../../assets/character/hair/hairW9_6.png'), require('../../assets/character/hair/hairW9_7.png'), require('../../assets/character/hair/hairW9_8.png'), require('../../assets/character/hair/hairW9_9.png')],
  hairW10: [require('../../assets/character/hair/hairW10_0.png'), require('../../assets/character/hair/hairW10_1.png'), require('../../assets/character/hair/hairW10_2.png'), require('../../assets/character/hair/hairW10_3.png'), require('../../assets/character/hair/hairW10_4.png'), require('../../assets/character/hair/hairW10_5.png'), require('../../assets/character/hair/hairW10_6.png'), require('../../assets/character/hair/hairW10_7.png'), require('../../assets/character/hair/hairW10_8.png'), require('../../assets/character/hair/hairW10_9.png')],
  hairW11: [require('../../assets/character/hair/hairW11_0.png'), require('../../assets/character/hair/hairW11_1.png'), require('../../assets/character/hair/hairW11_2.png'), require('../../assets/character/hair/hairW11_3.png'), require('../../assets/character/hair/hairW11_4.png'), require('../../assets/character/hair/hairW11_5.png'), require('../../assets/character/hair/hairW11_6.png'), require('../../assets/character/hair/hairW11_7.png'), require('../../assets/character/hair/hairW11_8.png'), require('../../assets/character/hair/hairW11_9.png')],
  hairW12: [require('../../assets/character/hair/hairW12_0.png'), require('../../assets/character/hair/hairW12_1.png'), require('../../assets/character/hair/hairW12_2.png'), require('../../assets/character/hair/hairW12_3.png'), require('../../assets/character/hair/hairW12_4.png'), require('../../assets/character/hair/hairW12_5.png'), require('../../assets/character/hair/hairW12_6.png'), require('../../assets/character/hair/hairW12_7.png'), require('../../assets/character/hair/hairW12_8.png'), require('../../assets/character/hair/hairW12_9.png')],
  hairW14: [require('../../assets/character/hair/hairW14_0.png'), require('../../assets/character/hair/hairW14_1.png'), require('../../assets/character/hair/hairW14_2.png'), require('../../assets/character/hair/hairW14_3.png'), require('../../assets/character/hair/hairW14_4.png'), require('../../assets/character/hair/hairW14_5.png'), require('../../assets/character/hair/hairW14_6.png'), require('../../assets/character/hair/hairW14_7.png'), require('../../assets/character/hair/hairW14_8.png'), require('../../assets/character/hair/hairW14_9.png')],
  hairW15: [require('../../assets/character/hair/hairW15_0.png'), require('../../assets/character/hair/hairW15_1.png'), require('../../assets/character/hair/hairW15_2.png'), require('../../assets/character/hair/hairW15_3.png'), require('../../assets/character/hair/hairW15_4.png'), require('../../assets/character/hair/hairW15_5.png'), require('../../assets/character/hair/hairW15_6.png'), require('../../assets/character/hair/hairW15_7.png'), require('../../assets/character/hair/hairW15_8.png'), require('../../assets/character/hair/hairW15_9.png')],
  hairW16: [require('../../assets/character/hair/hairW16_0.png'), require('../../assets/character/hair/hairW16_1.png'), require('../../assets/character/hair/hairW16_2.png'), require('../../assets/character/hair/hairW16_3.png'), require('../../assets/character/hair/hairW16_4.png'), require('../../assets/character/hair/hairW16_5.png'), require('../../assets/character/hair/hairW16_6.png'), require('../../assets/character/hair/hairW16_7.png'), require('../../assets/character/hair/hairW16_8.png'), require('../../assets/character/hair/hairW16_9.png')],
  hairW17: [require('../../assets/character/hair/hairW17_0.png'), require('../../assets/character/hair/hairW17_1.png'), require('../../assets/character/hair/hairW17_2.png'), require('../../assets/character/hair/hairW17_3.png'), require('../../assets/character/hair/hairW17_4.png'), require('../../assets/character/hair/hairW17_5.png'), require('../../assets/character/hair/hairW17_6.png'), require('../../assets/character/hair/hairW17_7.png'), require('../../assets/character/hair/hairW17_8.png'), require('../../assets/character/hair/hairW17_9.png')],
  hairM11: [require('../../assets/character/hair/hairM11_0.png'), require('../../assets/character/hair/hairM11_1.png'), require('../../assets/character/hair/hairM11_2.png'), require('../../assets/character/hair/hairM11_3.png'), require('../../assets/character/hair/hairM11_4.png'), require('../../assets/character/hair/hairM11_5.png'), require('../../assets/character/hair/hairM11_6.png'), require('../../assets/character/hair/hairM11_7.png'), require('../../assets/character/hair/hairM11_8.png'), require('../../assets/character/hair/hairM11_9.png')],
  hairM12: [require('../../assets/character/hair/hairM12_0.png'), require('../../assets/character/hair/hairM12_1.png'), require('../../assets/character/hair/hairM12_2.png'), require('../../assets/character/hair/hairM12_3.png'), require('../../assets/character/hair/hairM12_4.png'), require('../../assets/character/hair/hairM12_5.png'), require('../../assets/character/hair/hairM12_6.png'), require('../../assets/character/hair/hairM12_7.png'), require('../../assets/character/hair/hairM12_8.png'), require('../../assets/character/hair/hairM12_9.png')],
  hairM13: [require('../../assets/character/hair/hairM13_0.png'), require('../../assets/character/hair/hairM13_1.png'), require('../../assets/character/hair/hairM13_2.png'), require('../../assets/character/hair/hairM13_3.png'), require('../../assets/character/hair/hairM13_4.png'), require('../../assets/character/hair/hairM13_5.png'), require('../../assets/character/hair/hairM13_6.png'), require('../../assets/character/hair/hairM13_7.png'), require('../../assets/character/hair/hairM13_8.png'), require('../../assets/character/hair/hairM13_9.png')],
  hairM14: [require('../../assets/character/hair/hairM14_0.png'), require('../../assets/character/hair/hairM14_1.png'), require('../../assets/character/hair/hairM14_2.png'), require('../../assets/character/hair/hairM14_3.png'), require('../../assets/character/hair/hairM14_4.png'), require('../../assets/character/hair/hairM14_5.png'), require('../../assets/character/hair/hairM14_6.png'), require('../../assets/character/hair/hairM14_7.png'), require('../../assets/character/hair/hairM14_8.png'), require('../../assets/character/hair/hairM14_9.png')],
};
