// Companion metadata for the live cosmetic catalogue.
//
// This file is deliberately DATA ONLY. It does not participate in unlocks,
// ownership, rendering, lootboxes, progression, or FIRST_RUN_ITEMS. IDs remain
// authoritative in cosmetics.js and its generated supplements.
//
// Keep one key per globally unique cosmetic ID. The legacy sentinel "none" is
// shared by six slots and therefore has one shared curation record. Run
// `npm run check:curation` after editing.
//
// Bootstrap convention: PRO/pass rewards start in `vault`; recognisably
// running, trail, club, or Singapore pieces start in `core`; ordinary casual
// and costume pieces start in `lifestyle`. `collection` remains null until
// named collections are curated. Generated wardrobe `family` values are
// carried across verbatim so colourways of one silhouette stay together.

export const COSMETIC_STATUSES = ['core', 'lifestyle', 'vault', 'retired'];
export const COSMETIC_THEMES = ['running', 'trail', 'club', 'singapore', 'casual', 'fantasy'];
export const COSMETIC_ACQUISITION_TYPES = [
  'starter', 'distance', 'runs', 'streak', 'zones', 'level', 'club',
  'lootbox', 'battlepass', 'pro', 'event', 'special', null,
];

export const COSMETIC_CURATION = {
  "angelheart": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "angelwings": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "angry": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "antlers": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"zones"},
  "aurorajacket": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"pro"},
  "aviatorcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "aviators": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "ballcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bandana": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "bangs": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "beam": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "beanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "beret": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "bigafro": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bigbow": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bikehelmet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "blackvest": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "bloomcrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "bluntbob": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "blush": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "boater": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "boaterhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bomber": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "boombox": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"pro"},
  "bowband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "bowberet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bowcami": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bowcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bowler": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bowtie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bowwrap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "braids": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bucket": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bunnyears": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "bunstrands": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "butterfly": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "butterflyclip": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "buzz": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "camisole": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "candyscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "canvasbucket": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "cap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cape": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "captaincap": {"status":"core","theme":"club","collection":null,"family":null,"acquisitionType":"zones"},
  "cardigan": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "catbeanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "catears": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cateye": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "charmchain": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "chefhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "cheftoque": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "cherrybopper": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "chill": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "classiccap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cleargoggles": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "clochehat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "clownglasses": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "comma": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "content": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cowboyhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "cowpokehat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "cuffbeanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "curls": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "curtainlong": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "curtains": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cybershades": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cyclejersey": {"status":"core","theme":"club","collection":null,"family":null,"acquisitionType":"distance"},
  "dadcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "daisyband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "daisydress": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "deadpan": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "denimjacket": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "derbyhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "determined": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "devilhorns": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "dogtags": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "dragonwings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "exhausted": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "eyepatch": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "fairywings": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "fedora": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "fez": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "firehelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "flamecrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "flatberet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "flatcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "flatsnap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "flightcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "flow": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "flowerchain": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "flowerclip": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "flowercrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "frilltop": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "fringebob": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "fringebun": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "frogbeanie": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "gaiter": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "gardenhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "gasp": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "glum": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "goldmedal": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "golfcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "gradcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "greenscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "greyhoodie": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "grump": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "halfframe": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "halo": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "haloring": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "handbag": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "hardhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "harness": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"distance"},
  "headdress": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "headphones": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "headscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "headwrap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "heart": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "heartbopper": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "hearteyes": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "heromask": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "hexshades": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "highbun": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "highpony": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "hijab": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "hs11": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs15": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs22": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs25": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs26": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hydrovest": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "jestercap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "jetpack": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"pro"},
  "jeweltiara": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "jockeycap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "joy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "judogi": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "k10t": {"status":"vault","theme":"club","collection":null,"family":"Varsity jacket","acquisitionType":"pro"},
  "k11t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Stripe polo","acquisitionType":"starter"},
  "k12t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop jacket","acquisitionType":"runs"},
  "k13t": {"status":"core","theme":"club","collection":null,"family":"Rugby shirt","acquisitionType":"starter"},
  "k14t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop puffer","acquisitionType":"starter"},
  "k15t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pocket hoodie","acquisitionType":"starter"},
  "k1t": {"status":"core","theme":"running","collection":null,"family":"Running vest","acquisitionType":"starter"},
  "k2t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Boxy tee","acquisitionType":"starter"},
  "k3t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Zip hoodie","acquisitionType":"starter"},
  "k4t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Raglan tee","acquisitionType":"starter"},
  "k5t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop tee","acquisitionType":"starter"},
  "k6t": {"status":"core","theme":"running","collection":null,"family":"Track hoodie","acquisitionType":"runs"},
  "k7t": {"status":"vault","theme":"casual","collection":null,"family":"Zip gilet","acquisitionType":"pro"},
  "k8t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Half zip","acquisitionType":"starter"},
  "k9t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Block hoodie","acquisitionType":"starter"},
  "kabuto": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "katanas": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "kittyears": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "knightarmor": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "knitbeanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "labcoat": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "lacebib": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "lacecollar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "laugh": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "laurel": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "laurelcrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "lei": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "letterman": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "longwaves": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "loveboppers": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "maidapron": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "maidband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "medallion": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"level"},
  "messengerbag": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "messy": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "middlepart": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "minerhelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "mirrorvisor": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "mobcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "monocle": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"pro"},
  "mortarboard": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "navycap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "neckerchief": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "necktie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "neonwings": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "neutral": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "newsboy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "none": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "nursecap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "o0t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Zip jacket","acquisitionType":"starter"},
  "o10t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Zip hoodie","acquisitionType":"starter"},
  "o12t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Tank top","acquisitionType":"starter"},
  "o13t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Ringer tee","acquisitionType":"runs"},
  "o14t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Loose tee","acquisitionType":"distance"},
  "o16t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Polo","acquisitionType":"starter"},
  "o18t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Loose tee","acquisitionType":"runs"},
  "o1t": {"status":"core","theme":"club","collection":null,"family":"Basketball vest","acquisitionType":"starter"},
  "o2t": {"status":"core","theme":"trail","collection":null,"family":"Polo","acquisitionType":"starter"},
  "o30t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Zip hoodie","acquisitionType":"starter"},
  "o31t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Tank top","acquisitionType":"starter"},
  "o36t": {"status":"core","theme":"running","collection":null,"family":"Track jacket","acquisitionType":"starter"},
  "o3t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Zip hoodie","acquisitionType":"runs"},
  "o40t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Layered vest","acquisitionType":"starter"},
  "o41t": {"status":"core","theme":"trail","collection":null,"family":"Camp shirt","acquisitionType":"starter"},
  "o45t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Stripe jacket","acquisitionType":"starter"},
  "o48t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Polo","acquisitionType":"runs"},
  "o49t": {"status":"vault","theme":"club","collection":null,"family":"Varsity jacket","acquisitionType":"battlepass"},
  "o4t": {"status":"vault","theme":"casual","collection":null,"family":"Crew tee","acquisitionType":"battlepass"},
  "o50t": {"status":"core","theme":"running","collection":null,"family":"Track jacket","acquisitionType":"starter"},
  "o54t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Shrug","acquisitionType":"runs"},
  "o56t": {"status":"core","theme":"running","collection":null,"family":"Sports bra","acquisitionType":"starter"},
  "o57t": {"status":"core","theme":"running","collection":null,"family":"Racer jacket","acquisitionType":"starter"},
  "o58o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "o59o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "o60o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "o61o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "o64o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "o66o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "o68t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pullover hoodie","acquisitionType":"runs"},
  "o69o": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"distance"},
  "o6t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop polo","acquisitionType":"starter"},
  "o70t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Flannel shirt","acquisitionType":"starter"},
  "o71t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Puffer vest","acquisitionType":"starter"},
  "o72t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Heart cardigan","acquisitionType":"starter"},
  "o78t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pullover hoodie","acquisitionType":"runs"},
  "o79o": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "o82t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Button cardigan","acquisitionType":"starter"},
  "o87t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Shirt jacket","acquisitionType":"starter"},
  "o88t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Hooded puffer","acquisitionType":"runs"},
  "o89t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bomber jacket","acquisitionType":"runs"},
  "o90t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Blazer","acquisitionType":"starter"},
  "o91t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Trucker jacket","acquisitionType":"starter"},
  "o92t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Long cardigan","acquisitionType":"starter"},
  "o93t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Blazer","acquisitionType":"runs"},
  "o94t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Striped knit","acquisitionType":"runs"},
  "o95t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Zip hoodie","acquisitionType":"starter"},
  "o9t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Loose tee","acquisitionType":"distance"},
  "officercap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "onimask": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "overshirt": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "oversized": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "pageantsash": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "paradeshako": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "pastelcardi": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "pearlcollar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "pearls": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "pearlspecs": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "pearltiara": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"streak"},
  "pinkbow": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "pinupwrap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "piratehat": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "pixelshades": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "pixie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "polo": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "pombeanie": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "puffblouse": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "puffer": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "puffervest": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "puffmuffs": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "punkcrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "rabbitears": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "racesash": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"runs"},
  "rage": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "ravenlong": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "rects": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "redcape": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "redscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "ribboncap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "rodeohat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "rosecrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "roundfro": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "roundgold": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "rounds": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "royalcrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "royalrobe": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "runvisor": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"runs"},
  "sad": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sailorcollar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "sailorhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "sailortop": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "samuraihelm": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "santahat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "scallopband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "scarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "scrumcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "sheriffstar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "shieldvisor": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"zones"},
  "sidepony": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "silvermedal": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"runs"},
  "singlet": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "sitehelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "skatehelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "skigoggles": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "skullcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "sleeklong": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sleepmask": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "sleepy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "sleevehoodie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "slouchberet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sly": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "smiley": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "smirk": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "snapback": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "snowpuffer": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "sob": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "softwaves": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "spacebuns": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "spacehelmet": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "spikecrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"zones"},
  "sportcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "sportpolo": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "sportshield": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "stareyes": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"zones"},
  "starglasses": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "starnecklace": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "steampunk": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "stripetee": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sultanturban": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "sunbowhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "surfer": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "sweatband": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "sweater": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "swept": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "swimcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "tealscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "teamjersey": {"status":"core","theme":"club","collection":null,"family":null,"acquisitionType":"runs"},
  "texturedcrop": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "tiara": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "tiedbandana": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "tintgoggles": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "tongueout": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "topbow": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "tophat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "topknot": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "trapperhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "tricorn": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "trophychain": {"status":"core","theme":"club","collection":null,"family":null,"acquisitionType":"runs"},
  "turban": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "twoblock": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "uneasy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "unicornhorn": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "ushanka": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "utilityvest": {"status":"core","theme":"trail","collection":null,"family":null,"acquisitionType":"zones"},
  "varsity": {"status":"vault","theme":"club","collection":null,"family":null,"acquisitionType":"pro"},
  "vikinghelm": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "visor": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"distance"},
  "wayfarer": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "wb001": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sweat shorts","acquisitionType":"starter"},
  "wb002": {"status":"lifestyle","theme":"casual","collection":null,"family":"Gym shorts","acquisitionType":"starter"},
  "wb003": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cuffed shorts","acquisitionType":"starter"},
  "wb004": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb009": {"status":"lifestyle","theme":"casual","collection":null,"family":"Trousers","acquisitionType":"starter"},
  "wb012": {"status":"core","theme":"running","collection":null,"family":"Track shorts","acquisitionType":"starter"},
  "wb013": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pleated skirt","acquisitionType":"starter"},
  "wb014": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb017": {"status":"lifestyle","theme":"casual","collection":null,"family":"Swim shorts","acquisitionType":"starter"},
  "wb018": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb019": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pinstripe trousers","acquisitionType":"starter"},
  "wb021": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb024": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pleated shorts","acquisitionType":"starter"},
  "wb025": {"status":"vault","theme":"running","collection":null,"family":"Running shorts","acquisitionType":"battlepass"},
  "wb026": {"status":"lifestyle","theme":"casual","collection":null,"family":"Denim shorts","acquisitionType":"starter"},
  "wb027": {"status":"core","theme":"trail","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb031": {"status":"lifestyle","theme":"casual","collection":null,"family":"Gingham skirt","acquisitionType":"starter"},
  "wb032": {"status":"lifestyle","theme":"casual","collection":null,"family":"Knee shorts","acquisitionType":"starter"},
  "wb036": {"status":"core","theme":"running","collection":null,"family":"Track shorts","acquisitionType":"starter"},
  "wb043": {"status":"lifestyle","theme":"casual","collection":null,"family":"Drawstring shorts","acquisitionType":"starter"},
  "wb047": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sweat shorts","acquisitionType":"starter"},
  "wb048": {"status":"core","theme":"running","collection":null,"family":"Running shorts","acquisitionType":"starter"},
  "wb050": {"status":"vault","theme":"casual","collection":null,"family":"Denim shorts","acquisitionType":"battlepass"},
  "wb052": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb054": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pinstripe shorts","acquisitionType":"starter"},
  "wb056": {"status":"lifestyle","theme":"casual","collection":null,"family":"Drawstring shorts","acquisitionType":"starter"},
  "wb061": {"status":"lifestyle","theme":"casual","collection":null,"family":"Corduroy shorts","acquisitionType":"starter"},
  "wb062": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb065": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"runs"},
  "wb068": {"status":"lifestyle","theme":"casual","collection":null,"family":"Corduroy shorts","acquisitionType":"starter"},
  "wb071": {"status":"lifestyle","theme":"casual","collection":null,"family":"Plaid shorts","acquisitionType":"starter"},
  "wb072": {"status":"lifestyle","theme":"casual","collection":null,"family":"Compression shorts","acquisitionType":"starter"},
  "wb073": {"status":"lifestyle","theme":"casual","collection":null,"family":"Tennis skirt","acquisitionType":"starter"},
  "wb083": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skort","acquisitionType":"starter"},
  "wb084": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb086": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb092": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo trousers","acquisitionType":"starter"},
  "wb093": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb094": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb097": {"status":"lifestyle","theme":"casual","collection":null,"family":"Plaid shorts","acquisitionType":"starter"},
  "wb102": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cropped jeans","acquisitionType":"starter"},
  "wb103": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb105": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chinos","acquisitionType":"runs"},
  "wb106": {"status":"lifestyle","theme":"casual","collection":null,"family":"Leggings","acquisitionType":"starter"},
  "wb107": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pleated skirt","acquisitionType":"starter"},
  "wb108": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skirt","acquisitionType":"starter"},
  "wb109": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chino shorts","acquisitionType":"starter"},
  "wb110": {"status":"vault","theme":"running","collection":null,"family":"Race shorts","acquisitionType":"battlepass"},
  "wb111": {"status":"core","theme":"running","collection":null,"family":"Cropped joggers","acquisitionType":"starter"},
  "weddingveil": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "weldgoggles": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "wf001": {"status":"core","theme":"running","collection":null,"family":"Trainers","acquisitionType":"starter"},
  "wf002": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skate shoes","acquisitionType":"starter"},
  "wf004": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slip ons","acquisitionType":"starter"},
  "wf005": {"status":"vault","theme":"running","collection":null,"family":"Runners","acquisitionType":"battlepass"},
  "wf006": {"status":"core","theme":"trail","collection":null,"family":"Trail shoes","acquisitionType":"starter"},
  "wf007": {"status":"lifestyle","theme":"casual","collection":null,"family":"High tops","acquisitionType":"starter"},
  "wf008": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf009": {"status":"lifestyle","theme":"casual","collection":null,"family":"Canvas sneakers","acquisitionType":"starter"},
  "wf010": {"status":"vault","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"battlepass"},
  "wf011": {"status":"vault","theme":"running","collection":null,"family":"Runners","acquisitionType":"battlepass"},
  "wf012": {"status":"lifestyle","theme":"casual","collection":null,"family":"Retro sneakers","acquisitionType":"starter"},
  "wf013": {"status":"core","theme":"running","collection":null,"family":"Trainers","acquisitionType":"starter"},
  "wf015": {"status":"core","theme":"running","collection":null,"family":"Knit runners","acquisitionType":"runs"},
  "wf018": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"starter"},
  "wf019": {"status":"core","theme":"running","collection":null,"family":"Tech runners","acquisitionType":"starter"},
  "wf020": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"runs"},
  "wf021": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf022": {"status":"lifestyle","theme":"casual","collection":null,"family":"High tops","acquisitionType":"distance"},
  "wf023": {"status":"core","theme":"trail","collection":null,"family":"Trail runners","acquisitionType":"starter"},
  "wf024": {"status":"lifestyle","theme":"casual","collection":null,"family":"High tops","acquisitionType":"starter"},
  "wf025": {"status":"lifestyle","theme":"casual","collection":null,"family":"Canvas sneakers","acquisitionType":"runs"},
  "wf026": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf027": {"status":"core","theme":"trail","collection":null,"family":"Hiking shoes","acquisitionType":"starter"},
  "wf028": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf029": {"status":"core","theme":"running","collection":null,"family":"Trainers","acquisitionType":"starter"},
  "wf030": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"runs"},
  "wf031": {"status":"lifestyle","theme":"casual","collection":null,"family":"Platform sneakers","acquisitionType":"starter"},
  "wf032": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slides","acquisitionType":"starter"},
  "wf034": {"status":"lifestyle","theme":"casual","collection":null,"family":"Ballet flats","acquisitionType":"starter"},
  "wf036": {"status":"core","theme":"trail","collection":null,"family":"Hiking boots","acquisitionType":"starter"},
  "wf037": {"status":"lifestyle","theme":"casual","collection":null,"family":"Fleece slippers","acquisitionType":"starter"},
  "wf040": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slip ons","acquisitionType":"runs"},
  "wf041": {"status":"lifestyle","theme":"casual","collection":null,"family":"Rain boots","acquisitionType":"starter"},
  "wf043": {"status":"lifestyle","theme":"casual","collection":null,"family":"Mary Janes","acquisitionType":"starter"},
  "wf044": {"status":"vault","theme":"casual","collection":null,"family":"Strap sneakers","acquisitionType":"battlepass"},
  "wf045": {"status":"lifestyle","theme":"casual","collection":null,"family":"Espadrilles","acquisitionType":"runs"},
  "wf046": {"status":"core","theme":"trail","collection":null,"family":"Work boots","acquisitionType":"starter"},
  "wf047": {"status":"lifestyle","theme":"casual","collection":null,"family":"Court sneakers","acquisitionType":"starter"},
  "wf048": {"status":"lifestyle","theme":"casual","collection":null,"family":"Moccasins","acquisitionType":"starter"},
  "wf049": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"starter"},
  "wf050": {"status":"lifestyle","theme":"casual","collection":null,"family":"Clogs","acquisitionType":"runs"},
  "wf051": {"status":"core","theme":"running","collection":null,"family":"Sport sandals","acquisitionType":"starter"},
  "wf052": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chelsea boots","acquisitionType":"starter"},
  "wf053": {"status":"lifestyle","theme":"casual","collection":null,"family":"Duck boots","acquisitionType":"starter"},
  "wf054": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slip ons","acquisitionType":"starter"},
  "wf055": {"status":"lifestyle","theme":"casual","collection":null,"family":"Mary Janes","acquisitionType":"distance"},
  "wf060": {"status":"lifestyle","theme":"casual","collection":null,"family":"Canvas high tops","acquisitionType":"runs"},
  "wf061": {"status":"lifestyle","theme":"casual","collection":null,"family":"Boat shoes","acquisitionType":"starter"},
  "wf063": {"status":"lifestyle","theme":"casual","collection":null,"family":"Loafers","acquisitionType":"starter"},
  "wf064": {"status":"core","theme":"running","collection":null,"family":"Mesh runners","acquisitionType":"starter"},
  "wf070": {"status":"lifestyle","theme":"casual","collection":null,"family":"Strap shoes","acquisitionType":"runs"},
  "wf071": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skate shoes","acquisitionType":"starter"},
  "wf076": {"status":"lifestyle","theme":"casual","collection":null,"family":"Tassel loafers","acquisitionType":"starter"},
  "wf078": {"status":"core","theme":"trail","collection":null,"family":"Work boots","acquisitionType":"starter"},
  "wf079": {"status":"lifestyle","theme":"casual","collection":null,"family":"Fluffy slippers","acquisitionType":"starter"},
  "wf081": {"status":"lifestyle","theme":"casual","collection":null,"family":"Ballet flats","acquisitionType":"starter"},
  "wf083": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chelsea boots","acquisitionType":"starter"},
  "wf084": {"status":"core","theme":"trail","collection":null,"family":"Trail runners","acquisitionType":"starter"},
  "wf085": {"status":"lifestyle","theme":"casual","collection":null,"family":"Strap heels","acquisitionType":"runs"},
  "wf086": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slides","acquisitionType":"starter"},
  "whoa": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "wideband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "windbreaker": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "wink": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "wintscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "witchhat": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "wizardhat": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "wolfears": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "worried": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
};

export default COSMETIC_CURATION;
