// Cosmetics catalog — real layered PNG art (assets/character/*). Hair,
// tops, bottoms, and glasses are COLORABLE: each item has 10 pre-generated
// color variants (see cosmeticsArt.js, generated by the asset pipeline);
// equipped stores a palette INDEX per slot (hairColor, topColor, ...).
// The body/skin is fixed art. Rendering/placement lives in
// components/character/CharacterRig.js.
//
// Unlocks are evaluated client-side against /me/stats (same keys the trophy
// shelf uses) + clan membership. A server-authoritative cosmetics table can
// replace `isUnlocked` later without changing the catalog shape.

import { ART } from './cosmeticsArt';

// ---------------------------------------------------------------------------
// Palettes — hex values are for the studio swatches; the index into these
// arrays selects the matching pre-rendered variant.
// ---------------------------------------------------------------------------

export const HAIR_COLORS = [
  '#26282B', '#4A2F1F', '#7B4B2A', '#C9922B', '#E8D06B',
  '#C6482C', '#9EA3AB', '#E85D9E', '#8B5CF6', '#3B82F6',
];

export const CLOTH_COLORS = [
  '#F4F4F5', '#26272B', '#EF4444', '#F97316', '#EAB308',
  '#22C55E', '#2DD4BF', '#3B82F6', '#8B5CF6', '#EC4899',
];

// ---------------------------------------------------------------------------
// Unlock conditions — `stat` keys come from /me/stats; `clan` needs membership.
// ---------------------------------------------------------------------------

const free = null;
const runs = (n, label) => ({ stat: 'runs_count', value: n, label });
const dist = (km, label) => ({ stat: 'career_distance_m', value: km * 1000, label });
const zones = (n, label) => ({ stat: 'territory_count', value: n, label });
const streak = (n, label) => ({ stat: 'current_streak_weeks', value: n, label });
const clan = (label) => ({ clan: true, label });

// ---------------------------------------------------------------------------
// Slots + items. Colorable items carry `art` (array indexed by palette
// index); faces carry a single `img`. `fit: 'onepiece'` = chest→ankles
// placement (overalls). Rarity drives card styling only: common | rare | epic.
// ---------------------------------------------------------------------------

export const SLOTS = [
  { key: 'face', label: 'Face' },
  { key: 'hair', label: 'Hair', colorKey: 'hairColor', palette: HAIR_COLORS },
  { key: 'glasses', label: 'Glasses', colorKey: 'glassesColor', palette: CLOTH_COLORS },
  { key: 'top', label: 'Tops', colorKey: 'topColor', palette: CLOTH_COLORS },
  { key: 'bottom', label: 'Bottoms', colorKey: 'bottomColor', palette: CLOTH_COLORS },
];

export const BODY_IMG = require('../../assets/character/body/body.png');

export const ITEMS = {
  face: [
    { id: 'smiley', label: 'Smiley', img: require('../../assets/character/face/face2.png'), rarity: 'common', unlock: free },
    { id: 'neutral', label: 'Neutral', img: require('../../assets/character/face/face1.png'), rarity: 'common', unlock: free },
    { id: 'chill', label: 'Chill', img: require('../../assets/character/face/face7.png'), rarity: 'common', unlock: free },
    { id: 'laugh', label: 'Laugh', img: require('../../assets/character/face/face3.png'), rarity: 'common', unlock: free },
    { id: 'grump', label: 'Grump', img: require('../../assets/character/face/face6.png'), rarity: 'common', unlock: runs(1, 'Finish your first run') },
    { id: 'wink', label: 'Wink', img: require('../../assets/character/face/face4.png'), rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'whoa', label: 'Whoa', img: require('../../assets/character/face/face5.png'), rarity: 'rare', unlock: zones(1, 'Claim your first zone') },
    { id: 'sleepy', label: 'Sleepy', img: require('../../assets/character/face/face9.png'), rarity: 'rare', unlock: streak(2, 'Hold a 2-week streak') },
    { id: 'blush', label: 'Blush', img: require('../../assets/character/face/face8.png'), rarity: 'epic', unlock: dist(50, 'Run 50 km total') },
  ],
  hair: [
    { id: 'none', label: 'Bald', art: null, rarity: 'common', unlock: free },
    { id: 'curtains', label: 'Curtains', art: ART.hairM1, rarity: 'common', unlock: free },
    { id: 'middlepart', label: 'Middle part', art: ART.hairM4, rarity: 'common', unlock: free },
    { id: 'swept', label: 'Swept', art: ART.hairM3, layout: { top: -0.04 }, rarity: 'common', unlock: free },
    { id: 'curls', label: 'Curls', art: ART.hairM5, rarity: 'common', unlock: free },
    { id: 'pixie', label: 'Pixie', art: ART.hairW10, layout: { top: -0.045 }, rarity: 'common', unlock: free },
    { id: 'bluntbob', label: 'Blunt bob', art: ART.hairW4, rarity: 'common', unlock: free },
    { id: 'fringebob', label: 'Fringe bob', art: ART.hairW2, rarity: 'common', unlock: free },
    { id: 'sleeklong', label: 'Sleek long', art: ART.hairW5, rarity: 'common', unlock: free },
    { id: 'messy', label: 'Messy', art: ART.hairM10, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'longwaves', label: 'Long waves', art: ART.hairW1, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'flow', label: 'Flow', art: ART.hairM6, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'ravenlong', label: 'Straight long', art: ART.hairW6, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'bangs', label: 'Bangs', art: ART.hairW11, rarity: 'common', unlock: dist(10, 'Run 10 km total') },
    { id: 'roundfro', label: 'Round fro', art: ART.hairM8, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'softwaves', label: 'Soft waves', art: ART.hairW12, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'topknot', label: 'Top knot', art: ART.hairM2, layout: { w: 0.88, top: -0.15 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'sidepony', label: 'Side pony', art: ART.hairW9, layout: { top: -0.055 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'fringebun', label: 'Fringe bun', art: ART.hairM7, layout: { w: 0.92, top: -0.145 }, rarity: 'rare', unlock: zones(3, 'Hold 3 zones') },
    { id: 'highpony', label: 'High pony', art: ART.hairW7, layout: { w: 0.98, top: -0.155 }, rarity: 'rare', unlock: streak(2, 'Hold a 2-week streak') },
    { id: 'lowbun', label: 'Low bun', art: ART.hairW13, layout: { top: -0.055 }, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'surfer', label: 'Surfer', art: ART.hairM9, rarity: 'epic', unlock: dist(100, 'Run 100 km total') },
    { id: 'curlylong', label: 'Curly long', art: ART.hairW3, layout: { top: -0.04 }, rarity: 'epic', unlock: dist(100, 'Run 100 km total') },
    { id: 'spacebuns', label: 'Space buns', art: ART.hairW8, layout: { w: 1.0, top: -0.10 }, rarity: 'epic', unlock: zones(10, 'Hold 10 zones') },
  ],
  glasses: [
    { id: 'none', label: 'None', art: null, rarity: 'common', unlock: free },
    { id: 'rounds', label: 'Rounds', art: ART.specs1, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'rects', label: 'Rects', art: ART.specs2, rarity: 'rare', unlock: dist(10, 'Run 10 km total') },
  ],
  top: [
    { id: 'tee', label: 'Tee', art: ART.top1, rarity: 'common', unlock: free },
    { id: 'crewtee', label: 'Crew tee', art: ART.top2, rarity: 'common', unlock: free },
    { id: 'pockettee', label: 'Pocket tee', art: ART.top8, rarity: 'common', unlock: free },
    { id: 'stripetee', label: 'Stripe tee', art: ART.top5, layout: { top: 0.312 }, rarity: 'common', unlock: free },
    { id: 'hoodie', label: 'Hoodie', art: ART.top7, layout: { top: 0.292, w: 1.0 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'daisydress', label: 'Daisy dress', art: ART.top4, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'overshirt', label: 'Overshirt', art: ART.top6, layout: { top: 0.312, w: 0.90 }, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'sweater', label: 'Sweater', art: ART.top11, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'kangahoodie', label: 'Kanga hoodie', art: ART.top9, layout: { top: 0.30 }, rarity: 'rare', unlock: streak(2, 'Hold a 2-week streak') },
    { id: 'slouchhoodie', label: 'Slouch hoodie', art: ART.top10, layout: { top: 0.30 }, rarity: 'rare', unlock: clan('Join a club') },
    { id: 'overalls', label: 'Overalls', art: ART.onepiece1, fit: 'onepiece', layout: { w: 0.68, top: 0.375 }, rarity: 'epic', unlock: zones(5, 'Hold 5 zones') },
    { id: 'jacket', label: 'Jacket', art: ART.top3, rarity: 'epic', unlock: dist(100, 'Run 100 km total') },
  ],
  bottom: [
    { id: 'none', label: 'None', art: null, rarity: 'common', unlock: free },
    { id: 'pants', label: 'Pants', art: ART.bottom1, rarity: 'common', unlock: free },
    { id: 'shorts', label: 'Shorts', art: ART.bottom3, rarity: 'common', unlock: free },
    { id: 'skirt', label: 'Skirt', art: ART.bottom2, layout: { w: 0.80, top: 0.545 }, rarity: 'common', unlock: free },
    { id: 'cargos', label: 'Cargos', art: ART.bottom4, layout: { w: 0.66 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
  ],
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function getItem(slot, id) {
  const list = ITEMS[slot] || [];
  return list.find((i) => i.id === id) || list[0];
}

const COLOR_KEY = { hair: 'hairColor', glasses: 'glassesColor', top: 'topColor', bottom: 'bottomColor' };

// The image for an item in the loadout's chosen color (faces are fixed art).
export function itemImage(slot, item, equipped) {
  if (item.img) return item.img;
  if (!item.art) return null;
  const idx = equipped?.[COLOR_KEY[slot]] ?? 0;
  return item.art[Math.max(0, Math.min(item.art.length - 1, idx))];
}

// Everything is unlocked — all cosmetics are freely available. (Unlock
// metadata is kept on the items in case gating returns later.)
export function isUnlocked() {
  return true;
}

export function unlockLabel(item) {
  return item.unlock?.label || null;
}

export const DEFAULT_EQUIPPED = {
  face: 'smiley',
  hair: 'curtains',
  hairColor: 0,        // black
  glasses: 'none',
  glassesColor: 1,
  top: 'tee',
  topColor: 7,         // blue
  bottom: 'pants',
  bottomColor: 1,      // black
};

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
const pickIdx = (arr) => Math.floor(Math.random() * arr.length);

// Random loadout from the user's UNLOCKED pool only.
export function randomEquipped(ctx) {
  const pool = (slot) => (ITEMS[slot] || []).filter((i) => isUnlocked(i, ctx));
  return {
    face: pick(pool('face')).id,
    hair: pick(pool('hair')).id,
    hairColor: pickIdx(HAIR_COLORS),
    glasses: pick(pool('glasses')).id,
    glassesColor: pickIdx(CLOTH_COLORS),
    top: pick(pool('top')).id,
    topColor: pickIdx(CLOTH_COLORS),
    bottom: pick(pool('bottom')).id,
    bottomColor: pickIdx(CLOTH_COLORS),
  };
}
