// Cosmetics catalog — real layered PNG art (assets/character/*). Hair,
// tops, bottoms, and glasses are COLORABLE: each item has 10 pre-generated
// color variants (see cosmeticsArt.js, generated by the asset pipeline);
// equipped stores a palette INDEX per slot (hairColor, topColor, ...).
// The body/skin is fixed art. Rendering/placement lives in
// components/character/CharacterRig.js.
//
// Unlocks combine client-side stat/clan rules with server grants from pass
// claims, lootboxes, and the coin shop.

import { ART } from './cosmeticsArt';
import { OUTFIT_TOPS, OUTFIT_BOTTOMS, OUTFIT_SUITS, FOOTWEAR } from './outfitItems';
import { HAIR_SHEETS } from './hairSheetItems';
import {
  CURATED_TOPS, CURATED_BOTTOMS, CURATED_FOOTWEAR, CURATED_HEADWEAR,
  CURATED_GLASSES, CURATED_ACCESSORIES, CURATED_EXTRAS,
} from './curatedCosmetics';
import { isHiddenItem } from './hiddenCosmetics';

// ---------------------------------------------------------------------------
// Palettes — hex values are for the studio swatches; the index into these
// arrays selects the matching pre-rendered variant.
// ---------------------------------------------------------------------------

export const HAIR_COLORS = [
  '#26282B', '#4A2F1F', '#7B4B2A', '#C9922B', '#E8D06B',
  '#C6482C', '#9EA3AB', '#E85D9E', '#8B5CF6', '#3B82F6',
];

export const CLOTH_COLORS = [
  '#F4F4F5', '#26272B', '#EF4444', '#F97316', '#EAB308',
  '#22C55E', '#2DD4BF', '#3B82F6', '#8B5CF6', '#EC4899',
];

// ---------------------------------------------------------------------------
// Unlock conditions — `stat` keys come from /me/stats; pass markers require a
// matching server grant.
// ---------------------------------------------------------------------------

const free = null;
const runs = (n, label) => ({ stat: 'runs_count', value: n, label });
const dist = (km, label) => ({ stat: 'career_distance_m', value: km * 1000, label });
const zones = (n, label) => ({ stat: 'territory_count', value: n, label });
const streak = (n, label) => ({ stat: 'current_streak_weeks', value: n, label });
const level = (n, label) => ({ stat: 'level', value: n, label: label || `Reach level ${n}` });
const passOnly = { pass: true, label: 'Free pass reward' };
// PASER PRO exclusives — no stat route at all. The only way in is a pass tier
// granting a server-side unlock (see PREMIUM_ITEMS in backend/progression.py),
// which isUnlocked honours via ctx.unlocks.
const premiumOnly = { premium: true, label: 'PASER PRO reward' };

// ---------------------------------------------------------------------------
// Slots + items. Colorable items carry `art` (array indexed by palette
// index); faces carry a single `img`. `fit: 'onepiece'` = chest→ankles
// placement (overalls). Rarity drives card styling only: common | rare | epic.
// ---------------------------------------------------------------------------

export const SLOTS = [
  { key: 'face', label: 'Face' },
  { key: 'hair', label: 'Hair', colorKey: 'hairColor', palette: HAIR_COLORS },
  { key: 'headwear', label: 'Hats', colorKey: 'headwearColor', palette: CLOTH_COLORS },
  { key: 'glasses', label: 'Glasses', colorKey: 'glassesColor', palette: CLOTH_COLORS },
  { key: 'top', label: 'Tops', colorKey: 'topColor', palette: CLOTH_COLORS },
  { key: 'bottom', label: 'Bottoms', colorKey: 'bottomColor', palette: CLOTH_COLORS },
  // Shoes were baked into the leg art before; they are their own slot now, cut
  // off the full-outfit renders at the ankle. No palette — the art is fixed.
  { key: 'footwear', label: 'Shoes' },
  { key: 'accessory', label: 'Extras' },
];

export const BODY_IMG = require('../../assets/character/body/body.png');
export const HEAD_IMG = require('../../assets/character/body/head.png');

export const ITEMS = {
  face: [
    // Every face shares one placement, measured off the reference head:
    //   width = 0.59 x head width (outer brow to outer brow)
    //   top   = 0.34 x head height (top of the eyebrows)
    // That lives in CharacterRig's LAYOUT.face as a `top` anchor rather
    // than `cy`, so the brows hold their line while a long mouth, a tear
    // or a tongue is free to hang lower. No per-item overrides — an item
    // that drifts off the shared anchor also drifts away from the glasses.
    { id: 'smiley', label: 'Smiley', img: require('../../assets/character/face/faceN9.png'), layout: { top: 0.1348, dx: -0.0033 }, rarity: 'common', unlock: free },
    { id: 'chill', label: 'Chill', img: require('../../assets/character/face/faceN1.png'), layout: { w: 0.3951, top: 0.1335, dx: 0 }, rarity: 'common', unlock: free },
    { id: 'grump', label: 'Grump', img: require('../../assets/character/face/faceN5.png'), layout: { w: 0.4102, top: 0.1374, dx: -0.005 }, rarity: 'common', unlock: passOnly },
    { id: 'determined', label: 'Game face', img: require('../../assets/character/face/faceN3.png'), layout: { top: 0.1374 }, rarity: 'common', unlock: passOnly },
    { id: 'exhausted', label: 'Cooked', img: require('../../assets/character/face/faceN12.png'), layout: { w: 0.3844, top: 0.1377 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'worried', label: 'Worried', img: require('../../assets/character/face/faceN2.png'), layout: { w: 0.372, top: 0.138, dx: 0.005 }, rarity: 'common', unlock: free },
    { id: 'uneasy', label: 'Uneasy', img: require('../../assets/character/face/faceN4.png'), layout: { w: 0.4003, top: 0.1413, dx: 0 }, rarity: 'common', unlock: free },
    { id: 'glum', label: 'Glum', img: require('../../assets/character/face/faceN8.png'), layout: { w: 0.3781, top: 0.1412, dx: 0.0017 }, rarity: 'common', unlock: free },
    { id: 'smirk', label: 'Smirk', img: require('../../assets/character/face/faceN6.png'), layout: { w: 0.3926, top: 0.1425, dx: -0.005 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'beam', label: 'Beaming', img: require('../../assets/character/face/faceN7.png'), layout: { w: 0.3702, top: 0.1437, dx: -0.0017 }, rarity: 'common', unlock: runs(8, 'Finish 8 runs') },
    { id: 'angry', label: 'Angry', img: require('../../assets/character/face/faceN10.png'), layout: { w: 0.3635, top: 0.1451, dx: -0.0017 }, rarity: 'common', unlock: runs(10, 'Finish 10 runs') },
  ],
  hair: [
    { id: 'none', label: 'Bald', art: null, rarity: 'common', unlock: free },
    { id: 'curtains', label: 'Curtains', art: ART.hairM1, layout: { w: 0.8650, top: -0.0174, dx: 0.0034 }, rarity: 'common', unlock: free },
    { id: 'swept', label: 'Swept', art: ART.hairM3, layout: { w: 0.8385, top: -0.0352, dx: 0.0052 }, rarity: 'common', unlock: free },
    { id: 'curls', label: 'Curls', art: ART.hairM5, layout: { w: 0.8484, top: -0.0311, dx: 0.0023 }, bulky: true, rarity: 'common', unlock: free },
    { id: 'pixie', label: 'Pixie', art: ART.hairW10, layout: { w: 0.8319, top: -0.0413, dx: 0.0064 }, rarity: 'common', unlock: free },
    { id: 'bluntbob', label: 'Blunt bob', art: ART.hairW4, layout: { w: 0.8897, top: -0.0275, dx: 0.0089 }, rarity: 'common', unlock: free },
    { id: 'fringebob', label: 'Fringe bob', art: ART.hairW2, layout: { w: 0.8749, top: -0.0263, dx: 0.0090 }, rarity: 'common', unlock: free },
    { id: 'sleeklong', label: 'Sleek long', art: ART.hairW5, layout: { w: 0.9590, top: -0.0368, dx: 0.0010 }, rarity: 'common', unlock: free },
    { id: 'messy', label: 'Messy', art: ART.hairM10, layout: { w: 0.8864, top: -0.0393, dx: -0.0009 }, rarity: 'common', unlock: passOnly },
    { id: 'longwaves', label: 'Long waves', art: ART.hairW1, layout: { w: 0.9541, top: -0.0374, dx: 0.0005 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'flow', label: 'Flow', art: ART.hairM6, layout: { w: 0.9260, top: -0.0302, dx: 0.0030 }, rarity: 'common', unlock: passOnly },
    { id: 'ravenlong', label: 'Straight long', art: ART.hairW6, layout: { w: 0.9293, top: -0.0258 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'bangs', label: 'Bangs', art: ART.hairW11, layout: { w: 0.8517, top: -0.0350, dx: -0.0023 }, rarity: 'common', unlock: dist(10, 'Run 10 km total') },
    { id: 'roundfro', label: 'Round fro', art: ART.hairM8, layout: { w: 0.9508, top: -0.0533, dx: -0.0001 }, bulky: true, rarity: 'rare', unlock: passOnly },
    { id: 'softwaves', label: 'Soft waves', art: ART.hairW12, layout: { w: 1.0069, top: -0.0320, dx: 0.0037 }, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'topknot', label: 'Top knot', art: ART.hairM2, layout: { w: 0.7709, top: -0.0886, dx: 0.0001 }, bulky: true, rarity: 'rare', unlock: passOnly },
    { id: 'sidepony', label: 'Side pony', art: ART.hairW9, layout: { w: 0.8831, top: -0.0563, dx: 0.0487 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'fringebun', label: 'Fringe bun', art: ART.hairM7, layout: { w: 0.8369, top: -0.0776, dx: -0.0035 }, bulky: true, rarity: 'rare', unlock: zones(3, 'Hold 3 zones') },
    { id: 'highpony', label: 'High pony', art: ART.hairW7, layout: { w: 0.8650, top: -0.0876, dx: 0.0570 }, bulky: true, rarity: 'rare', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'surfer', label: 'Surfer', art: ART.hairM9, layout: { w: 0.9376, top: -0.0230, dx: 0.0135 }, rarity: 'epic', unlock: passOnly },
    { id: 'spacebuns', label: 'Space buns', art: ART.hairW8, layout: { w: 0.9442, top: -0.0446, dx: 0.0062 }, bulky: true, rarity: 'epic', unlock: zones(10, 'Hold 10 zones') },
    { id: 'hijab', label: 'Sports hijab', art: ART.hairW14, layout: { w: 0.8138, top: -0.0241, dx: 0.0019 }, rarity: 'common', unlock: free },
    { id: 'curtainlong', label: 'Curtain long', art: ART.hairW17, layout: { w: 0.8732, top: -0.0253, dx: -0.0013 }, rarity: 'common', unlock: free },
    { id: 'twoblock', label: 'Two block', art: ART.hairM11, layout: { w: 0.9359, top: -0.0365, dx: 0.0071 }, rarity: 'common', unlock: free },
    { id: 'buzz', label: 'Buzz cut', art: ART.hairM12, layout: { w: 0.7606, top: -0.0012, dx: -0.003 }, rarity: 'common', unlock: free },
    { id: 'braids', label: 'Braided pigtails', art: ART.hairW15, layout: { w: 0.7962, top: -0.0449, dx: 0.0087 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'bunstrands', label: 'Soft bun', art: ART.hairW16, layout: { w: 0.7808, top: -0.0747, dx: 0.0036 }, bulky: true, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'comma', label: 'Comma fringe', art: ART.hairM13, layout: { w: 0.9244, top: -0.0451, dx: 0.0032 }, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'texturedcrop', label: 'Textured crop', art: ART.hairM14, layout: { w: 0.8815, top: -0.0390, dx: 0.0112 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    // --- wave 3 (2026-07-31) ---
    { id: 'bigafro', label: 'Big afro', img: require('../../assets/character/hair/hairX24.png'), layout: { w: 1.1469, top: -0.075, dx: 0.001 }, bulky: true, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'highbun', label: 'High bun', img: require('../../assets/character/hair/hairX25.png'), layout: { w: 1.0185, top: -0.1295, dx: -0.1073 }, bulky: true, rarity: 'rare', unlock: streak(2, 'Hold a 2 week streak') },
  ],
  headwear: [
    { id: 'none', label: 'None', art: null, rarity: 'common', unlock: free },
    { id: 'bandana', label: 'Bandana', img: require('../../assets/character/headwear/hat6.png'), layout: { w: 0.6567, top: -0.0492, dx: 0.0117 }, rarity: 'common', unlock: passOnly },
    { id: 'snapback', label: 'Backwards cap', img: require('../../assets/character/headwear/hat2.png'), hidesBulky: true, layout: { w: 0.69, top: -0.0417, dx: -0.0033 }, rarity: 'common', unlock: zones(3, 'Hold 3 zones') },
    // `top` was 0.0327, which put the brim ON THE EYES. hat11's ink runs to
    // the bottom of its canvas, so at that height it reached body y 127 while
    // the face's eyes sit at 108-120 — every runner wearing the visor was
    // blindfolded by it, and on the shop attendant it hid the blinks and three
    // of the four expressions the Pit Stop scene is built around. -0.010 lands
    // the ink at y 99.7, the same brow line the sweatband sits on.
    { id: 'skatehelmet', label: 'Skate helmet', img: require('../../assets/character/headwear/hat9.png'), layout: { w: 0.73, top: -0.0467, dx: 0.005 }, hideHair: true, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'hardhat', label: 'Hard hat', img: require('../../assets/character/headwear/hat12.png'), layout: { w: 0.7067, top: -0.0679, dx: -0.005 }, hidesBulky: true, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'bikehelmet', label: 'Bike helmet', img: require('../../assets/character/headwear/hat8.png'), layout: { w: 0.7633, top: -0.0669, dx: -0.0033 }, hideHair: true, rarity: 'epic', unlock: passOnly },
    { id: 'laurel', label: 'Laurel wreath', img: require('../../assets/character/headwear/hat13.png'), layout: { w: 0.8566, top: -0.0218, dx: -0.005 }, rarity: 'epic', unlock: premiumOnly },
    { id: 'flamecrown', label: 'Flame crown', img: require('../../assets/character/headwear/hat14.png'), layout: { w: 0.8467, top: -0.0661, dx: 0.005 }, rarity: 'legendary', unlock: premiumOnly },
    { id: 'wolfears', label: 'Wolf ears', img: require('../../assets/character/headwear/hat16.png'), layout: { w: 0.7634, top: -0.075, dx: -0.0017 }, rarity: 'epic', unlock: premiumOnly },
    { id: 'frogbeanie', label: 'Frog beanie', img: require('../../assets/character/headwear/hat18.png'), hideHair: true, layout: { w: 0.75, top: -0.0842, dx: 0.0067 }, rarity: 'rare', unlock: runs(3, 'Finish 3 runs') },
    { id: 'wizardhat', label: 'Wizard hat', img: require('../../assets/character/headwear/hat19.png'), layout: { w: 0.86, top: -0.1394, dx: 0 }, rarity: 'epic', unlock: level(18) },
    { id: 'antlers', label: 'Antlers', img: require('../../assets/character/headwear/hat20.png'), layout: { w: 1.0034, top: -0.1235, dx: -0.005 }, rarity: 'rare', unlock: zones(3, 'Hold 3 zones') },
    { id: 'aviatorcap', label: 'Aviator cap', img: require('../../assets/character/headwear/hat21.png'), hideHair: true, layout: { w: 0.81, top: -0.0429 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'chefhat', label: 'Chef hat', img: require('../../assets/character/headwear/hat22.png'), layout: { w: 0.8933, top: -0.1817, dx: -0.0083 }, hideHair: true, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'piratehat', label: 'Pirate hat', img: require('../../assets/character/headwear/hat24.png'), layout: { w: 0.8834, top: -0.07, dx: -0.01 }, hidesBulky: true, rarity: 'epic', unlock: level(22) },
    { id: 'headdress', label: 'Feather crown', img: require('../../assets/character/headwear/hat25.png'), layout: { w: 0.8166, top: -0.0787, dx: 0.0033 }, rarity: 'epic', unlock: level(28) },
    { id: 'gradcap', label: 'Grad cap', img: require('../../assets/character/headwear/hat26.png'), layout: { w: 1.01, top: -0.0719, dx: -0.02 }, hidesBulky: true, rarity: 'rare', unlock: runs(25, 'Finish 25 runs') },
    { id: 'bowler', label: 'Bowler', img: require('../../assets/character/headwear/hat27.png'), hidesBulky: true, layout: { w: 0.97, top: -0.1152, dx: 0.0033 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'tiara', label: 'Tiara', img: require('../../assets/character/headwear/hat29.png'), layout: { w: 0.6967, top: -0.0453, dx: 0.0016 }, rarity: 'epic', unlock: passOnly },
    { id: 'turban', label: 'Turban', img: require('../../assets/character/headwear/hat30.png'), hideHair: true, layout: { top: -0.0946, dx: -0.0033 }, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'catears', label: 'Cat ears', img: require('../../assets/character/headwear/hat31.png'), layout: { w: 0.7467, top: -0.0527 }, rarity: 'common', unlock: passOnly },
    { id: 'pinkbow', label: 'Bow', img: require('../../assets/character/headwear/hat32.png'), layout: { w: 0.5033, top: -0.0214, dx: 0.165 }, rarity: 'common', unlock: free },
    { id: 'flowercrown', label: 'Flower crown', img: require('../../assets/character/headwear/hat33.png'), layout: { w: 0.8067, top: -0.0428, dx: 0.0067 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    // --- wave 3 (2026-07-31) ---
    { id: 'catbeanie', label: 'Cat beanie', img: require('../../assets/character/headwear/hat35.png'), hideHair: true, layout: { top: -0.0829, dx: 0.0033 }, rarity: 'rare', unlock: runs(5, 'Finish 5 runs') },
    { id: 'boater', label: 'Boater', img: require('../../assets/character/headwear/hat36.png'), hidesBulky: true, layout: { w: 1.0367, top: -0.0765, dx: 0.0066 }, rarity: 'common', unlock: dist(10, 'Run 10 km total') },
    { id: 'jockeycap', label: 'Jockey cap', img: require('../../assets/character/headwear/hat37.png'), hidesBulky: true, layout: { w: 1.02, top: -0.0662, dx: 0.0083 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'beret', label: 'Beret', img: require('../../assets/character/headwear/hat38.png'), layout: { w: 0.89, top: -0.0626, dx: -0.015 }, hidesBulky: true, rarity: 'common', unlock: free },
    { id: 'newsboy', label: 'Newsboy cap', img: require('../../assets/character/headwear/hat39.png'), hidesBulky: true, layout: { w: 0.7867, top: -0.03, dx: -0.005 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'flatcap', label: 'Flat cap', img: require('../../assets/character/headwear/hat40.png'), hidesBulky: true, layout: { w: 0.77, top: -0.0313, dx: -0.0034 }, rarity: 'common', unlock: runs(8, 'Finish 8 runs') },
    { id: 'captaincap', label: 'Captain cap', img: require('../../assets/character/headwear/hat41.png'), hidesBulky: true, layout: { w: 0.8166, top: -0.0274, dx: 0.0033 }, rarity: 'rare', unlock: zones(3, 'Hold 3 zones') },
    { id: 'sailorhat', label: 'Sailor hat', img: require('../../assets/character/headwear/hat42.png'), hidesBulky: true, layout: { top: -0.0596, dx: 0.03 }, rarity: 'common', unlock: dist(15, 'Run 15 km total') },
    { id: 'nursecap', label: 'Nurse cap', img: require('../../assets/character/headwear/hat43.png'), layout: { w: 0.78, top: -0.0511, dx: 0.0033 }, rarity: 'common', unlock: runs(10, 'Finish 10 runs') },
    { id: 'kabuto', label: 'Kabuto', img: require('../../assets/character/headwear/hat45.png'), layout: { w: 1.09, top: -0.1351, dx: -0.0017 }, hidesBulky: true, rarity: 'epic', unlock: premiumOnly },
    { id: 'sultanturban', label: 'Jewel turban', img: require('../../assets/character/headwear/hat46.png'), layout: { w: 0.83, top: -0.1146, dx: 0.0067 }, hidesBulky: true, rarity: 'epic', unlock: level(26) },
    { id: 'ushanka', label: 'Ushanka', img: require('../../assets/character/headwear/hat47.png'), hideHair: true, layout: { w: 0.9, top: -0.0765, dx: 0.0083 }, rarity: 'rare', unlock: dist(50, 'Run 50 km total') },
    { id: 'bunnyears', label: 'Bunny ears', img: require('../../assets/character/headwear/hat48.png'), layout: { w: 0.7267, top: -0.1287, dx: 0.02 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'devilhorns', label: 'Devil horns', img: require('../../assets/character/headwear/hat50.png'), layout: { w: 0.77, top: -0.0732, dx: -0.0083 }, rarity: 'rare', unlock: level(10) },
    { id: 'heartbopper', label: 'Heart boppers', img: require('../../assets/character/headwear/hat51.png'), layout: { w: 0.8, top: -0.1048, dx: 0.0167 }, rarity: 'common', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'cherrybopper', label: 'Cherry boppers', img: require('../../assets/character/headwear/hat52.png'), layout: { w: 0.74, top: -0.0251, dx: 0.0133 }, rarity: 'common', unlock: runs(8, 'Finish 8 runs') },
    { id: 'spikecrown', label: 'Spike band', img: require('../../assets/character/headwear/hat53.png'), layout: { w: 0.75, top: -0.0447, dx: 0.0083 }, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'punkcrown', label: 'Punk crown', img: require('../../assets/character/headwear/hat54.png'), layout: { w: 0.74, top: -0.0613, dx: 0.0133 }, rarity: 'epic', unlock: premiumOnly },
    { id: 'royalcrown', label: 'Royal crown', img: require('../../assets/character/headwear/hat55.png'), layout: { w: 0.6833, top: -0.1232, dx: -0.0083 }, rarity: 'legendary', unlock: passOnly },
    { id: 'bowberet', label: 'Bow beret', img: require('../../assets/character/headwear/hat56.png'), layout: { w: 0.8, top: -0.055 }, hidesBulky: true, rarity: 'common', unlock: runs(10, 'Finish 10 runs') },
    { id: 'bowcap', label: 'Bow cap', img: require('../../assets/character/headwear/hat57.png'), hidesBulky: true, layout: { top: -0.0416, dx: -0.01 }, rarity: 'common', unlock: dist(10, 'Run 10 km total') },
    { id: 'maidband', label: 'Maid band', img: require('../../assets/character/headwear/hat58.png'), layout: { w: 0.44, top: -0.0308, dx: 0.19 }, rarity: 'common', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'daisyband', label: 'Daisy band', img: require('../../assets/character/headwear/hat59.png'), layout: { w: 0.76, top: 0.01 }, rarity: 'common', unlock: free },
    { id: 'angelheart', label: 'Angel heart', img: require('../../assets/character/headwear/hat63.png'), layout: { w: 0.4733, top: -0.0242, dx: 0.19 }, rarity: 'epic', unlock: level(16) },
    { id: 'flowerclip', label: 'Flower clip', img: require('../../assets/character/headwear/hat64.png'), layout: { w: 0.32, top: 0.0045, dx: -0.2067 }, rarity: 'common', unlock: free },
    // --- wave 4 (2026-08-03) --- line art drawn in the body's own style,
    // lifted off the heads it was worn on and fitted by measurement
    // (scripts/cut-headwear-4.py + install-headwear-4.py). Layouts are
    // solved, not tuned: do not hand-edit them, re-run the installer.
    { id: 'headphones', label: 'Headphones', img: require('../../assets/character/headwear/hat72.png'), layout: { w: 0.8819, top: -0.0009 }, hidesBulky: true, rarity: 'rare', unlock: runs(8, 'Finish 8 runs') },
    { id: 'witchhat', label: 'Witch hat', img: require('../../assets/character/headwear/hat74.png'), layout: { w: 0.9279, top: -0.1769 }, hidesBulky: true, rarity: 'epic', unlock: level(16) },
    { id: 'bowband', label: 'Bow band', img: require('../../assets/character/headwear/hat75.png'), layout: { w: 0.7948, top: -0.026 }, rarity: 'common', unlock: free },
    { id: 'puffmuffs', label: 'Puff earmuffs', img: require('../../assets/character/headwear/hat77.png'), layout: { w: 0.926, top: -0.0092 }, rarity: 'common', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'wideband', label: 'Wide band', img: require('../../assets/character/headwear/hat81.png'), layout: { w: 0.6648, top: 0.0021 }, rarity: 'common', unlock: runs(1, 'Finish your first run') },
    { id: 'tiedbandana', label: 'Tied bandana', img: require('../../assets/character/headwear/hat82.png'), layout: { w: 0.8728, top: -0.0308, dx: 0.0805 }, hideHair: true, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'tophat', label: 'Top hat', img: require('../../assets/character/headwear/hat85.png'), layout: { w: 0.8541, top: -0.1005, dx: -0.0067 }, hidesBulky: true, rarity: 'epic', unlock: level(20) },
    { id: 'cheftoque', label: 'Chef toque', img: require('../../assets/character/headwear/hat88.png'), layout: { w: 0.9054, top: -0.1403, dx: 0.01 }, hideHair: true, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'kittyears', label: 'Kitty ears', img: require('../../assets/character/headwear/hat90.png'), layout: { w: 0.6874, top: -0.0358 }, rarity: 'common', unlock: free },
    { id: 'rabbitears', label: 'Rabbit ears', img: require('../../assets/character/headwear/hat92.png'), layout: { w: 0.7264, top: -0.1213 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'tricorn', label: 'Tricorn', img: require('../../assets/character/headwear/hat93.png'), layout: { w: 1.0238, top: -0.0431 }, hidesBulky: true, rarity: 'epic', unlock: level(18) },
    { id: 'firehelmet', label: 'Fire helmet', img: require('../../assets/character/headwear/hat95.png'), layout: { w: 0.9058, top: -0.0834 }, hidesBulky: true, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'trapperhat', label: 'Trapper hat', img: require('../../assets/character/headwear/hat97.png'), layout: { w: 0.8677, top: -0.051 }, hideHair: true, rarity: 'rare', unlock: dist(50, 'Run 50 km total') },
    { id: 'unicornhorn', label: 'Unicorn horn', img: require('../../assets/character/headwear/hat98.png'), layout: { w: 0.7247, top: -0.1197 }, rarity: 'epic', unlock: level(14) },
    { id: 'loveboppers', label: 'Love boppers', img: require('../../assets/character/headwear/hat101.png'), layout: { w: 0.8856, top: -0.1423, dx: 0.0067 }, rarity: 'common', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'scrumcap', label: 'Scrum cap', img: require('../../assets/character/headwear/hat105.png'), layout: { w: 0.7754, top: -0.042, dx: -0.0033 }, hideHair: true, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
    { id: 'sunbowhat', label: 'Sun hat', img: require('../../assets/character/headwear/hat106.png'), layout: { w: 1.1444, top: -0.0481, dx: -0.0085 }, hidesBulky: true, rarity: 'common', unlock: dist(10, 'Run 10 km total') },
    { id: 'santahat', label: 'Santa hat', img: require('../../assets/character/headwear/hat107.png'), layout: { w: 0.8981, top: -0.0658, dx: 0.0857 }, hideHair: true, rarity: 'rare', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'rodeohat', label: 'Rodeo hat', img: require('../../assets/character/headwear/hat109.png'), layout: { w: 0.9966, top: -0.0712, dx: 0.0017 }, hidesBulky: true, rarity: 'rare', unlock: dist(50, 'Run 50 km total') },
    { id: 'headwrap', label: 'Head wrap', img: require('../../assets/character/headwear/hat110.png'), layout: { w: 0.7092, top: -0.0427 }, hideHair: true, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'vikinghelm', label: 'Viking helm', img: require('../../assets/character/headwear/hat111.png'), layout: { w: 0.871, top: -0.0467 }, hidesBulky: true, rarity: 'epic', unlock: level(22) },
    { id: 'mobcap', label: 'Mob cap', img: require('../../assets/character/headwear/hat112.png'), layout: { w: 0.7791, top: -0.0514, dx: -0.0015 }, hideHair: true, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'headscarf', label: 'Head scarf', img: require('../../assets/character/headwear/hat113.png'), layout: { w: 0.7829, top: -0.0076 }, hideHair: true, rarity: 'common', unlock: free },
    { id: 'bowwrap', label: 'Bow wrap', img: require('../../assets/character/headwear/hat115.png'), layout: { w: 0.7341, top: -0.0248 }, hidesBulky: true, rarity: 'common', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'minerhelmet', label: 'Miner helmet', img: require('../../assets/character/headwear/hat116.png'), layout: { w: 0.8275, top: -0.0498, dx: 0.0133 }, hidesBulky: true, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'fez', label: 'Fez', img: require('../../assets/character/headwear/hat117.png'), layout: { w: 0.6867, top: -0.0822, dx: 0.0342 }, hidesBulky: true, rarity: 'rare', unlock: level(12) },
    { id: 'rosecrown', label: 'Rose crown', img: require('../../assets/character/headwear/hat121.png'), layout: { w: 0.8133, top: -0.0109, dx: 0.0267 }, rarity: 'common', unlock: free },
    { id: 'scallopband', label: 'Scallop band', img: require('../../assets/character/headwear/hat122.png'), layout: { w: 0.7163, top: -0.0352 }, rarity: 'common', unlock: runs(8, 'Finish 8 runs') },
    { id: 'derbyhat', label: 'Derby hat', img: require('../../assets/character/headwear/hat124.png'), layout: { w: 0.7485, top: -0.0486 }, hidesBulky: true, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'dadcap', label: 'Dad cap', img: require('../../assets/character/headwear/hat125.png'), layout: { w: 0.787, top: -0.0382, dx: 0.0028 }, hidesBulky: true, rarity: 'common', unlock: free },
    { id: 'topbow', label: 'Top bow', img: require('../../assets/character/headwear/hat129.png'), layout: { w: 0.6623, top: -0.0387, dx: 0.0032 }, rarity: 'common', unlock: free },
    { id: 'boaterhat', label: 'Boater hat', img: require('../../assets/character/headwear/hat130.png'), layout: { w: 0.9367, top: -0.0227 }, hidesBulky: true, rarity: 'common', unlock: dist(15, 'Run 15 km total') },
    { id: 'pearltiara', label: 'Pearl tiara', img: require('../../assets/character/headwear/hat131.png'), layout: { w: 0.6609, top: -0.0241, dx: 0.003 }, rarity: 'rare', unlock: streak(3, 'Hold a 3 week streak') },
    { id: 'swimcap', label: 'Swim cap', img: require('../../assets/character/headwear/hat132.png'), layout: { w: 0.6684, top: -0.0076 }, hideHair: true, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'bigbow', label: 'Big bow', img: require('../../assets/character/headwear/hat133.png'), layout: { w: 0.6572, top: -0.0059 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    // --- PASER running cosmetics (2026-09-17) ---
    { id: 'lightweightracecap', label: 'Lightweight Race Cap', img: require('../../assets/character/headwear/38_lightweight_race_cap.png'), layout: { w: 0.9796, top: -0.139, dx: -0.0001 }, hidesBulky: true, rarity: 'common', unlock: free },
    { id: 'reflectivenightcap', label: 'Reflective Night Cap', img: require('../../assets/character/headwear/39_reflective_night_cap.png'), layout: { w: 0.9529, top: -0.1325, dx: -0.0034 }, hidesBulky: true, rarity: 'epic', unlock: free },
    { id: 'trailsuncap', label: 'Trail Sun Cap', img: require('../../assets/character/headwear/40_trail_sun_cap.png'), layout: { w: 0.9396, top: -0.1377, dx: 0.0033 }, hidesBulky: true, rarity: 'common', unlock: free },
  ],
  accessory: [
    { id: 'none', label: 'None', art: null, rarity: 'common', unlock: free },
    { id: 'jetpack', label: 'Jetpack', img: require('../../assets/character/accessory/acc9.png'), z: 'back', layout: { w: 1.4033, cy: 0.5316, dx: -0.0333 }, rarity: 'legendary', unlock: premiumOnly },
    { id: 'greenscarf', label: 'Knit scarf', img: require('../../assets/character/accessory/acc17.png'), backImg: require('../../assets/character/accessory/acc17b.png'), z: 'front', layout: { w: 0.55, top: 0.2764 }, rarity: 'common', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'tealscarf', label: 'Winter scarf', img: require('../../assets/character/accessory/acc18.png'), backImg: require('../../assets/character/accessory/acc18b.png'), z: 'front', layout: { w: 0.55, top: 0.2814 }, rarity: 'common', unlock: dist(15, 'Run 15 km total') },
    // --- wave 3 (2026-07-31) ---
    { id: 'pearlcollar', label: 'Pearl collar', img: require('../../assets/character/accessory/acc25.png'), backImg: require('../../assets/character/accessory/acc25b.png'), z: 'front', layout: { w: 0.4367, top: 0.3188, dx: -0.0016 }, rarity: 'rare', unlock: level(12) },
    { id: 'pearls', label: 'Pearl strand', img: require('../../assets/character/accessory/acc26.png'), backImg: require('../../assets/character/accessory/acc26b.png'), z: 'front', layout: { w: 0.4267, top: 0.2975, dx: -0.0033 }, rarity: 'common', unlock: dist(15, 'Run 15 km total') },
    { id: 'charmchain', label: 'Charm chain', img: require('../../assets/character/accessory/acc27.png'), backImg: require('../../assets/character/accessory/acc27b.png'), z: 'front', layout: { w: 0.42, top: 0.292, dx: 0.0033 }, rarity: 'common', unlock: runs(10, 'Finish 10 runs') },
    { id: 'flowerchain', label: 'Daisy chain', img: require('../../assets/character/accessory/acc28.png'), backImg: require('../../assets/character/accessory/acc28b.png'), z: 'front', layout: { w: 0.4067, top: 0.2964, dx: -0.0067 }, rarity: 'common', unlock: free },
    { id: 'lei', label: 'Flower lei', img: require('../../assets/character/accessory/acc29.png'), backImg: require('../../assets/character/accessory/acc29b.png'), z: 'front', layout: { w: 0.4467, top: 0.3009, dx: 0.0033 }, rarity: 'common', unlock: dist(10, 'Run 10 km total') },
    { id: 'neckerchief', label: 'Neckerchief', img: require('../../assets/character/accessory/acc30.png'), backImg: require('../../assets/character/accessory/acc30b.png'), z: 'front', layout: { w: 0.42, top: 0.2986, dx: 0.0033 }, rarity: 'common', unlock: free },
    { id: 'sailorcollar', label: 'Sailor collar', img: require('../../assets/character/accessory/acc31.png'), backImg: require('../../assets/character/accessory/acc31b.png'), z: 'front', layout: { w: 0.5767, top: 0.3099, dx: 0.005 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'necktie', label: 'Necktie', img: require('../../assets/character/accessory/acc33.png'), backImg: require('../../assets/character/accessory/acc33b.png'), z: 'front', layout: { w: 0.39, top: 0.3044, dx: 0.0016 }, rarity: 'common', unlock: runs(8, 'Finish 8 runs') },
    { id: 'candyscarf', label: 'Candy scarf', img: require('../../assets/character/accessory/acc38.png'), backImg: require('../../assets/character/accessory/acc38b.png'), z: 'front', layout: { w: 0.4667, top: 0.2879, dx: -0.0033 }, rarity: 'common', unlock: streak(3, 'Hold a 3 week streak') },
    { id: 'redscarf', label: 'Red scarf', img: require('../../assets/character/accessory/acc39.png'), backImg: require('../../assets/character/accessory/acc39b.png'), z: 'front', layout: { w: 0.4567, top: 0.2747, dx: 0.0017 }, rarity: 'common', unlock: runs(12, 'Finish 12 runs') },
    { id: 'pageantsash', label: 'Pageant sash', img: require('../../assets/character/accessory/acc40.png'), z: 'front', layout: { w: 0.7967, top: 0.3328, dx: -0.0083 }, rarity: 'rare', unlock: zones(5, 'Hold 5 zones') },
    { id: 'racesash', label: 'Race sash', img: require('../../assets/character/accessory/acc41.png'), z: 'front', layout: { w: 0.72, top: 0.3354, dx: 0.0067 }, rarity: 'rare', unlock: runs(25, 'Finish 25 runs') },
    { id: 'harness', label: 'Race harness', img: require('../../assets/character/accessory/acc43.png'), z: 'front', layout: { w: 0.63, top: 0.3276, dx: 0.0017 }, rarity: 'rare', unlock: dist(75, 'Run 75 km total') },
    { id: 'fairywings', label: 'Fairy wings', img: require('../../assets/character/accessory/acc44.png'), z: 'back', layout: { w: 1.9, cy: 0.3598 }, rarity: 'legendary', unlock: level(36) },
    { id: 'handbag', label: 'Handbag', img: require('../../assets/character/accessory/acc47.png'), z: 'front', layout: { w: 0.62, top: 0.3326, dx: -0.0067 }, rarity: 'common', unlock: dist(15, 'Run 15 km total') },
    { id: 'sheriffstar', label: 'Sheriff star', img: require('../../assets/character/accessory/acc49.png'), z: 'front', layout: { w: 0.24, top: 0.3814, dx: 0.1167 }, rarity: 'rare', unlock: zones(8, 'Hold 8 zones') },
    // --- PASER running cosmetics (2026-09-17) ---
  ],
  glasses: [
    { id: 'none', label: 'None', art: null, rarity: 'common', unlock: free },
    { id: 'rects', label: 'Rectangle shades', img: require('../../assets/character/glasses/specs2.png'), layout: { w: 0.6011, cy: 0.183, dx: 0.0016 }, rarity: 'rare', unlock: passOnly },
    { id: 'halfframe', label: 'Half frames', img: require('../../assets/character/glasses/specs8.png'), layout: { w: 0.62, cy: 0.1877, dx: 0 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    // Tallest eyewear art by a distance — narrower so its height lands in
    // line with the rest instead of covering half the face.
    { id: 'monocle', label: 'Monocle', img: require('../../assets/character/glasses/specs11.png'), layout: { w: 0.59, cy: 0.1723, dx: 0.0016 }, rarity: 'epic', unlock: premiumOnly },
    { id: 'cybershades', label: 'Cyber shades', img: require('../../assets/character/glasses/specs12.png'), layout: { w: 0.6133, cy: 0.1719, dx: 0.0033 }, rarity: 'legendary', unlock: premiumOnly },
    { id: 'starglasses', label: 'Star shades', img: require('../../assets/character/glasses/specs14.png'), layout: { w: 0.58, cy: 0.1825, dx: 0 }, rarity: 'rare', unlock: streak(2, 'Hold a 2 week streak') },
    { id: 'steampunk', label: 'Steampunk goggles', img: require('../../assets/character/glasses/specs15.png'), layout: { w: 0.61, cy: 0.1793, dx: 0.0017 }, rarity: 'epic', unlock: passOnly },
    { id: 'hexshades', label: 'Hex shades', img: require('../../assets/character/glasses/specs16.png'), layout: { w: 0.5867, cy: 0.1821, dx: 0.0034 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
    { id: 'cateye', label: 'Cat eye', img: require('../../assets/character/glasses/specs17.png'), layout: { w: 0.61, cy: 0.1866, dx: 0.0017 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'aviators', label: 'Aviators', img: require('../../assets/character/glasses/specs19.png'), layout: { w: 0.6, cy: 0.1925, dx: 0.0033 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'eyepatch', label: 'Eyepatch', img: require('../../assets/character/glasses/specs20.png'), layout: { w: 0.5766, cy: 0.1919, dx: -0.0017 }, rarity: 'rare', unlock: zones(3, 'Hold 3 zones') },
    { id: 'clownglasses', label: 'Clown glasses', img: require('../../assets/character/glasses/specs21.png'), layout: { w: 0.6934, cy: 0.1929, dx: 0.0033 }, rarity: 'rare', unlock: runs(20, 'Finish 20 runs') },
    { id: 'sleepmask', label: 'Sleep mask', img: require('../../assets/character/glasses/specs22.png'), layout: { w: 0.6067, cy: 0.1802, dx: -0.0033 }, rarity: 'common', unlock: streak(3, 'Hold a 3 week streak') },
    { id: 'heromask', label: 'Hero mask', img: require('../../assets/character/glasses/specs23.png'), layout: { w: 0.6233, cy: 0.1862, dx: -0.0017 }, rarity: 'epic', unlock: level(24) },
    // --- wave 3 (2026-07-31) ---
    { id: 'weldgoggles', label: 'Welder goggles', img: require('../../assets/character/glasses/specs24.png'), layout: { w: 0.6333, cy: 0.1839, dx: 0.0034 }, rarity: 'epic', unlock: level(22) },
    { id: 'pearlspecs', label: 'Pearl specs', img: require('../../assets/character/glasses/specs25.png'), layout: { w: 0.64, cy: 0.1921 }, rarity: 'rare', unlock: streak(3, 'Hold a 3 week streak') },
    { id: 'butterfly', label: 'Butterfly shades', img: require('../../assets/character/glasses/specs26.png'), layout: { w: 0.6933, cy: 0.1885, dx: 0 }, rarity: 'rare', unlock: runs(12, 'Finish 12 runs') },
    { id: 'tintgoggles', label: 'Tint goggles', img: require('../../assets/character/glasses/specs27.png'), layout: { w: 0.6567, cy: 0.1888, dx: 0.015 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'onimask', label: 'Oni mask', img: require('../../assets/character/glasses/specs28.png'), layout: { w: 0.87, cy: 0.1989, dx: 0.0083 }, rarity: 'legendary', unlock: passOnly },
    // --- PASER running cosmetics (2026-09-17) ---
  ],
  top: [
    { id: 'daisydress', label: 'Daisy dress', img: require('../../assets/character/outfit/top4.png'), layout: { w: 0.9488, top: 0.3251, dx: 0.0017 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'overshirt', label: 'Overshirt', img: require('../../assets/character/outfit/top6.png'), layout: { w: 0.9867, top: 0.2921, dx: -0.0083 }, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
    { id: 'sweater', label: 'Sweater', img: require('../../assets/character/outfit/top11.png'), layout: { w: 0.9651, top: 0.322, dx: 0.0033 }, rarity: 'rare', unlock: dist(25, 'Run 25 km total') },
    { id: 'singlet', label: 'Race singlet', img: require('../../assets/character/outfit/top12.png'), layout: { w: 0.6233, top: 0.3343, dx: -0.0033 }, rarity: 'common', unlock: free },
    { id: 'oversized', label: 'Oversized tee', img: require('../../assets/character/outfit/top17.png'), layout: { w: 1, top: 0.3228, dx: 0.01 }, rarity: 'common', unlock: runs(3, 'Finish 3 runs') },
    { id: 'camisole', label: 'Camisole', img: require('../../assets/character/outfit/top16.png'), layout: { w: 0.6067, top: 0.3449, dx: 0.0033 }, rarity: 'common', unlock: runs(5, 'Finish 5 runs') },
    { id: 'polo', label: 'PE polo', img: require('../../assets/character/outfit/top13.png'), layout: { w: 0.95, top: 0.3021 }, rarity: 'common', unlock: runs(10, 'Finish 10 runs') },
    { id: 'windbreaker', label: 'Windbreaker', img: require('../../assets/character/outfit/top14.png'), layout: { w: 0.98, top: 0.2744 }, rarity: 'rare', unlock: dist(50, 'Run 50 km total') },
    // Drawn much longer than the other tops (313px against a 225px median),
    // so at full width it hung past the hips and over the bottoms.
  ],
  bottom: [
    { id: 'none', label: 'None', art: null, rarity: 'common', unlock: free },
    // --- wave 3 (2026-07-31) ---
  ],
};

// The outfit wave is appended rather than inlined: it is generated art (see
// config/outfitItems.js), and keeping it out of the hand-written lists means
// a re-run of the cutter never has to reconcile with edits made here.
ITEMS.hair.push(...HAIR_SHEETS);
ITEMS.headwear.push(...CURATED_HEADWEAR);
ITEMS.glasses.push(...CURATED_GLASSES);
ITEMS.accessory.push(...CURATED_ACCESSORIES, ...CURATED_EXTRAS);
ITEMS.top.push(...OUTFIT_TOPS, ...OUTFIT_SUITS);
ITEMS.top.push(...CURATED_TOPS);
ITEMS.bottom.push(...OUTFIT_BOTTOMS);
ITEMS.bottom.push(...CURATED_BOTTOMS);
ITEMS.footwear = [
  { id: 'none', label: 'Barefoot', art: null, rarity: 'common', unlock: free },
  ...FOOTWEAR,
  ...CURATED_FOOTWEAR,
];

// ---------------------------------------------------------------------------
// First run — a STARTER RACK, not the catalogue
// ---------------------------------------------------------------------------
//
// The wardrobe is big on purpose: it is the thing lootboxes, the pass and the
// level ladder hand out over a season. Showing all of it in the five minutes
// before anybody has run a step is the one place that works against itself —
// forty-six pairs of shorts is a shop, not a character, and the reward loses
// its shine when the runner has already seen (and could already wear) every
// piece of it on day zero.
//
// So the first-run steps draw from these lists instead: a handful per slot,
// picked to cover the shapes rather than the colourways, so every choice
// reads as a different character rather than the same tee in a tenth tint.
// Everything left out is still FREE — it is simply met later, in the Avatar
// Studio, where the rest of the catalogue is the point.
//
// Faces get the smallest rack of all, because faces are the collection: most
// of them unlock as you run or come off the pass, and the first run is where
// that collection starts, not where it is handed out. List FREE faces only.
// During the first run /me/stats has usually not landed, and `isUnlocked`
// reads a stat gate with no stats behind it as open (so the studio never locks
// something wrongly while it loads). That put every stat gated face in the
// signup grid as a free pick; the rack is what keeps them out of it.
//
// Slots not listed here (glasses, footwear, extras) show their unlocked list
// unchanged: they are small already, or they are not part of the flow.
export const FIRST_RUN_ITEMS = {
  face: ['smiley', 'chill', 'laugh'],
  hair: [
    'none', 'hijab', 'hs11', 'twoblock', 'curtains', 'middlepart',
    'swept', 'curls', 'pixie', 'fringebob',
  ],
  top: [
    'cur_everydaytechnicaltee', 'singlet', 'o56t',
    'cur_hotweathermeshtee', 'cur_teamjersey', 'cur_greeneverydayrunningshirt',
    'cur_lightweightrainshell', 'cur_runclubtechnicalshirt',
  ],
  bottom: [
    'wb012', 'wb002', 'wb018', 'wb072', 'wb083', 'wb106',
    'wb111',
  ],
  footwear: [
    'wf001', 'wf008', 'wf019', 'wf023', 'wf064', 'wf051',
  ],
  headwear: [
    'none', 'cap', 'sportcap', 'runvisor', 'knitbeanie',
  ],
  glasses: [
    'cur_roundframes', 'cur_wayfarers',
  ],
  accessory: [
    'cur_neckgaiter',
  ],
};

/**
 * The grid one first-run step should show.
 *
 * `unlocked` is the runner's own unlocked list for the slot — already filtered
 * by the caller, because only it knows the entitlement context. The starter
 * rack is applied ON TOP of that and never widens it, so a piece that has not
 * been earned cannot slip into the flow through this door.
 *
 * `keepId` is whatever is worn right now, and it survives the rack whether it
 * is in it or not: the runner may arrive wearing a pass reward or a piece
 * chosen in the Studio, and a grid that cannot show what is already on the
 * character reads as the selection having been lost.
 *
 * Two guards, both about never handing back an empty grid: an id that has been
 * renamed out of the catalogue is skipped, and if the intersection comes out
 * too thin to be a choice at all (art pulled, a slot renamed wholesale) the
 * full list comes back rather than a step with two tiles on it.
 */
export function firstRunItems(slot, unlocked, keepId) {
  const rack = FIRST_RUN_ITEMS[slot];
  if (!rack) return unlocked;
  const wanted = new Set(rack);
  const picked = unlocked.filter((item) => wanted.has(item.id) || item.id === keepId);
  return picked.length >= 3 ? picked : unlocked;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// `getItem` is called 8x (once per slot) on every render of every mounted
// CharacterRig — a feed of busts, up to 6 bodies in a capture cutscene — and
// was doing a linear `Array.find` through catalogues up to 124 items long
// (headwear) every single time. `ITEMS` is the static catalogue, frozen at
// import time and never mutated at runtime, so it is safe to index once per
// slot and reuse the index for the app's whole lifetime.
const ITEM_INDEX = {};
function itemIndexFor(slot) {
  let index = ITEM_INDEX[slot];
  if (!index) {
    index = new Map();
    (ITEMS[slot] || []).forEach((item) => index.set(item.id, item));
    ITEM_INDEX[slot] = index;
  }
  return index;
}

export function getItem(slot, id) {
  const list = ITEMS[slot] || [];
  return itemIndexFor(slot).get(id) || list[0];
}

const COLOR_KEY = { hair: 'hairColor', headwear: 'headwearColor', glasses: 'glassesColor', top: 'topColor', bottom: 'bottomColor' };

// The picker should show each older item's authored colour, not palette index
// zero (the white/grey recolour master). Equipping still uses `art` and the
// selected swatch, so this restores the catalogue art without removing colour
// customisation from the runner.
const AUTHORED_PREVIEWS = {
};

// The image for an item in the loadout's chosen color (faces are fixed art).
export function itemImage(slot, item, equipped) {
  if (item.img) return item.img;
  if (!item.art) return null;
  const idx = equipped?.[COLOR_KEY[slot]] ?? 0;
  return item.art[Math.max(0, Math.min(item.art.length - 1, idx))];
}

export function itemPreviewImage(slot, item) {
  if (!item) return null;
  return AUTHORED_PREVIEWS[`${slot}:${item?.id}`] || itemImage(slot, item, null);
}

// Open footwear — slides, sandals, clogs, anything you can see into — ships a
// second image for WEARING, with the shoe's own lining punched out so the
// leg shows through the mouth and the rim closes around it instead of the
// runner standing next to a shoe. `img` stays the picker's, because a shoe
// with a see-through middle only reads correctly on a leg. Shoes that split
// into footL/footR carry the cut in those halves and need nothing here.
export function itemWornImage(slot, item, equipped) {
  return item?.wornImg || itemImage(slot, item, equipped);
}

// Wrap-around items (sweatband, visor, medals, scarf, cape) split into a
// front image + a back image rendered BEHIND the body, so the piece reads as
// going around the head/neck instead of pasted on top. Same canvas dims as
// the front → same layout placement.
export function itemBackImage(slot, item, equipped) {
  if (item.backImg) return item.backImg;
  if (!item.backArt) return null;
  const idx = equipped?.[COLOR_KEY[slot]] ?? 0;
  return item.backArt[Math.max(0, Math.min(item.backArt.length - 1, idx))];
}

// Unlock evaluation. `unlock` is null (starter), a stat predicate, or a pass
// marker. Stats come from /me/stats (including `level`,
// `runs_count`, `career_distance_m`, `territory_count`, `current_streak_weeks`).
// A `{ clan: true }` predicate requires club membership. Missing ctx/stats →
// unlocked (so the studio never wrongly locks before stats load).
// Server-granted unlocks (both pass tracks, shop buys, lootbox rolls) arrive from
// /me/progression as "<slot>:<id>". Ids are unique across slots — except
// 'none', which is free everywhere — so a flat Set of bare ids is enough and
// keeps `isUnlocked` from needing to know its own slot.
export function unlockSet(list) {
  return new Set((list || []).map((k) => String(k).split(':').pop()));
}

export function isUnlocked(item, ctx) {
  // DEV: everything unlocked in development builds so asset placement can be
  // tested without grinding stats. __DEV__ is false in release builds, so
  // store users still earn their unlocks.
  if (typeof __DEV__ !== 'undefined' && __DEV__) return true;
  // Anything the server handed you outranks the local gate.
  if (ctx?.unlocks?.has?.(item?.id)) return true;
  const u = item?.unlock;
  if (!u) return true;
  if (!ctx) return true;
  // Pass cosmetics have no stat route. Claiming the matching tier writes the
  // server grant checked above.
  if (u.pass || u.premium) return false;
  if (u.clan) return !!ctx.hasClan;
  if (!ctx.stats) return true;
  return Number(ctx.stats[u.stat] || 0) >= Number(u.value || 0);
}

export function unlockLabel(item) {
  return item.unlock?.label || null;
}

/**
 * Is this a PASER PRO exclusive?
 *
 * `unlock.premium` is the entitlement marker the catalogue already carried
 * (see `premiumOnly` at the top of this file) and it stays the ONE source of
 * truth — a second `isPro: true` field alongside it would be two flags that
 * eventually disagree about the same hat, and the server half
 * (PREMIUM_ITEMS in backend/app/progression.py) is keyed to this one.
 *
 * Used by the studio to decide which locked items are worth TRYING ON rather
 * than refusing: a stat gate ("finish 5 runs") is an instruction, and a
 * preview of it would just be a tease. A PRO exclusive is a purchase, and
 * nobody buys a hat they have not seen on their own character.
 */
export function isProItem(item) {
  return !!item?.unlock?.premium;
}

export const DEFAULT_EQUIPPED = {
  face: 'smiley',
  hair: 'curtains',
  hairColor: 4,        // blonde
  headwear: 'none',
  headwearColor: 7,    // blue
  glasses: 'none',
  glassesColor: 1,
  top: 'daisydress',
  topColor: 7,         // blue
  // Wave 6 refilled this slot; a new runner starting with no bottoms at all
  // reads as a bug rather than a style. Neutral navy trousers.
  bottom: 'wb009',
  bottomColor: 1,      // black
  // Existing loadouts predate this slot and have no `footwear` key at all, so
  // the rig falls back to 'none' — barefoot, which is what the leg art already
  // showed. Nobody's saved runner changes underneath them.
  footwear: 'none',
  accessory: 'none',
};

// The handful of layers needed to draw one complete runner. Preloading only
// the equipped loadout keeps profile/feed portraits instant without decoding
// the whole (very large) cosmetics catalogue into memory.
export function equippedImageSources(equipped) {
  // `?? DEFAULT_EQUIPPED` rather than a default parameter: a runner who never
  // opened the studio has `avatar: null`, and a default only covers undefined.
  const worn = equipped || DEFAULT_EQUIPPED;
  const selected = Object.fromEntries(
    SLOTS.map(({ key }) => [key, getItem(key, worn[key])])
  );

  return [
    BODY_IMG,
    HEAD_IMG,
    itemBackImage('accessory', selected.accessory, worn),
    itemBackImage('headwear', selected.headwear, worn),
    itemImage('bottom', selected.bottom, worn),
    itemImage('footwear', selected.footwear, worn),
    itemImage('top', selected.top, worn),
    itemImage('accessory', selected.accessory, worn),
    itemImage('face', selected.face, worn),
    itemImage('hair', selected.hair, worn),
    itemImage('glasses', selected.glasses, worn),
    itemImage('headwear', selected.headwear, worn),
  ].filter(Boolean);
}

// One thumbnail per item for a customisation category. Hair accepts a preview
// colour override because the studio deliberately uses blonde on dark cards
// and dark hair on light cards for contrast.
export function itemPreviewSources(slot, previewEquipped = null) {
  return (ITEMS[slot] || [])
    .filter((item) => !isHiddenItem(item))
    .map((item) => (
      previewEquipped ? itemImage(slot, item, previewEquipped) : itemPreviewImage(slot, item)
    ))
    .filter(Boolean);
}

export function itemVariantSources(item) {
  if (!item) return [];
  return [item.img, item.backImg, item.art || [], item.backArt || []]
    .flat(Infinity)
    .filter(Boolean);
}

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
const pickIdx = (arr) => Math.floor(Math.random() * arr.length);

// Random loadout from the user's UNLOCKED pool only.
export function randomEquipped(ctx) {
  // Hidden items (hiddenCosmetics.js) are never rolled onto a character.
  const pool = (slot) => (ITEMS[slot] || []).filter((i) => isUnlocked(i, ctx) && !isHiddenItem(i));
  return {
    face: pick(pool('face')).id,
    hair: pick(pool('hair')).id,
    hairColor: pickIdx(HAIR_COLORS),
    headwear: pick(pool('headwear')).id,
    headwearColor: pickIdx(CLOTH_COLORS),
    glasses: pick(pool('glasses')).id,
    glassesColor: pickIdx(CLOTH_COLORS),
    top: pick(pool('top')).id,
    topColor: pickIdx(CLOTH_COLORS),
    bottom: pick(pool('bottom')).id,
    bottomColor: pickIdx(CLOTH_COLORS),
    footwear: pick(pool('footwear')).id,
    accessory: pick(pool('accessory')).id,
  };
}
