// Companion metadata for the live cosmetic catalogue.
//
// This file is deliberately DATA ONLY. It does not participate in unlocks,
// ownership, rendering, lootboxes, progression, or FIRST_RUN_ITEMS. IDs remain
// authoritative in cosmetics.js and its generated supplements.
//
// Keep one key per globally unique cosmetic ID. The legacy sentinel "none" is
// shared by six slots and therefore has one shared curation record. Run
// `npm run check:curation` after editing.
//
// Bootstrap convention: PRO/pass rewards start in `vault`; recognisably
// running, trail, club, or Singapore pieces start in `core`; ordinary casual
// and costume pieces start in `lifestyle`. `collection` remains null until
// named collections are curated. Generated wardrobe `family` values are
// carried across verbatim so colourways of one silhouette stay together.

export const COSMETIC_STATUSES = ['core', 'lifestyle', 'vault', 'retired'];
export const COSMETIC_THEMES = ['running', 'trail', 'club', 'singapore', 'casual', 'fantasy'];
export const COSMETIC_ACQUISITION_TYPES = [
  'starter', 'distance', 'runs', 'streak', 'zones', 'level', 'club',
  'lootbox', 'battlepass', 'pro', 'event', 'special', null,
];

export const COSMETIC_CURATION = {
  "angelheart": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "angry": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "antlers": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"zones"},
  "aviatorcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "aviators": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "ballcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bandana": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "bangs": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "beam": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "beanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "beret": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "bigafro": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bigbow": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bikehelmet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "bloomcrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "bluntbob": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "blush": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "boater": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "boaterhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bowband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "bowberet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bowcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bowler": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bowwrap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "braids": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "bucket": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "bunnyears": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "bunstrands": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "butterfly": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "butterflyclip": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "buzz": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "camisole": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "candyscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "canvasbucket": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "cap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "captaincap": {"status":"core","theme":"club","collection":null,"family":null,"acquisitionType":"zones"},
  "catbeanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "catears": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cateye": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "charmchain": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "chefhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "cheftoque": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "cherrybopper": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "chill": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "classiccap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cleargoggles": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "clochehat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "clownglasses": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "comma": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "content": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cowboyhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "cowpokehat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "cuffbeanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "curls": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "curtainlong": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "curtains": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "cybershades": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "dadcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "daisyband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "daisydress": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "deadpan": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "derbyhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "determined": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "devilhorns": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "dogtags": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "exhausted": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "eyepatch": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "fairywings": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "fedora": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "fez": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "firehelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "flamecrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "flatberet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "flatcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "flatsnap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "flightcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "flow": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "flowerchain": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "flowerclip": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "flowercrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "fringebob": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "fringebun": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "frogbeanie": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"runs"},
  "gardenhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "gasp": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "glum": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "golfcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "gradcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "greenscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "grump": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "halfframe": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "halo": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "haloring": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "handbag": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "hardhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "harness": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"distance"},
  "headdress": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "headphones": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "headscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "headwrap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "heartbopper": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "hearteyes": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "heromask": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "hexshades": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "highbun": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "highpony": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "hijab": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "hs11": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs15": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs22": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs25": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "hs26": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "jestercap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "jetpack": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"pro"},
  "jeweltiara": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "jockeycap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "joy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "k10t": {"status":"vault","theme":"club","collection":null,"family":"Varsity jacket","acquisitionType":"pro"},
  "k12t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop jacket","acquisitionType":"runs"},
  "k14t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop puffer","acquisitionType":"starter"},
  "k5t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop tee","acquisitionType":"starter"},
  "k8t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Half zip","acquisitionType":"starter"},
  "k9t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Block hoodie","acquisitionType":"starter"},
  "kabuto": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "kittyears": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "knitbeanie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "laugh": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "laurel": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "laurelcrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "lei": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "longwaves": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "loveboppers": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "maidband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "messy": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "middlepart": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "minerhelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "mobcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "monocle": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"pro"},
  "mortarboard": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "navycap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "neckerchief": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "necktie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "neutral": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "newsboy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "none": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "nursecap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "o13t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Ringer tee","acquisitionType":"runs"},
  "o56t": {"status":"core","theme":"running","collection":null,"family":"Sports bra","acquisitionType":"starter"},
  "o68t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pullover hoodie","acquisitionType":"runs"},
  "o6t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Crop polo","acquisitionType":"starter"},
  "o72t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Heart cardigan","acquisitionType":"starter"},
  "o89t": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bomber jacket","acquisitionType":"runs"},
  "officercap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "onimask": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "overshirt": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "oversized": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "pageantsash": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "paradeshako": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "pearlcollar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "pearls": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "pearlspecs": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "pearltiara": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"streak"},
  "pinkbow": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "pinupwrap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "piratehat": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "pixie": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "polo": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "pombeanie": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "puffmuffs": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "punkcrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "rabbitears": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "racesash": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"runs"},
  "rage": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "ravenlong": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "rects": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "redscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "ribboncap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "rodeohat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "rosecrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"starter"},
  "roundfro": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "royalcrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "runvisor": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "sad": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sailorcollar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "sailorhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "samuraihelm": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "santahat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "scallopband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "scarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "scrumcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "sheriffstar": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "sidepony": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "singlet": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "sitehelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "skatehelmet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "skullcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "sleeklong": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sleepmask": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "sleepy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "slouchberet": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "sly": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "smiley": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "smirk": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "snapback": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "sob": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "softwaves": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "spacebuns": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "spacehelmet": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "spikecrown": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"zones"},
  "sportcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"starter"},
  "stareyes": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"zones"},
  "starglasses": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"streak"},
  "starnecklace": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "steampunk": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "sultanturban": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "sunbowhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "surfer": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "sweatband": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "sweater": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "swept": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "swimcap": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "tealscarf": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "texturedcrop": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "tiara": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "tiedbandana": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "tintgoggles": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "tongueout": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "topbow": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "tophat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "topknot": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "trapperhat": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "tricorn": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "turban": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"zones"},
  "twoblock": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "uneasy": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "unicornhorn": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "ushanka": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "vikinghelm": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "visor": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":"distance"},
  "wb001": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sweat shorts","acquisitionType":"starter"},
  "wb002": {"status":"lifestyle","theme":"casual","collection":null,"family":"Gym shorts","acquisitionType":"starter"},
  "wb003": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cuffed shorts","acquisitionType":"starter"},
  "wb004": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb009": {"status":"lifestyle","theme":"casual","collection":null,"family":"Trousers","acquisitionType":"starter"},
  "wb012": {"status":"core","theme":"running","collection":null,"family":"Track shorts","acquisitionType":"starter"},
  "wb013": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pleated skirt","acquisitionType":"starter"},
  "wb014": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb017": {"status":"lifestyle","theme":"casual","collection":null,"family":"Swim shorts","acquisitionType":"starter"},
  "wb018": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb019": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pinstripe trousers","acquisitionType":"starter"},
  "wb021": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb024": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pleated shorts","acquisitionType":"starter"},
  "wb025": {"status":"vault","theme":"running","collection":null,"family":"Running shorts","acquisitionType":"battlepass"},
  "wb026": {"status":"lifestyle","theme":"casual","collection":null,"family":"Denim shorts","acquisitionType":"starter"},
  "wb027": {"status":"core","theme":"trail","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb031": {"status":"lifestyle","theme":"casual","collection":null,"family":"Gingham skirt","acquisitionType":"starter"},
  "wb032": {"status":"lifestyle","theme":"casual","collection":null,"family":"Knee shorts","acquisitionType":"starter"},
  "wb043": {"status":"lifestyle","theme":"casual","collection":null,"family":"Drawstring shorts","acquisitionType":"starter"},
  "wb047": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sweat shorts","acquisitionType":"starter"},
  "wb048": {"status":"core","theme":"running","collection":null,"family":"Running shorts","acquisitionType":"starter"},
  "wb054": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pinstripe shorts","acquisitionType":"starter"},
  "wb056": {"status":"lifestyle","theme":"casual","collection":null,"family":"Drawstring shorts","acquisitionType":"starter"},
  "wb061": {"status":"lifestyle","theme":"casual","collection":null,"family":"Corduroy shorts","acquisitionType":"starter"},
  "wb062": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb065": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"runs"},
  "wb068": {"status":"lifestyle","theme":"casual","collection":null,"family":"Corduroy shorts","acquisitionType":"starter"},
  "wb071": {"status":"lifestyle","theme":"casual","collection":null,"family":"Plaid shorts","acquisitionType":"starter"},
  "wb072": {"status":"lifestyle","theme":"casual","collection":null,"family":"Compression shorts","acquisitionType":"starter"},
  "wb073": {"status":"lifestyle","theme":"casual","collection":null,"family":"Tennis skirt","acquisitionType":"starter"},
  "wb083": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skort","acquisitionType":"starter"},
  "wb084": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb086": {"status":"lifestyle","theme":"casual","collection":null,"family":"Bike shorts","acquisitionType":"starter"},
  "wb092": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo trousers","acquisitionType":"starter"},
  "wb093": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb097": {"status":"lifestyle","theme":"casual","collection":null,"family":"Plaid shorts","acquisitionType":"starter"},
  "wb102": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cropped jeans","acquisitionType":"starter"},
  "wb103": {"status":"lifestyle","theme":"casual","collection":null,"family":"Cargo shorts","acquisitionType":"starter"},
  "wb106": {"status":"lifestyle","theme":"casual","collection":null,"family":"Leggings","acquisitionType":"starter"},
  "wb107": {"status":"lifestyle","theme":"casual","collection":null,"family":"Pleated skirt","acquisitionType":"starter"},
  "wb108": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skirt","acquisitionType":"starter"},
  "wb109": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chino shorts","acquisitionType":"starter"},
  "wb110": {"status":"vault","theme":"running","collection":null,"family":"Race shorts","acquisitionType":"battlepass"},
  "wb111": {"status":"core","theme":"running","collection":null,"family":"Cropped joggers","acquisitionType":"starter"},
  "weddingveil": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "weldgoggles": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"level"},
  "wf001": {"status":"core","theme":"running","collection":null,"family":"Trainers","acquisitionType":"starter"},
  "wf002": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skate shoes","acquisitionType":"starter"},
  "wf004": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slip ons","acquisitionType":"starter"},
  "wf005": {"status":"vault","theme":"running","collection":null,"family":"Runners","acquisitionType":"battlepass"},
  "wf006": {"status":"core","theme":"trail","collection":null,"family":"Trail shoes","acquisitionType":"starter"},
  "wf007": {"status":"lifestyle","theme":"casual","collection":null,"family":"High tops","acquisitionType":"starter"},
  "wf008": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf009": {"status":"lifestyle","theme":"casual","collection":null,"family":"Canvas sneakers","acquisitionType":"starter"},
  "wf010": {"status":"vault","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"battlepass"},
  "wf011": {"status":"vault","theme":"running","collection":null,"family":"Runners","acquisitionType":"battlepass"},
  "wf012": {"status":"lifestyle","theme":"casual","collection":null,"family":"Retro sneakers","acquisitionType":"starter"},
  "wf013": {"status":"core","theme":"running","collection":null,"family":"Trainers","acquisitionType":"starter"},
  "wf015": {"status":"core","theme":"running","collection":null,"family":"Knit runners","acquisitionType":"runs"},
  "wf018": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"starter"},
  "wf019": {"status":"core","theme":"running","collection":null,"family":"Tech runners","acquisitionType":"starter"},
  "wf020": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"runs"},
  "wf021": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf022": {"status":"lifestyle","theme":"casual","collection":null,"family":"High tops","acquisitionType":"distance"},
  "wf023": {"status":"core","theme":"trail","collection":null,"family":"Trail runners","acquisitionType":"starter"},
  "wf024": {"status":"lifestyle","theme":"casual","collection":null,"family":"High tops","acquisitionType":"starter"},
  "wf025": {"status":"lifestyle","theme":"casual","collection":null,"family":"Canvas sneakers","acquisitionType":"runs"},
  "wf026": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf027": {"status":"core","theme":"trail","collection":null,"family":"Hiking shoes","acquisitionType":"starter"},
  "wf028": {"status":"core","theme":"running","collection":null,"family":"Runners","acquisitionType":"starter"},
  "wf029": {"status":"core","theme":"running","collection":null,"family":"Trainers","acquisitionType":"starter"},
  "wf030": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"runs"},
  "wf031": {"status":"lifestyle","theme":"casual","collection":null,"family":"Platform sneakers","acquisitionType":"starter"},
  "wf032": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slides","acquisitionType":"starter"},
  "wf034": {"status":"lifestyle","theme":"casual","collection":null,"family":"Ballet flats","acquisitionType":"starter"},
  "wf036": {"status":"core","theme":"trail","collection":null,"family":"Hiking boots","acquisitionType":"starter"},
  "wf037": {"status":"lifestyle","theme":"casual","collection":null,"family":"Fleece slippers","acquisitionType":"starter"},
  "wf040": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slip ons","acquisitionType":"runs"},
  "wf041": {"status":"lifestyle","theme":"casual","collection":null,"family":"Rain boots","acquisitionType":"starter"},
  "wf043": {"status":"lifestyle","theme":"casual","collection":null,"family":"Mary Janes","acquisitionType":"starter"},
  "wf044": {"status":"vault","theme":"casual","collection":null,"family":"Strap sneakers","acquisitionType":"battlepass"},
  "wf045": {"status":"lifestyle","theme":"casual","collection":null,"family":"Espadrilles","acquisitionType":"runs"},
  "wf046": {"status":"core","theme":"trail","collection":null,"family":"Work boots","acquisitionType":"starter"},
  "wf047": {"status":"lifestyle","theme":"casual","collection":null,"family":"Court sneakers","acquisitionType":"starter"},
  "wf048": {"status":"lifestyle","theme":"casual","collection":null,"family":"Moccasins","acquisitionType":"starter"},
  "wf049": {"status":"lifestyle","theme":"casual","collection":null,"family":"Sneakers","acquisitionType":"starter"},
  "wf050": {"status":"lifestyle","theme":"casual","collection":null,"family":"Clogs","acquisitionType":"runs"},
  "wf051": {"status":"core","theme":"running","collection":null,"family":"Sport sandals","acquisitionType":"starter"},
  "wf052": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chelsea boots","acquisitionType":"starter"},
  "wf053": {"status":"lifestyle","theme":"casual","collection":null,"family":"Duck boots","acquisitionType":"starter"},
  "wf054": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slip ons","acquisitionType":"starter"},
  "wf055": {"status":"lifestyle","theme":"casual","collection":null,"family":"Mary Janes","acquisitionType":"distance"},
  "wf060": {"status":"lifestyle","theme":"casual","collection":null,"family":"Canvas high tops","acquisitionType":"runs"},
  "wf061": {"status":"lifestyle","theme":"casual","collection":null,"family":"Boat shoes","acquisitionType":"starter"},
  "wf063": {"status":"lifestyle","theme":"casual","collection":null,"family":"Loafers","acquisitionType":"starter"},
  "wf064": {"status":"core","theme":"running","collection":null,"family":"Mesh runners","acquisitionType":"starter"},
  "wf070": {"status":"lifestyle","theme":"casual","collection":null,"family":"Strap shoes","acquisitionType":"runs"},
  "wf071": {"status":"lifestyle","theme":"casual","collection":null,"family":"Skate shoes","acquisitionType":"starter"},
  "wf076": {"status":"lifestyle","theme":"casual","collection":null,"family":"Tassel loafers","acquisitionType":"starter"},
  "wf078": {"status":"core","theme":"trail","collection":null,"family":"Work boots","acquisitionType":"starter"},
  "wf079": {"status":"lifestyle","theme":"casual","collection":null,"family":"Fluffy slippers","acquisitionType":"starter"},
  "wf081": {"status":"lifestyle","theme":"casual","collection":null,"family":"Ballet flats","acquisitionType":"starter"},
  "wf083": {"status":"lifestyle","theme":"casual","collection":null,"family":"Chelsea boots","acquisitionType":"starter"},
  "wf084": {"status":"core","theme":"trail","collection":null,"family":"Trail runners","acquisitionType":"starter"},
  "wf085": {"status":"lifestyle","theme":"casual","collection":null,"family":"Strap heels","acquisitionType":"runs"},
  "wf086": {"status":"lifestyle","theme":"casual","collection":null,"family":"Slides","acquisitionType":"starter"},
  "whoa": {"status":"vault","theme":"casual","collection":null,"family":null,"acquisitionType":"battlepass"},
  "wideband": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "windbreaker": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"distance"},
  "wink": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"runs"},
  "witchhat": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "wizardhat": {"status":"lifestyle","theme":"fantasy","collection":null,"family":null,"acquisitionType":"level"},
  "wolfears": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "worried": {"status":"lifestyle","theme":"casual","collection":null,"family":null,"acquisitionType":"starter"},
  "lightweightracecap": {"status":"core","theme":"running","collection":"runner_essentials","family":"running_cap","acquisitionType":"starter"},
  "reflectivenightcap": {"status":"core","theme":"running","collection":"marina_after_dark","family":"running_cap","acquisitionType":"starter"},
  "trailsuncap": {"status":"core","theme":"trail","collection":"trail","family":"running_cap","acquisitionType":"starter"},
  "cur_technicalracecap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_reflectivenightcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_sunprotectionrunningcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_wizardhat": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_dragonhorns": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_piratehat": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_knighthelmet": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_astronauthelmet": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_shinobiheadband": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_catears": {"status":"core","theme":"fantasy","collection":null,"family":null,"acquisitionType":null},
  "cur_foxears": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_bunnyears": {"status":"core","theme":"fantasy","collection":null,"family":null,"acquisitionType":null},
  "cur_devilhorns": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_sweatband": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_performanceheadband": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_runclubcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_flowercrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"event"},
  "cur_tropicalstrawhat": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_beret": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_sailorcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_tiara": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cowboyhat": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_royalcrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cyclingcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_nightstripecap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_desertflapcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_racingvisor": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_trailflapcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_buckethat": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_truckercap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_knitbeanie": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_tealbrimcap": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_snapback": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_halo": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cybervisorcap": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_glowingracecap": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_championlaurels": {"status":"core","theme":"fantasy","collection":null,"family":null,"acquisitionType":null},
  "cur_festivalheadpiece": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_championcrown": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cloudhalo": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_neonantennaheadband": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_runningwaistpouch": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_wearableracebib": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_phonearmband": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_coolingnecktowel": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_nightrunninglightharness": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_runclubcrossbodybag": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_hydrationracevest": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_neckgaiter": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_goldmedal": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_trophychain": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_raceharness": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_dogtags": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_pearlstrand": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_charmchain": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_necktie": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_neckerchief": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_bowtie": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_waterproofphonepouch": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_electrolyterunningbelt": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_runclublanyard": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_reflectiveracesash": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_luckycharmpendant": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_finishlinewreathnecklace": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_marathonfinishersash": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_neonclubbadge": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_angelwings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_neonwings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_dragonwings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_fairywings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_phoenixwings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_wateraura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_holographicwings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_twinblades": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_lightningaura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_flameaura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_leafaura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"event"},
  "cur_staraura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cloudaura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_neonorbitrings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_pixelglitchaura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_heartorbit": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_spiritflameorbs": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_championlaurelglow": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_runclubhologrambadge": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_floatingminitrophy": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_prismatichalo": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_energyshoulderflares": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_speedenergyrings": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_victoryconfettiaura": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"event"},
  "cur_wraparoundperformancesunglasses": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_clearnightrunningglasses": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_adaptiveperformancesunglasses": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_wayfarers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_roundframes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_oversizedfashionframes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_clearsportshield": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_mirroredsportshield": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cybervisor": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_snowskivisor": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_heartglasses": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_starglasses": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_pixelglasses": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_halffacemask": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_shinobifacemask": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_festivalmask": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_reflectivefaceshield": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_dragonmask": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_lightweightrainshell": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_tropicalstormponcho": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_tropicalcampshirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_creamstripedknit": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_sleevelesshoodie": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_teamjersey": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_cyclingjersey": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_utilityvest": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_singaporeracesinglet": {"status":"vault","theme":"singapore","collection":null,"family":null,"acquisitionType":"event"},
  "cur_windbreaker": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_varsityjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_aurorajacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_dragonteamjersey": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"event"},
  "cur_seabreezewindshirt": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_championvarsityjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_shadowrunnertop": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_holographicshell": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_lightningracesuit": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_heritagerunnerjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_lunarrunnerjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_sunrisemarathonsinglet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_regionalchampionshipsinglet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_sailorblouse": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_puffsleevecroptop": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackfootballjersey": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackpuffervest": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_pastelcardigan": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_cloudpufferjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_blacksleevelesshoodie": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_bowcamisole": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_frillyhearttop": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_tacticalrig": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_cyberrunnerjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_neongridshell": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_midnightreflectivehoodie": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_goldracedaysinglet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cityrunclubjacket": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_trailexpeditionvest": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_lilachalfzip": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_whitestripepolo": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_blushcropjacket": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_stormparka": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_judogi": {"status":"core","theme":"fantasy","collection":null,"family":null,"acquisitionType":null},
  "cur_knightarmour": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_starlitmagerobes": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_shinobigi": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_astronautsuit": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_runclubtechnicalshirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_runclubracesinglet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_trailsleevelesstop": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_hotweathermeshtee": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_everydaytechnicaltee": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_greeneverydayrunningshirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_darkreflectivetechnicaltee": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_coastalsunrisesinglet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_competitivetracksinglet": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_bretonstripetee": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackbomberjacket": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_sherpadenimjacket": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_oatmealcardigan": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_labcoat": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_whitecroppedcami": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_pinkcroptee": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_midnightpullover": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_pastelrugbyshirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_layeredpuffervest": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_piratecoat": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_leaffairydress": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_valkyriearmour": {"status":"vault","theme":"fantasy","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_olivecargoshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_camocargoshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_creamcargoshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_denimskirt": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_sagetennisskirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_reflectivenighttights": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_greenginghamskirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_trailexpeditiontrousers": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_runclubraceshorts": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_goldmarathonsplitshorts": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_waterproofrunningtrousers": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_cybergridtights": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_shadowrunnerpants": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_festivalrunningskort": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_championraceshorts": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_fulllengthtechnicaltights": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_trailrunningshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_runningskort": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_modestrunningtrousers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_competitivesplitshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_everydaytrainingshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_layeredcompressionshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_kneelengthperformancetights": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_greysweatshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_redrunningshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blacktrackjoggers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_whitestraighttrousers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_creammidiskirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackbasicshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackdolphinshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackleggings": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackbikeshorts": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_whitepleatedskirt": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_coralskort": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_everydaycushionedroadshoes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_maxcushionlongrunshoes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_lightweightspeedtrainers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_highstackracedayshoes": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_trailrunningshoes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_wetweatherroadshoes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_reflectivenightrunners": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"battlepass"},
  "cur_recoverysandals": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_cleanwhitesneakers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_blackknitrunners": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_classichightops": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_courtsneakers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_loafers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_chelseaboots": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_trailboots": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_hikingsandals": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_slides": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_maryjanes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_balletflats": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_dressshoes": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_carbongoldracers": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_auroraracers": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_neonpulserunners": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_cloudfoamrunners": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_stealthnightshoes": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_lavatrailshoes": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_frosttrailshoes": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"lootbox"},
  "cur_wingedspeedshoes": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_regionaleventrunners": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"event"},
  "cur_championtrackspikes": {"status":"vault","theme":"running","collection":null,"family":null,"acquisitionType":"pro"},
  "cur_blushchunkytrainers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
  "cur_tealdailytrainers": {"status":"core","theme":"running","collection":null,"family":null,"acquisitionType":null},
};

export default COSMETIC_CURATION;
