// GENERATED — outfit art cut from the full-body renders (scripts/cut.py).
//
// Each render is one worn outfit on the shared headless body, so every piece
// here was measured in place: `layout` puts it back exactly where it sat on
// that body, mapped onto the rig (collar y=203, waist y=355, sole y=635 of the
// 248x640 frame). Nothing is eyeballed.
//
// Outfits that are one continuous garment — robes, cloaks, armour, jumpsuits —
// could not be cut at a waist seam, so they ship whole in `suits` as
// `fit: 'onepiece'` items that hide the bottom slot.
//
// Colours are baked (no 10-swatch recolour), matching the wave-2/3 convention.
//
// NAMES are hand-written, not generated: the cutter numbered pieces off their
// source render ("White top 7"), which described the file rather than the
// garment and was wrong as often as not — several "white" pieces are green,
// black or sand. Every garment carries `family` (what it is) and `colorway`
// (what colour this one is), and `label` is the name a player reads, said
// the way a person would say it, colour first ("Lilac Mary Janes"), and
// written off the ART. The last generated form was "Shoes, Lilac 2" with a
// mid dot for the comma, and it named nothing, so every piece was renamed
// by looking at it (2026-09-15). No separator, no number, no dash: the
// reward reveal prints this name as its headline, and
// __tests__/catalogNames.test.js holds those rules. Pieces sharing a
// `family` are the same garment in another colour. The one piece costumes
// are unique, so they carry a plain `label` and no colorway. If the cutter
// is ever re-run, it must not overwrite these three fields.

const free = null;
const passOnly = { pass: true, label: 'Free pass reward' };
// PASER PRO exclusive — no stat route at all; the only way in is a pass tier
// granting a server-side unlock (PREMIUM_ITEMS in backend/app/progression.py).
const premiumOnly = { premium: true, label: 'PASER PRO reward' };
const runs = (n, label) => ({ stat: 'runs_count', value: n, label });
const dist = (km, label) => ({ stat: 'career_distance_m', value: km * 1000, label });


export const OUTFIT_TOPS = [
  { id: 'o0t', label: 'Navy zip jacket', family: 'Zip jacket', colorway: 'Navy', img: require('../../assets/character/outfit/ofT1.png'), layout: { w: 1.05, top: 0.2952, dx: 0.0167 }, rarity: 'common', unlock: free },
  { id: 'o1t', label: 'Red basketball vest', family: 'Basketball vest', colorway: 'Red', img: require('../../assets/character/outfit/ofT2.png'), layout: { w: 0.9285, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'o2t', label: 'Forest green polo', family: 'Polo', colorway: 'Forest green', img: require('../../assets/character/outfit/ofT3.png'), layout: { w: 1.0063, top: 0.3043, dx: 0.015 }, rarity: 'common', unlock: free },
  { id: 'o3t', label: 'Yellow zip hoodie', family: 'Zip hoodie', colorway: 'Yellow', img: require('../../assets/character/outfit/ofT4.png'), layout: { w: 1.0341, top: 0.294, dx: 0.01 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o4t', label: 'Black crew tee', family: 'Crew tee', colorway: 'Black', img: require('../../assets/character/outfit/ofT5.png'), layout: { w: 1.0316, top: 0.3172, dx: 0.01 }, rarity: 'epic', unlock: passOnly },
  { id: 'o6t', label: 'White crop polo', family: 'Crop polo', colorway: 'White', img: require('../../assets/character/outfit/ofT7.png'), layout: { w: 0.9822, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'o9t', label: 'Sea glass tee', family: 'Loose tee', colorway: 'Sea glass', img: require('../../assets/character/outfit/ofT10.png'), layout: { w: 0.9299, top: 0.3094, dx: 0.0017 }, rarity: 'epic', unlock: dist(25, 'Run 25 km total') },
  { id: 'o10t', label: 'Red zip hoodie', family: 'Zip hoodie', colorway: 'Red', img: require('../../assets/character/outfit/ofT11.png'), layout: { w: 1.0034, top: 0.3013, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'o12t', label: 'Cobalt tank top', family: 'Tank top', colorway: 'Cobalt', img: require('../../assets/character/outfit/ofT13.png'), layout: { w: 1.0288, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'o13t', label: 'Yellow ringer tee', family: 'Ringer tee', colorway: 'Yellow', img: require('../../assets/character/outfit/ofT14.png'), layout: { w: 0.9536, top: 0.3172 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o14t', label: 'Black loose tee', family: 'Loose tee', colorway: 'Black', img: require('../../assets/character/outfit/ofT15.png'), layout: { w: 0.9381, top: 0.3172 }, rarity: 'epic', unlock: dist(10, 'Run 10 km total') },
  { id: 'o16t', label: 'White polo', family: 'Polo', colorway: 'White', img: require('../../assets/character/outfit/ofT17.png'), layout: { w: 0.9822, top: 0.3048, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'o18t', label: 'Mint loose tee', family: 'Loose tee', colorway: 'Mint', img: require('../../assets/character/outfit/ofT19.png'), layout: { w: 0.9587, top: 0.3133, dx: 0.0133 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o30t', label: 'Sky blue zip hoodie', family: 'Zip hoodie', colorway: 'Sky blue', img: require('../../assets/character/outfit/ofT21.png'), layout: { w: 0.9834, top: 0.2916, dx: 0.0133 }, rarity: 'common', unlock: free },
  { id: 'o31t', label: 'Orange tank top', family: 'Tank top', colorway: 'Orange', img: require('../../assets/character/outfit/ofT22.png'), layout: { w: 1.0133, top: 0.3249, dx: 0.0117 }, rarity: 'common', unlock: free },
  { id: 'o36t', label: 'Coral track jacket', family: 'Track jacket', colorway: 'Coral', img: require('../../assets/character/outfit/ofT27.png'), layout: { w: 1.7133, top: -0.0134, dx: 0.3443 }, rarity: 'common', unlock: free },
  { id: 'o40t', label: 'Orange layered vest', family: 'Layered vest', colorway: 'Orange', img: require('../../assets/character/outfit/ofT31.png'), layout: { w: 0.9787, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'o41t', label: 'Sand camp shirt', family: 'Camp shirt', colorway: 'Sand', img: require('../../assets/character/outfit/ofT32.png'), layout: { w: 0.925, top: 0.3098, dx: 0.01 }, rarity: 'common', unlock: free },
  { id: 'o45t', label: 'Coral stripe jacket', family: 'Stripe jacket', colorway: 'Coral', img: require('../../assets/character/outfit/ofT36.png'), layout: { w: 1.0152, top: 0.2914, dx: 0.0067 }, rarity: 'common', unlock: free },
  { id: 'o48t', label: 'Lilac polo', family: 'Polo', colorway: 'Lilac', img: require('../../assets/character/outfit/ofT39.png'), layout: { w: 1.0424, top: 0.3095, dx: 0.0117 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o49t', label: 'Red varsity jacket', family: 'Varsity jacket', colorway: 'Red', img: require('../../assets/character/outfit/ofT40.png'), layout: { w: 0.9932, top: 0.2933, dx: 0.0167 }, rarity: 'epic', unlock: passOnly },
  { id: 'o50t', label: 'Teal track jacket', family: 'Track jacket', colorway: 'Teal', img: require('../../assets/character/outfit/ofT41.png'), layout: { w: 0.9972, top: 0.2775, dx: 0.0117 }, rarity: 'common', unlock: free },
  { id: 'o54t', label: 'Blush shrug', family: 'Shrug', colorway: 'Blush', img: require('../../assets/character/outfit/ofT44.png'), layout: { w: 0.9686, top: 0.3147, dx: 0.0067 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o56t', label: 'Mint sports bra', family: 'Sports bra', colorway: 'Mint', img: require('../../assets/character/outfit/ofT46.png'), layout: { w: 1.2793, top: 0.3327, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'o57t', label: 'White racer jacket', family: 'Racer jacket', colorway: 'White', img: require('../../assets/character/outfit/ofT47.png'), layout: { w: 0.9876, top: 0.2955, dx: 0.0083 }, rarity: 'common', unlock: free },
  { id: 'o68t', label: 'Black hoodie', family: 'Pullover hoodie', colorway: 'Black', img: require('../../assets/character/outfit/ofT50.png'), layout: { w: 1.0035, top: 0.2734, dx: 0.005 }, rarity: 'rare', unlock: runs(3, 'Finish 3 runs') },
  { id: 'o70t', label: 'Olive flannel shirt', family: 'Flannel shirt', colorway: 'Olive', img: require('../../assets/character/outfit/ofT51.png'), layout: { w: 0.9755, top: 0.3043, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'o71t', label: 'Black puffer vest', family: 'Puffer vest', colorway: 'Black', img: require('../../assets/character/outfit/ofT52.png'), layout: { w: 0.9603, top: 0.2681, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'o72t', label: 'Blush heart cardigan', family: 'Heart cardigan', colorway: 'Blush', img: require('../../assets/character/outfit/ofT53.png'), layout: { w: 1.0518, top: 0.2939, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'o78t', label: 'Jet black hoodie', family: 'Pullover hoodie', colorway: 'Jet black', img: require('../../assets/character/outfit/ofT59.png'), layout: { w: 0.9781, top: 0.2875, dx: 0.0033 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o82t', label: 'Blush button cardigan', family: 'Button cardigan', colorway: 'Blush', img: require('../../assets/character/outfit/ofT62.png'), layout: { w: 1.0501, top: 0.3056, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'o87t', label: 'Navy shirt jacket', family: 'Shirt jacket', colorway: 'Navy', img: require('../../assets/character/outfit/ofT67.png'), layout: { w: 0.9948, top: 0.3094, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'o88t', label: 'Ash hooded puffer', family: 'Hooded puffer', colorway: 'Ash', img: require('../../assets/character/outfit/ofT68.png'), layout: { w: 0.9699, top: 0.263, dx: 0.0033 }, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
  { id: 'o89t', label: 'Green bomber jacket', family: 'Bomber jacket', colorway: 'Green', img: require('../../assets/character/outfit/ofT69.png'), layout: { w: 0.9911, top: 0.2875, dx: 0.01 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o90t', label: 'Grey blazer', family: 'Blazer', colorway: 'Grey', img: require('../../assets/character/outfit/ofT70.png'), layout: { w: 0.9662, top: 0.3107, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'o91t', label: 'Tan trucker jacket', family: 'Trucker jacket', colorway: 'Tan', img: require('../../assets/character/outfit/ofT71.png'), layout: { w: 0.9568, top: 0.3107, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'o92t', label: 'Cream long cardigan', family: 'Long cardigan', colorway: 'Cream', img: require('../../assets/character/outfit/ofT72.png'), layout: { w: 0.9815, top: 0.3249, dx: 0.0133 }, rarity: 'common', unlock: free },
  { id: 'o93t', label: 'Navy blazer', family: 'Blazer', colorway: 'Navy', img: require('../../assets/character/outfit/ofT73.png'), layout: { w: 1.0032, top: 0.3223, dx: 0.005 }, rarity: 'rare', unlock: runs(10, 'Finish 10 runs') },
  { id: 'o94t', label: 'Cream striped knit', family: 'Striped knit', colorway: 'Cream', img: require('../../assets/character/outfit/ofT74.png'), layout: { w: 1.0256, top: 0.3249, dx: 0.0083 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'o95t', label: 'Mauve zip hoodie', family: 'Zip hoodie', colorway: 'Mauve', img: require('../../assets/character/outfit/ofT75.png'), layout: { w: 0.9958, top: 0.2914, dx: 0.005 }, rarity: 'common', unlock: free },
  // --- wave 5 (2026-08-07) --- drawn alone rather than on a body, so
  // these layouts are a category guess, not a measurement. Adjust them
  // in Fit Studio (`npm run fit`), not by hand.
  { id: 'k1t', label: 'White running vest', family: 'Running vest', colorway: 'White', img: require('../../assets/character/outfit/ofT101.png'), layout: { w: 0.61, top: 0.3328, dx: -0.0017 }, rarity: 'common', unlock: free },
  { id: 'k2t', label: 'Black boxy tee', family: 'Boxy tee', colorway: 'Black', img: require('../../assets/character/outfit/ofT102.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'k3t', label: 'Charcoal zip hoodie', family: 'Zip hoodie', colorway: 'Charcoal', img: require('../../assets/character/outfit/ofT103.png'), layout: { w: 1.05, top: 0.298 }, rarity: 'common', unlock: free },
  { id: 'k4t', label: 'Black raglan tee', family: 'Raglan tee', colorway: 'Black', img: require('../../assets/character/outfit/ofT104.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'k5t', label: 'Pink crop tee', family: 'Crop tee', colorway: 'Pink', img: require('../../assets/character/outfit/ofT105.png'), layout: { w: 0.98, top: 0.3198, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'k6t', label: 'Blue track hoodie', family: 'Track hoodie', colorway: 'Blue', img: require('../../assets/character/outfit/ofT106.png'), layout: { w: 1.05, top: 0.298 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'k7t', label: 'Teal zip gilet', family: 'Zip gilet', colorway: 'Teal', img: require('../../assets/character/outfit/ofT107.png'), layout: { w: 0.6433, top: 0.2804, dx: 0.0183 }, rarity: 'epic', unlock: premiumOnly },
  { id: 'k8t', label: 'Lilac half zip', family: 'Half zip', colorway: 'Lilac', img: require('../../assets/character/outfit/ofT108.png'), layout: { w: 1.05, top: 0.2868, dx: -0.0017 }, rarity: 'common', unlock: free },
  { id: 'k9t', label: 'Blush block hoodie', family: 'Block hoodie', colorway: 'Blush', img: require('../../assets/character/outfit/ofT109.png'), layout: { w: 1.05, top: 0.2735, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'k10t', label: 'Navy varsity jacket', family: 'Varsity jacket', colorway: 'Navy', img: require('../../assets/character/outfit/ofT110.png'), layout: { w: 1.05, top: 0.298 }, rarity: 'legendary', unlock: premiumOnly },
  { id: 'k11t', label: 'White stripe polo', family: 'Stripe polo', colorway: 'White', img: require('../../assets/character/outfit/ofT111.png'), layout: { w: 1.02, top: 0.31 }, rarity: 'common', unlock: free },
  { id: 'k12t', label: 'Blush crop jacket', family: 'Crop jacket', colorway: 'Blush', img: require('../../assets/character/outfit/ofT112.png'), layout: { w: 1, top: 0.2882, dx: 0.0033 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'k13t', label: 'Lilac rugby shirt', family: 'Rugby shirt', colorway: 'Lilac', img: require('../../assets/character/outfit/ofT113.png'), layout: { w: 1.02, top: 0.2945, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'k14t', label: 'Grey crop puffer', family: 'Crop puffer', colorway: 'Grey', img: require('../../assets/character/outfit/ofT114.png'), layout: { w: 1.0, top: 0.305 }, rarity: 'common', unlock: free },
  { id: 'k15t', label: 'Slate pocket hoodie', family: 'Pocket hoodie', colorway: 'Slate', img: require('../../assets/character/outfit/ofT115.png'), layout: { w: 1.05, top: 0.2696, dx: 0.0067 }, rarity: 'common', unlock: free },
  // --- PASER running cosmetics (2026-09-17) ---
  { id: 'eastcoastsunrisesinglet', label: 'East Coast Sunrise Singlet', family: 'Running vest', colorway: 'Sunrise', img: require('../../assets/character/_src/outfit/ofT112.png'), layout: { w: 0.61, top: 0.3328, dx: -0.0017 }, rarity: 'rare', unlock: free },
  { id: 'marinanighttee', label: 'Marina Night Reflective Tee', family: 'Reflective tee', colorway: 'Marina night', img: require('../../assets/character/_src/outfit/ofT113.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'epic', unlock: free },
  { id: 'parkconnectortee', label: 'Park Connector Tech Tee', family: 'Tech tee', colorway: 'Park connector', img: require('../../assets/character/_src/outfit/ofT114.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'rare', unlock: free },
  { id: 'kallangtracksinglet', label: 'Kallang Track Singlet', family: 'Track singlet', colorway: 'Kallang', img: require('../../assets/character/_src/outfit/ofT115.png'), layout: { w: 0.61, top: 0.3328, dx: -0.0017 }, rarity: 'rare', unlock: free },
  { id: 'monsoonshell', label: 'Monsoon Running Shell', family: 'Running shell', colorway: 'Monsoon', img: require('../../assets/character/_src/outfit/ofT116.png'), layout: { w: 1.05, top: 0.298 }, rarity: 'rare', unlock: free },
  { id: 'humiditymeshtee', label: 'Humidity Mesh Tee', family: 'Mesh tee', colorway: 'Humidity', img: require('../../assets/character/_src/outfit/ofT117.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'clubtrainingtee', label: 'Club Training Tee', family: 'Training tee', colorway: 'Club', img: require('../../assets/character/_src/outfit/ofT118.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'clubracesinglet', label: 'Club Race Singlet', family: 'Race singlet', colorway: 'Club', img: require('../../assets/character/_src/outfit/ofT119.png'), layout: { w: 0.61, top: 0.3328, dx: -0.0017 }, rarity: 'rare', unlock: free },
  { id: 'trailsleevelesstop', label: 'Trail Sleeveless Top', family: 'Sleeveless top', colorway: 'Trail', img: require('../../assets/character/_src/outfit/ofT120.png'), layout: { w: 1.0, top: 0.3172 }, rarity: 'common', unlock: free },
  { id: 'nationaldaysinglet', label: 'National Day Race Singlet', family: 'Race singlet', colorway: 'National day', img: require('../../assets/character/_src/outfit/ofT121.png'), layout: { w: 0.61, top: 0.3328, dx: -0.0017 }, rarity: 'epic', unlock: free },
];

export const OUTFIT_BOTTOMS = [
  // --- wave 5 (2026-08-07) --- drawn alone rather than on a body, so
  // these layouts are a category guess, not a measurement. Adjust them
  // in Fit Studio (`npm run fit`), not by hand.
  // --- wave 6 (2026-08-09) --- refills the slots emptied on 08-08.
  // Names and layouts are both generated; see scripts/install-wardrobe-6.py.
  { id: 'wb001', label: 'Teal sweat shorts', family: 'Sweat shorts', colorway: 'Teal', img: require('../../assets/character/outfit/ofB301.png'), layout: { w: 1.08, top: 0.4152, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb002', label: 'Scarlet gym shorts', family: 'Gym shorts', colorway: 'Scarlet', img: require('../../assets/character/outfit/ofB302.png'), layout: { w: 1.13, top: 0.4074, dx: -0.005 }, rarity: 'common', unlock: free },
  { id: 'wb003', label: 'Blue cuffed shorts', family: 'Cuffed shorts', colorway: 'Blue', img: require('../../assets/character/outfit/ofB303.png'), layout: { w: 1.0467, top: 0.4551, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb004', label: 'Olive cargo shorts', family: 'Cargo shorts', colorway: 'Olive', img: require('../../assets/character/outfit/ofB304.png'), layout: { w: 1.13, top: 0.445, dx: -0.005 }, rarity: 'common', unlock: free },
  { id: 'wb009', label: 'Navy trousers', family: 'Trousers', colorway: 'Navy', img: require('../../assets/character/outfit/ofB309.png'), layout: { w: 1.22, top: 0.4441, dx: 0.0067 }, rarity: 'common', unlock: free },
  { id: 'wb012', label: 'Black track shorts', family: 'Track shorts', colorway: 'Black', img: require('../../assets/character/outfit/ofB312.png'), layout: { w: 1.11, top: 0.4072, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'wb013', label: 'Purple pleated skirt', family: 'Pleated skirt', colorway: 'Purple', img: require('../../assets/character/outfit/ofB313.png'), layout: { w: 1.2867, top: 0.317, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb014', label: 'Camo cargo shorts', family: 'Cargo shorts', colorway: 'Camo', img: require('../../assets/character/outfit/ofB314.png'), layout: { w: 1.0767, top: 0.424, dx: -0.0083 }, rarity: 'common', unlock: free },
  { id: 'wb017', label: 'Aqua swim shorts', family: 'Swim shorts', colorway: 'Aqua', img: require('../../assets/character/outfit/ofB317.png'), layout: { w: 0.9133, top: 0.4801, dx: -0.0067 }, rarity: 'common', unlock: free },
  { id: 'wb018', label: 'Lilac bike shorts', family: 'Bike shorts', colorway: 'Lilac', img: require('../../assets/character/outfit/ofB318.png'), layout: { w: 1.2, top: 0.3733 }, rarity: 'common', unlock: free },
  { id: 'wb019', label: 'Black pinstripe trousers', family: 'Pinstripe trousers', colorway: 'Black', img: require('../../assets/character/outfit/ofB319.png'), layout: { w: 1.42, top: 0.3692 }, rarity: 'common', unlock: free },
  { id: 'wb021', label: 'Brown cargo shorts', family: 'Cargo shorts', colorway: 'Brown', img: require('../../assets/character/outfit/ofB321.png'), layout: { w: 1.2333, top: 0.3315, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb024', label: 'Sand pleated shorts', family: 'Pleated shorts', colorway: 'Sand', img: require('../../assets/character/outfit/ofB324.png'), layout: { w: 1.07, top: 0.4175, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb025', label: 'Red running shorts', family: 'Running shorts', colorway: 'Red', img: require('../../assets/character/outfit/ofB325.png'), layout: { w: 1.1, top: 0.36 }, rarity: 'rare', unlock: passOnly },
  { id: 'wb026', label: 'Blue denim shorts', family: 'Denim shorts', colorway: 'Blue', img: require('../../assets/character/outfit/ofB326.png'), layout: { w: 1.3667, top: 0.4066 }, rarity: 'common', unlock: free },
  { id: 'wb027', label: 'Forest cargo shorts', family: 'Cargo shorts', colorway: 'Forest', img: require('../../assets/character/outfit/ofB327.png'), layout: { w: 1.1133, top: 0.4779 }, rarity: 'common', unlock: free },
  { id: 'wb031', label: 'Green gingham skirt', family: 'Gingham skirt', colorway: 'Green', img: require('../../assets/character/outfit/ofB331.png'), layout: { w: 1.4633, top: 0.2855, dx: -0.0083 }, rarity: 'common', unlock: free },
  { id: 'wb032', label: 'Denim knee shorts', family: 'Knee shorts', colorway: 'Denim', img: require('../../assets/character/outfit/ofB332.png'), layout: { w: 1.32, top: 0.3734, dx: -0.0067 }, rarity: 'common', unlock: free },
  { id: 'wb036', label: 'Red track shorts', family: 'Track shorts', colorway: 'Red', img: require('../../assets/character/outfit/ofB336.png'), layout: { w: 1.0133, top: 0.4788, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb043', label: 'Jade drawstring shorts', family: 'Drawstring shorts', colorway: 'Jade', img: require('../../assets/character/outfit/ofB343.png'), layout: { w: 1.19, top: 0.3877, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'wb047', label: 'Grey sweat shorts', family: 'Sweat shorts', colorway: 'Grey', img: require('../../assets/character/outfit/ofB347.png'), layout: { w: 1.1667, top: 0.4006, dx: -0.0067 }, rarity: 'common', unlock: free },
  { id: 'wb048', label: 'Orange running shorts', family: 'Running shorts', colorway: 'Orange', img: require('../../assets/character/outfit/ofB348.png'), layout: { w: 1.11, top: 0.4016, dx: -0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb050', label: 'Light denim shorts', family: 'Denim shorts', colorway: 'Light denim', img: require('../../assets/character/outfit/ofB350.png'), layout: { w: 1.0767, top: 0.4314, dx: 0.0017 }, rarity: 'rare', unlock: passOnly },
  { id: 'wb052', label: 'Black bike shorts', family: 'Bike shorts', colorway: 'Black', img: require('../../assets/character/outfit/ofB352.png'), layout: { w: 1.3367, top: 0.3137, dx: -0.005 }, rarity: 'common', unlock: free },
  { id: 'wb054', label: 'Navy pinstripe shorts', family: 'Pinstripe shorts', colorway: 'Navy', img: require('../../assets/character/outfit/ofB354.png'), layout: { w: 1.08, top: 0.4095 }, rarity: 'common', unlock: free },
  { id: 'wb056', label: 'Checkered shorts', family: 'Drawstring shorts', colorway: 'Checkered', img: require('../../assets/character/outfit/ofB356.png'), layout: { w: 1.2133, top: 0.3807 }, rarity: 'common', unlock: free },
  { id: 'wb061', label: 'Orange corduroy shorts', family: 'Corduroy shorts', colorway: 'Orange', img: require('../../assets/character/outfit/ofB361.png'), layout: { w: 1.1867, top: 0.4104, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb062', label: 'Charcoal bike shorts', family: 'Bike shorts', colorway: 'Charcoal', img: require('../../assets/character/outfit/ofB362.png'), layout: { w: 1.4567, top: 0.2572, dx: -0.005 }, rarity: 'common', unlock: free },
  { id: 'wb065', label: 'Yellow cargo shorts', family: 'Cargo shorts', colorway: 'Yellow', img: require('../../assets/character/outfit/ofB365.png'), layout: { w: 1.1867, top: 0.3821, dx: 0.0033 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wb068', label: 'Brown corduroy shorts', family: 'Corduroy shorts', colorway: 'Brown', img: require('../../assets/character/outfit/ofB368.png'), layout: { w: 1.3167, top: 0.3501, dx: -0.005 }, rarity: 'common', unlock: free },
  { id: 'wb071', label: 'Pink plaid shorts', family: 'Plaid shorts', colorway: 'Pink', img: require('../../assets/character/outfit/ofB371.png'), layout: { w: 1.1867, top: 0.3543, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb072', label: 'Black compression shorts', family: 'Compression shorts', colorway: 'Black', img: require('../../assets/character/outfit/ofB372.png'), layout: { w: 1.2, top: 0.3338, dx: 0.0067 }, rarity: 'common', unlock: free },
  { id: 'wb073', label: 'Sage tennis skirt', family: 'Tennis skirt', colorway: 'Sage', img: require('../../assets/character/outfit/ofB373.png'), layout: { w: 1.1367, top: 0.4096, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb083', label: 'Coral skort', family: 'Skort', colorway: 'Coral', img: require('../../assets/character/outfit/ofB383.png'), layout: { w: 1.1633, top: 0.3823, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb084', label: 'Khaki cargo shorts', family: 'Cargo shorts', colorway: 'Khaki', img: require('../../assets/character/outfit/ofB384.png'), layout: { w: 1.0433, top: 0.4536, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb086', label: 'Neon stripe bike shorts', family: 'Bike shorts', colorway: 'Black and neon', img: require('../../assets/character/outfit/ofB386.png'), layout: { w: 1.1867, top: 0.3473 }, rarity: 'common', unlock: free },
  { id: 'wb092', label: 'Maroon cargo trousers', family: 'Cargo trousers', colorway: 'Maroon', img: require('../../assets/character/outfit/ofB392.png'), layout: { w: 0.9833, top: 0.5123, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb093', label: 'Stone cargo shorts', family: 'Cargo shorts', colorway: 'Stone', img: require('../../assets/character/outfit/ofB393.png'), layout: { w: 1.3367, top: 0.3807, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb094', label: 'Cream cargo shorts', family: 'Cargo shorts', colorway: 'Cream', img: require('../../assets/character/outfit/ofB394.png'), layout: { w: 1.12, top: 0.3859, dx: -0.0067 }, rarity: 'common', unlock: free },
  { id: 'wb097', label: 'Lilac plaid shorts', family: 'Plaid shorts', colorway: 'Lilac', img: require('../../assets/character/outfit/ofB397.png'), layout: { w: 1.0667, top: 0.4408 }, rarity: 'common', unlock: free },
  { id: 'wb102', label: 'Cropped jeans', family: 'Cropped jeans', colorway: 'Denim', img: require('../../assets/character/outfit/ofB402.png'), layout: { w: 1.1967, top: 0.4436, dx: 0.0083 }, rarity: 'common', unlock: free },
  { id: 'wb103', label: 'Teal cargo shorts', family: 'Cargo shorts', colorway: 'Teal', img: require('../../assets/character/outfit/ofB403.png'), layout: { w: 1.2, top: 0.443, dx: 0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb105', label: 'Sand chinos', family: 'Chinos', colorway: 'Sand', img: require('../../assets/character/outfit/ofB405.png'), layout: { w: 1.25, top: 0.3993, dx: -0.0017 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wb106', label: 'Teal leggings', family: 'Leggings', colorway: 'Teal', img: require('../../assets/character/outfit/ofB406.png'), layout: { w: 1.2333, top: 0.4212, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'wb107', label: 'Slate pleated skirt', family: 'Pleated skirt', colorway: 'Slate', img: require('../../assets/character/outfit/ofB407.png'), layout: { w: 1.17, top: 0.3826, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb108', label: 'Denim skirt', family: 'Skirt', colorway: 'Denim', img: require('../../assets/character/outfit/ofB408.png'), layout: { w: 1.09, top: 0.4342, dx: -0.005 }, rarity: 'common', unlock: free },
  { id: 'wb109', label: 'Teal chino shorts', family: 'Chino shorts', colorway: 'Teal', img: require('../../assets/character/outfit/ofB409.png'), layout: { w: 1.19, top: 0.3949, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wb110', label: 'Charcoal race shorts', family: 'Race shorts', colorway: 'Charcoal', img: require('../../assets/character/outfit/ofB410.png'), layout: { w: 1.0667, top: 0.3982, dx: 0.0033 }, rarity: 'epic', unlock: passOnly },
  { id: 'wb111', label: 'Sage cropped joggers', family: 'Cropped joggers', colorway: 'Sage', img: require('../../assets/character/outfit/ofB411.png'), layout: { w: 1.3267, top: 0.297 }, rarity: 'common', unlock: free },
  // --- PASER running cosmetics (2026-09-17) ---
  { id: 'splitraceshorts', label: 'Split Race Shorts', family: 'Running shorts', colorway: 'Split', img: require('../../assets/character/outfit/ofB401.png'), layout: { w: 1.11, top: 0.4072, dx: 0.005 }, rarity: 'rare', unlock: free },
  { id: 'training5shorts', label: '5-inch Training Shorts', family: 'Training shorts', colorway: 'Black', img: require('../../assets/character/outfit/ofB402.png'), layout: { w: 1.11, top: 0.4072, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'twoinoneshorts', label: '2-in-1 Running Shorts', family: 'Running shorts', colorway: 'Black', img: require('../../assets/character/outfit/ofB403.png'), layout: { w: 1.11, top: 0.4072, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'performancehalftights', label: 'Performance Half Tights', family: 'Half tights', colorway: 'Black', img: require('../../assets/character/outfit/ofB404.png'), layout: { w: 1.2, top: 0.3733 }, rarity: 'common', unlock: free },
  { id: 'fullrunningtights', label: 'Full Running Tights', family: 'Running tights', colorway: 'Black', img: require('../../assets/character/outfit/ofB405.png'), layout: { w: 1.2333, top: 0.4212, dx: -0.0033 }, rarity: 'common', unlock: free },
  { id: 'trailrunningshorts', label: 'Trail Running Shorts', family: 'Trail shorts', colorway: 'Green', img: require('../../assets/character/outfit/ofB406.png'), layout: { w: 1.11, top: 0.4072, dx: 0.005 }, rarity: 'common', unlock: free },
  { id: 'raceskort', label: 'Race Skort', family: 'Skort', colorway: 'Black', img: require('../../assets/character/outfit/ofB407.png'), layout: { w: 1.1633, top: 0.3823, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'modestrunningpants', label: 'Lightweight Modest Running Pants', family: 'Running pants', colorway: 'Black', img: require('../../assets/character/outfit/ofB408.png'), layout: { w: 1.3267, top: 0.297 }, rarity: 'common', unlock: free },
];

export const FOOTWEAR = [
  // --- wave 6 (2026-08-09) --- refills the slots emptied on 08-08.
  // Names and layouts are both generated; see scripts/install-wardrobe-6.py.
  { id: 'wf001', label: 'Coral trainers', family: 'Trainers', colorway: 'Coral', img: require('../../assets/character/footwear/shoe301.png'), footL: require('../../assets/character/footwear/shoe301L.png'), footR: require('../../assets/character/footwear/shoe301R.png'), footLBack: require('../../assets/character/footwear/shoe301L-back.png'), footRBack: require('../../assets/character/footwear/shoe301R-back.png'), feet: { l: { w: 0.5061, dx: -0.2797, top: 0.8988, rot: 7 }, r: { w: 0.4937, dx: 0.2696, top: 0.9021, rot: -9.5 } }, layout: { w: 0.8967, top: 0.8442, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'wf002', label: 'Yellow skate shoes', family: 'Skate shoes', colorway: 'Yellow', img: require('../../assets/character/footwear/shoe302.png'), footL: require('../../assets/character/footwear/shoe302L.png'), footR: require('../../assets/character/footwear/shoe302R.png'), footLBack: require('../../assets/character/footwear/shoe302L-back.png'), footRBack: require('../../assets/character/footwear/shoe302R-back.png'), feet: { l: { w: 0.4407, dx: -0.2561, top: 0.8947, rot: 6 }, r: { w: 0.4385, dx: 0.2525, top: 0.8987, rot: -8.5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'common', unlock: free },
  { id: 'wf004', label: 'Blush slip ons', family: 'Slip ons', colorway: 'Blush', img: require('../../assets/character/footwear/shoe304.png'), footL: require('../../assets/character/footwear/shoe304L.png'), footR: require('../../assets/character/footwear/shoe304R.png'), footLBack: require('../../assets/character/footwear/shoe304L-back.png'), footRBack: require('../../assets/character/footwear/shoe304R-back.png'), feet: { l: { w: 0.4589, dx: -0.2571, top: 0.8776, rot: 6 }, r: { w: 0.4619, dx: 0.2504, top: 0.8842, rot: -7 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf005', label: 'Black and red runners', family: 'Runners', colorway: 'Black and red', img: require('../../assets/character/footwear/shoe305.png'), footL: require('../../assets/character/footwear/shoe305L.png'), footR: require('../../assets/character/footwear/shoe305R.png'), footLBack: require('../../assets/character/footwear/shoe305L-back.png'), footRBack: require('../../assets/character/footwear/shoe305R-back.png'), feet: { l: { w: 0.4319, dx: -0.2636, top: 0.8965, rot: 8.5 }, r: { w: 0.4423, dx: 0.2524, top: 0.8994, rot: -3.5 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'rare', unlock: passOnly },
  { id: 'wf006', label: 'Forest trail shoes', family: 'Trail shoes', colorway: 'Forest', img: require('../../assets/character/footwear/shoe306.png'), footL: require('../../assets/character/footwear/shoe306L.png'), footR: require('../../assets/character/footwear/shoe306R.png'), footLBack: require('../../assets/character/footwear/shoe306L-back.png'), footRBack: require('../../assets/character/footwear/shoe306R-back.png'), feet: { l: { w: 0.4578, dx: -0.26, top: 0.8866, rot: 6 }, r: { w: 0.454, dx: 0.2321, top: 0.8861, rot: -8 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'common', unlock: free },
  { id: 'wf007', label: 'Blue high tops', family: 'High tops', colorway: 'Blue', img: require('../../assets/character/footwear/shoe307.png'), footL: require('../../assets/character/footwear/shoe307L.png'), footR: require('../../assets/character/footwear/shoe307R.png'), footLBack: require('../../assets/character/footwear/shoe307L-back.png'), footRBack: require('../../assets/character/footwear/shoe307R-back.png'), feet: { l: { w: 0.4178, dx: -0.2463, top: 0.8779, rot: 4.5 }, r: { w: 0.4352, dx: 0.2408, top: 0.8718, rot: -8.5 } }, layout: { w: 0.7, top: 0.8107 }, rarity: 'common', unlock: free },
  { id: 'wf008', label: 'Pastel runners', family: 'Runners', colorway: 'Pastel', img: require('../../assets/character/footwear/shoe308.png'), footL: require('../../assets/character/footwear/shoe308L.png'), footR: require('../../assets/character/footwear/shoe308R.png'), footLBack: require('../../assets/character/footwear/shoe308L-back.png'), footRBack: require('../../assets/character/footwear/shoe308R-back.png'), feet: { l: { w: 0.4721, dx: -0.248, top: 0.8856, rot: 7 }, r: { w: 0.4472, dx: 0.2422, top: 0.8904, rot: -8.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf009', label: 'Teal canvas sneakers', family: 'Canvas sneakers', colorway: 'Teal', img: require('../../assets/character/footwear/shoe309.png'), footL: require('../../assets/character/footwear/shoe309L.png'), footR: require('../../assets/character/footwear/shoe309R.png'), footLBack: require('../../assets/character/footwear/shoe309L-back.png'), footRBack: require('../../assets/character/footwear/shoe309R-back.png'), feet: { l: { w: 0.4446, dx: -0.2703, top: 0.8996, rot: 8 }, r: { w: 0.4476, dx: 0.2587, top: 0.8997, rot: -9.5 } }, layout: { w: 0.7, top: 0.8062 }, rarity: 'common', unlock: free },
  { id: 'wf010', label: 'Purple and gold sneakers', family: 'Sneakers', colorway: 'Purple and gold', img: require('../../assets/character/footwear/shoe310.png'), footL: require('../../assets/character/footwear/shoe310L.png'), footR: require('../../assets/character/footwear/shoe310R.png'), footLBack: require('../../assets/character/footwear/shoe310L-back.png'), footRBack: require('../../assets/character/footwear/shoe310R-back.png'), feet: { l: { w: 0.4348, dx: -0.2356, top: 0.8862, rot: 5 }, r: { w: 0.446, dx: 0.2416, top: 0.8904, rot: -3.5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'rare', unlock: passOnly },
  { id: 'wf011', label: 'Volt runners', family: 'Runners', colorway: 'Volt', img: require('../../assets/character/footwear/shoe311.png'), footL: require('../../assets/character/footwear/shoe311L.png'), footR: require('../../assets/character/footwear/shoe311R.png'), footLBack: require('../../assets/character/footwear/shoe311L-back.png'), footRBack: require('../../assets/character/footwear/shoe311R-back.png'), feet: { l: { w: 0.5954, dx: -0.2941, top: 0.9037, rot: 7 }, r: { w: 0.5437, dx: 0.2805, top: 0.9112, rot: -10.5 } }, layout: { w: 0.7, top: 0.8107 }, rarity: 'epic', unlock: passOnly },
  { id: 'wf012', label: 'Olive retro sneakers', family: 'Retro sneakers', colorway: 'Olive', img: require('../../assets/character/footwear/shoe312.png'), footL: require('../../assets/character/footwear/shoe312L.png'), footR: require('../../assets/character/footwear/shoe312R.png'), footLBack: require('../../assets/character/footwear/shoe312L-back.png'), footRBack: require('../../assets/character/footwear/shoe312R-back.png'), feet: { l: { w: 0.4819, dx: -0.2676, top: 0.9016, rot: 9.5 }, r: { w: 0.4909, dx: 0.2696, top: 0.9, rot: -9.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf013', label: 'Aqua trainers', family: 'Trainers', colorway: 'Aqua', img: require('../../assets/character/footwear/shoe313.png'), footL: require('../../assets/character/footwear/shoe313L.png'), footR: require('../../assets/character/footwear/shoe313R.png'), footLBack: require('../../assets/character/footwear/shoe313L-back.png'), footRBack: require('../../assets/character/footwear/shoe313R-back.png'), feet: { l: { w: 0.4642, dx: -0.2746, top: 0.8921, rot: 8.5 }, r: { w: 0.4562, dx: 0.2567, top: 0.8988, rot: -11 } }, layout: { w: 0.7, top: 0.8081 }, rarity: 'common', unlock: free },
  { id: 'wf015', label: 'Black knit runners', family: 'Knit runners', colorway: 'Black', img: require('../../assets/character/footwear/shoe315.png'), footL: require('../../assets/character/footwear/shoe315L.png'), footR: require('../../assets/character/footwear/shoe315R.png'), footLBack: require('../../assets/character/footwear/shoe315L-back.png'), footRBack: require('../../assets/character/footwear/shoe315R-back.png'), feet: { l: { w: 0.4992, dx: -0.2799, top: 0.8945, rot: 8 }, r: { w: 0.4842, dx: 0.2692, top: 0.898, rot: -7 } }, layout: { w: 0.7, top: 0.8107 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf018', label: 'Crimson sneakers', family: 'Sneakers', colorway: 'Crimson', img: require('../../assets/character/footwear/shoe318.png'), footL: require('../../assets/character/footwear/shoe318L.png'), footR: require('../../assets/character/footwear/shoe318R.png'), footLBack: require('../../assets/character/footwear/shoe318L-back.png'), footRBack: require('../../assets/character/footwear/shoe318R-back.png'), feet: { l: { w: 0.4388, dx: -0.2598, top: 0.8906, rot: 8 }, r: { w: 0.4543, dx: 0.2558, top: 0.8956, rot: -7 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'common', unlock: free },
  { id: 'wf019', label: 'Cyan tech runners', family: 'Tech runners', colorway: 'Cyan', img: require('../../assets/character/footwear/shoe319.png'), footL: require('../../assets/character/footwear/shoe319L.png'), footR: require('../../assets/character/footwear/shoe319R.png'), footLBack: require('../../assets/character/footwear/shoe319L-back.png'), footRBack: require('../../assets/character/footwear/shoe319R-back.png'), feet: { l: { w: 0.4513, dx: -0.2681, top: 0.8983, rot: 8.5 }, r: { w: 0.4462, dx: 0.2576, top: 0.8995, rot: -9.5 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'common', unlock: free },
  { id: 'wf020', label: 'Lavender sneakers', family: 'Sneakers', colorway: 'Lavender', img: require('../../assets/character/footwear/shoe320.png'), footL: require('../../assets/character/footwear/shoe320L.png'), footR: require('../../assets/character/footwear/shoe320R.png'), footLBack: require('../../assets/character/footwear/shoe320L-back.png'), footRBack: require('../../assets/character/footwear/shoe320R-back.png'), feet: { l: { w: 0.4656, dx: -0.2627, top: 0.8924, rot: 7 }, r: { w: 0.4743, dx: 0.262, top: 0.8904, rot: -9.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf021', label: 'Mint and lilac runners', family: 'Runners', colorway: 'Mint and lilac', img: require('../../assets/character/footwear/shoe321.png'), footL: require('../../assets/character/footwear/shoe321L.png'), footR: require('../../assets/character/footwear/shoe321R.png'), footLBack: require('../../assets/character/footwear/shoe321L-back.png'), footRBack: require('../../assets/character/footwear/shoe321R-back.png'), feet: { l: { w: 0.4847, dx: -0.2713, top: 0.8952, rot: 10.5 }, r: { w: 0.4846, dx: 0.2646, top: 0.8969, rot: -9.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf022', label: 'Black and gold high tops', family: 'High tops', colorway: 'Black and gold', img: require('../../assets/character/footwear/shoe322.png'), footL: require('../../assets/character/footwear/shoe322L.png'), footR: require('../../assets/character/footwear/shoe322R.png'), footLBack: require('../../assets/character/footwear/shoe322L-back.png'), footRBack: require('../../assets/character/footwear/shoe322R-back.png'), feet: { l: { w: 0.4831, dx: -0.2583, top: 0.8805, rot: 2.5 }, r: { w: 0.4615, dx: 0.2675, top: 0.8845, rot: -7 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'epic', unlock: dist(25, 'Run 25 km total') },
  { id: 'wf023', label: 'Red trail runners', family: 'Trail runners', colorway: 'Red', img: require('../../assets/character/footwear/shoe323.png'), footL: require('../../assets/character/footwear/shoe323L.png'), footR: require('../../assets/character/footwear/shoe323R.png'), footLBack: require('../../assets/character/footwear/shoe323L-back.png'), footRBack: require('../../assets/character/footwear/shoe323R-back.png'), feet: { l: { w: 0.5473, dx: -0.2849, top: 0.8977, rot: 5 }, r: { w: 0.5296, dx: 0.2793, top: 0.9034, rot: -5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'common', unlock: free },
  { id: 'wf024', label: 'Orange stripe high tops', family: 'High tops', colorway: 'Orange stripe', img: require('../../assets/character/footwear/shoe324.png'), footL: require('../../assets/character/footwear/shoe324L.png'), footR: require('../../assets/character/footwear/shoe324R.png'), footLBack: require('../../assets/character/footwear/shoe324L-back.png'), footRBack: require('../../assets/character/footwear/shoe324R-back.png'), feet: { l: { w: 0.5164, dx: -0.2731, top: 0.8916, rot: 3.5 }, r: { w: 0.5089, dx: 0.2647, top: 0.8904, rot: -2.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf025', label: 'Mint canvas sneakers', family: 'Canvas sneakers', colorway: 'Mint', img: require('../../assets/character/footwear/shoe325.png'), footL: require('../../assets/character/footwear/shoe325L.png'), footR: require('../../assets/character/footwear/shoe325R.png'), footLBack: require('../../assets/character/footwear/shoe325L-back.png'), footRBack: require('../../assets/character/footwear/shoe325R-back.png'), feet: { l: { w: 0.4956, dx: -0.2848, top: 0.902, rot: 4.5 }, r: { w: 0.5285, dx: 0.287, top: 0.8945, rot: 0 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf026', label: 'Purple runners', family: 'Runners', colorway: 'Purple', img: require('../../assets/character/footwear/shoe326.png'), footL: require('../../assets/character/footwear/shoe326L.png'), footR: require('../../assets/character/footwear/shoe326R.png'), footLBack: require('../../assets/character/footwear/shoe326L-back.png'), footRBack: require('../../assets/character/footwear/shoe326R-back.png'), feet: { l: { w: 0.4945, dx: -0.2599, top: 0.8913, rot: 6 }, r: { w: 0.4817, dx: 0.2583, top: 0.8934, rot: -2.5 } }, layout: { w: 0.7, top: 0.8081 }, rarity: 'common', unlock: free },
  { id: 'wf027', label: 'Tan hiking shoes', family: 'Hiking shoes', colorway: 'Tan', img: require('../../assets/character/footwear/shoe327.png'), footL: require('../../assets/character/footwear/shoe327L.png'), footR: require('../../assets/character/footwear/shoe327R.png'), footLBack: require('../../assets/character/footwear/shoe327L-back.png'), footRBack: require('../../assets/character/footwear/shoe327R-back.png'), feet: { l: { w: 0.507, dx: -0.2638, top: 0.8985, rot: 0 }, r: { w: 0.5246, dx: 0.269, top: 0.8965, rot: -6 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'common', unlock: free },
  { id: 'wf028', label: 'Lemon runners', family: 'Runners', colorway: 'Lemon', img: require('../../assets/character/footwear/shoe328.png'), footL: require('../../assets/character/footwear/shoe328L.png'), footR: require('../../assets/character/footwear/shoe328R.png'), footLBack: require('../../assets/character/footwear/shoe328L-back.png'), footRBack: require('../../assets/character/footwear/shoe328R-back.png'), feet: { l: { w: 0.56, dx: -0.2756, top: 0.8991, rot: 5 }, r: { w: 0.5264, dx: 0.266, top: 0.902, rot: -9.5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'common', unlock: free },
  { id: 'wf029', label: 'Silver trainers', family: 'Trainers', colorway: 'Silver', img: require('../../assets/character/footwear/shoe329.png'), footL: require('../../assets/character/footwear/shoe329L.png'), footR: require('../../assets/character/footwear/shoe329R.png'), footLBack: require('../../assets/character/footwear/shoe329L-back.png'), footRBack: require('../../assets/character/footwear/shoe329R-back.png'), feet: { l: { w: 0.5609, dx: -0.2669, top: 0.8913, rot: 4.5 }, r: { w: 0.5093, dx: 0.2549, top: 0.8904, rot: -8.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf030', label: 'Berry sneakers', family: 'Sneakers', colorway: 'Berry', img: require('../../assets/character/footwear/shoe330.png'), footL: require('../../assets/character/footwear/shoe330L.png'), footR: require('../../assets/character/footwear/shoe330R.png'), footLBack: require('../../assets/character/footwear/shoe330L-back.png'), footRBack: require('../../assets/character/footwear/shoe330R-back.png'), feet: { l: { w: 0.5311, dx: -0.2866, top: 0.9031, rot: 8.5 }, r: { w: 0.4968, dx: 0.2678, top: 0.9072, rot: -6 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf031', label: 'Pink platform sneakers', family: 'Platform sneakers', colorway: 'Pink', img: require('../../assets/character/footwear/shoe331.png'), footL: require('../../assets/character/footwear/shoe331L.png'), footR: require('../../assets/character/footwear/shoe331R.png'), footLBack: require('../../assets/character/footwear/shoe331L-back.png'), footRBack: require('../../assets/character/footwear/shoe331R-back.png'), feet: { l: { w: 0.535, dx: -0.2596, top: 0.8873, rot: 1.5 }, r: { w: 0.4931, dx: 0.2567, top: 0.8865, rot: -5 } }, layout: { w: 0.7, top: 0.8107 }, rarity: 'common', unlock: free },
  { id: 'wf032', label: 'Striped slides', family: 'Slides', colorway: 'Striped', img: require('../../assets/character/footwear/shoe332.png'), backImg: require('../../assets/character/footwear/shoe332_worn-back.png'), wornImg: require('../../assets/character/footwear/shoe332_worn.png'), layout: { w: 0.9071, top: 0.8411, dx: -0.0161 }, rarity: 'common', unlock: free },
  { id: 'wf034', label: 'Lilac ballet flats', family: 'Ballet flats', colorway: 'Lilac', img: require('../../assets/character/footwear/shoe334.png'), footL: require('../../assets/character/footwear/shoe334L.png'), footR: require('../../assets/character/footwear/shoe334R.png'), footLBack: require('../../assets/character/footwear/shoe334L-back.png'), footRBack: require('../../assets/character/footwear/shoe334R-back.png'), feet: { l: { w: 0.4201, dx: -0.2018, top: 0.8931, rot: 0 }, r: { w: 0.4393, dx: 0.2218, top: 0.8891, rot: 0 } }, layout: { w: 0.7, top: 0.8107 }, rarity: 'common', unlock: free },
  { id: 'wf036', label: 'Olive hiking boots', family: 'Hiking boots', colorway: 'Olive', img: require('../../assets/character/footwear/shoe336.png'), footL: require('../../assets/character/footwear/shoe336L.png'), footR: require('../../assets/character/footwear/shoe336R.png'), footLBack: require('../../assets/character/footwear/shoe336L-back.png'), footRBack: require('../../assets/character/footwear/shoe336R-back.png'), feet: { l: { w: 0.524, dx: -0.2664, top: 0.8873, rot: 6 }, r: { w: 0.5185, dx: 0.2787, top: 0.891, rot: -6 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf037', label: 'Brown fleece slippers', family: 'Fleece slippers', colorway: 'Brown', img: require('../../assets/character/footwear/shoe337.png'), footL: require('../../assets/character/footwear/shoe337L.png'), footR: require('../../assets/character/footwear/shoe337R.png'), footLBack: require('../../assets/character/footwear/shoe337L-back.png'), footRBack: require('../../assets/character/footwear/shoe337R-back.png'), feet: { l: { w: 0.4701, dx: -0.2297, top: 0.9082, rot: 6 }, r: { w: 0.4511, dx: 0.2289, top: 0.8907, rot: -12 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'common', unlock: free },
  { id: 'wf040', label: 'Teal trim slip ons', family: 'Slip ons', colorway: 'Teal trim', img: require('../../assets/character/footwear/shoe340.png'), footL: require('../../assets/character/footwear/shoe340L.png'), footR: require('../../assets/character/footwear/shoe340R.png'), footLBack: require('../../assets/character/footwear/shoe340L-back.png'), footRBack: require('../../assets/character/footwear/shoe340R-back.png'), feet: { l: { w: 0.4813, dx: -0.2541, top: 0.91, rot: 0 }, r: { w: 0.4785, dx: 0.2575, top: 0.9085, rot: 0 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf041', label: 'Yellow rain boots', family: 'Rain boots', colorway: 'Yellow', img: require('../../assets/character/footwear/shoe341.png'), footL: require('../../assets/character/footwear/shoe341L.png'), footR: require('../../assets/character/footwear/shoe341R.png'), footLBack: require('../../assets/character/footwear/shoe341L-back.png'), footRBack: require('../../assets/character/footwear/shoe341R-back.png'), feet: { l: { w: 0.388, dx: -0.2298, top: 0.8487, rot: 0 }, r: { w: 0.3825, dx: 0.2187, top: 0.8455, rot: 0 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf043', label: 'Red Mary Janes', family: 'Mary Janes', colorway: 'Red', img: require('../../assets/character/footwear/shoe343.png'), footL: require('../../assets/character/footwear/shoe343L.png'), footR: require('../../assets/character/footwear/shoe343R.png'), footLBack: require('../../assets/character/footwear/shoe343L-back.png'), footRBack: require('../../assets/character/footwear/shoe343R-back.png'), feet: { l: { w: 0.436, dx: -0.2483, top: 0.8974, rot: 7 }, r: { w: 0.4656, dx: 0.2345, top: 0.897, rot: -8.5 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'common', unlock: free },
  { id: 'wf044', label: 'Pink strap sneakers', family: 'Strap sneakers', colorway: 'Pink', img: require('../../assets/character/footwear/shoe344.png'), footL: require('../../assets/character/footwear/shoe344L.png'), footR: require('../../assets/character/footwear/shoe344R.png'), footLBack: require('../../assets/character/footwear/shoe344L-back.png'), footRBack: require('../../assets/character/footwear/shoe344R-back.png'), feet: { l: { w: 0.4803, dx: -0.2591, top: 0.9027, rot: 4.5 }, r: { w: 0.4978, dx: 0.2624, top: 0.8976, rot: -5 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'epic', unlock: passOnly },
  { id: 'wf045', label: 'Bow espadrilles', family: 'Espadrilles', colorway: 'Cream', img: require('../../assets/character/footwear/shoe345.png'), footL: require('../../assets/character/footwear/shoe345L.png'), footR: require('../../assets/character/footwear/shoe345R.png'), footLBack: require('../../assets/character/footwear/shoe345L-back.png'), footRBack: require('../../assets/character/footwear/shoe345R-back.png'), feet: { l: { w: 0.4742, dx: -0.2478, top: 0.8999, rot: 0 }, r: { w: 0.4291, dx: 0.2287, top: 0.8999, rot: 0 } }, layout: { w: 0.7, top: 0.8107 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf046', label: 'Black work boots', family: 'Work boots', colorway: 'Black', img: require('../../assets/character/footwear/shoe346.png'), footL: require('../../assets/character/footwear/shoe346L.png'), footR: require('../../assets/character/footwear/shoe346R.png'), footLBack: require('../../assets/character/footwear/shoe346L-back.png'), footRBack: require('../../assets/character/footwear/shoe346R-back.png'), feet: { l: { w: 0.5082, dx: -0.2752, top: 0.8799, rot: 0 }, r: { w: 0.535, dx: 0.2697, top: 0.8792, rot: 0 } }, layout: { w: 0.7, top: 0.8075 }, rarity: 'common', unlock: free },
  { id: 'wf047', label: 'Mint court sneakers', family: 'Court sneakers', colorway: 'Mint', img: require('../../assets/character/footwear/shoe347.png'), footL: require('../../assets/character/footwear/shoe347L.png'), footR: require('../../assets/character/footwear/shoe347R.png'), footLBack: require('../../assets/character/footwear/shoe347L-back.png'), footRBack: require('../../assets/character/footwear/shoe347R-back.png'), feet: { l: { w: 0.527, dx: -0.285, top: 0.8892, rot: 6 }, r: { w: 0.5407, dx: 0.2857, top: 0.8924, rot: -6 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'common', unlock: free },
  { id: 'wf048', label: 'Tan moccasins', family: 'Moccasins', colorway: 'Tan', img: require('../../assets/character/footwear/shoe348.png'), footL: require('../../assets/character/footwear/shoe348L.png'), footR: require('../../assets/character/footwear/shoe348R.png'), footLBack: require('../../assets/character/footwear/shoe348L-back.png'), footRBack: require('../../assets/character/footwear/shoe348R-back.png'), feet: { l: { w: 0.4646, dx: -0.2548, top: 0.8958, rot: 2.5 }, r: { w: 0.4691, dx: 0.2576, top: 0.8863, rot: -9.5 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf049', label: 'Chrome sneakers', family: 'Sneakers', colorway: 'Chrome', img: require('../../assets/character/footwear/shoe349.png'), footL: require('../../assets/character/footwear/shoe349L.png'), footR: require('../../assets/character/footwear/shoe349R.png'), footLBack: require('../../assets/character/footwear/shoe349L-back.png'), footRBack: require('../../assets/character/footwear/shoe349R-back.png'), feet: { l: { w: 0.535, dx: -0.2727, top: 0.8939, rot: 0 }, r: { w: 0.5356, dx: 0.2835, top: 0.8994, rot: -2.5 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'common', unlock: free },
  { id: 'wf050', label: 'Navy clogs', family: 'Clogs', colorway: 'Navy', img: require('../../assets/character/footwear/shoe350.png'), footL: require('../../assets/character/footwear/shoe350L.png'), footR: require('../../assets/character/footwear/shoe350R.png'), footLBack: require('../../assets/character/footwear/shoe350L-back.png'), footRBack: require('../../assets/character/footwear/shoe350R-back.png'), feet: { l: { w: 0.418, dx: -0.2373, top: 0.9036, rot: 0 }, r: { w: 0.3989, dx: 0.2316, top: 0.9131, rot: 0 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf051', label: 'Teal sport sandals', family: 'Sport sandals', colorway: 'Teal', img: require('../../assets/character/footwear/shoe351.png'), footL: require('../../assets/character/footwear/shoe351L.png'), footR: require('../../assets/character/footwear/shoe351R.png'), footLBack: require('../../assets/character/footwear/shoe351L-back.png'), footRBack: require('../../assets/character/footwear/shoe351R-back.png'), feet: { l: { w: 0.4852, dx: -0.248, top: 0.8851, rot: 0 }, r: { w: 0.4913, dx: 0.2559, top: 0.8805, rot: 0 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf052', label: 'Maroon Chelsea boots', family: 'Chelsea boots', colorway: 'Maroon', img: require('../../assets/character/footwear/shoe352.png'), footL: require('../../assets/character/footwear/shoe352L.png'), footR: require('../../assets/character/footwear/shoe352R.png'), footLBack: require('../../assets/character/footwear/shoe352L-back.png'), footRBack: require('../../assets/character/footwear/shoe352R-back.png'), feet: { l: { w: 0.5576, dx: -0.2911, top: 0.8633, rot: 0 }, r: { w: 0.5621, dx: 0.3005, top: 0.8692, rot: 0 } }, layout: { w: 0.7, top: 0.8062 }, rarity: 'common', unlock: free },
  { id: 'wf053', label: 'Duck boots', family: 'Duck boots', colorway: 'Brown and cream', img: require('../../assets/character/footwear/shoe353.png'), backImg: require('../../assets/character/footwear/shoe353-back.png'), layout: { w: 0.9233, top: 0.8005, dx: -0.0166 }, rarity: 'common', unlock: free },
  { id: 'wf054', label: 'Checkered slip ons', family: 'Slip ons', colorway: 'Checkered', img: require('../../assets/character/footwear/shoe354.png'), footL: require('../../assets/character/footwear/shoe354L.png'), footR: require('../../assets/character/footwear/shoe354R.png'), footLBack: require('../../assets/character/footwear/shoe354L-back.png'), footRBack: require('../../assets/character/footwear/shoe354R-back.png'), feet: { l: { w: 0.438, dx: -0.2615, top: 0.8973, rot: 0 }, r: { w: 0.4691, dx: 0.282, top: 0.8952, rot: 0 } }, layout: { w: 0.7, top: 0.8081 }, rarity: 'common', unlock: free },
  { id: 'wf055', label: 'Lilac Mary Janes', family: 'Mary Janes', colorway: 'Lilac', img: require('../../assets/character/footwear/shoe355.png'), footL: require('../../assets/character/footwear/shoe355L.png'), footR: require('../../assets/character/footwear/shoe355R.png'), footLBack: require('../../assets/character/footwear/shoe355L-back.png'), footRBack: require('../../assets/character/footwear/shoe355R-back.png'), feet: { l: { w: 0.428, dx: -0.2431, top: 0.8893, rot: 0 }, r: { w: 0.4425, dx: 0.2487, top: 0.8826, rot: 0 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'epic', unlock: dist(25, 'Run 25 km total') },
  { id: 'wf060', label: 'Red canvas high tops', family: 'Canvas high tops', colorway: 'Red', img: require('../../assets/character/footwear/shoe360.png'), footL: require('../../assets/character/footwear/shoe360L.png'), footR: require('../../assets/character/footwear/shoe360R.png'), footLBack: require('../../assets/character/footwear/shoe360L-back.png'), footRBack: require('../../assets/character/footwear/shoe360R-back.png'), feet: { l: { w: 0.4331, dx: -0.2406, top: 0.8724, rot: 5 }, r: { w: 0.4199, dx: 0.2404, top: 0.872, rot: -5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf061', label: 'Navy boat shoes', family: 'Boat shoes', colorway: 'Navy', img: require('../../assets/character/footwear/shoe361.png'), footL: require('../../assets/character/footwear/shoe361L.png'), footR: require('../../assets/character/footwear/shoe361R.png'), footLBack: require('../../assets/character/footwear/shoe361L-back.png'), footRBack: require('../../assets/character/footwear/shoe361R-back.png'), feet: { l: { w: 0.4907, dx: -0.269, top: 0.9015, rot: 0 }, r: { w: 0.456, dx: 0.2478, top: 0.8887, rot: 0 } }, layout: { w: 0.7, top: 0.8101 }, rarity: 'common', unlock: free },
  { id: 'wf063', label: 'Gold trim loafers', family: 'Loafers', colorway: 'Black and gold', img: require('../../assets/character/footwear/shoe363.png'), footL: require('../../assets/character/footwear/shoe363L.png'), footR: require('../../assets/character/footwear/shoe363R.png'), footLBack: require('../../assets/character/footwear/shoe363L-back.png'), footRBack: require('../../assets/character/footwear/shoe363R-back.png'), feet: { l: { w: 0.4658, dx: -0.2787, top: 0.8916, rot: 9.5 }, r: { w: 0.4831, dx: 0.2651, top: 0.8989, rot: -5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'common', unlock: free },
  { id: 'wf064', label: 'Aqua mesh runners', family: 'Mesh runners', colorway: 'Aqua', img: require('../../assets/character/footwear/shoe364.png'), footL: require('../../assets/character/footwear/shoe364L.png'), footR: require('../../assets/character/footwear/shoe364R.png'), footLBack: require('../../assets/character/footwear/shoe364L-back.png'), footRBack: require('../../assets/character/footwear/shoe364R-back.png'), feet: { l: { w: 0.5044, dx: -0.2837, top: 0.897, rot: 8.5 }, r: { w: 0.4662, dx: 0.2511, top: 0.8858, rot: -5 } }, layout: { w: 0.7, top: 0.8088 }, rarity: 'common', unlock: free },
  { id: 'wf070', label: 'Cream strap shoes', family: 'Strap shoes', colorway: 'Cream', img: require('../../assets/character/footwear/shoe370.png'), footL: require('../../assets/character/footwear/shoe370L.png'), footR: require('../../assets/character/footwear/shoe370R.png'), footLBack: require('../../assets/character/footwear/shoe370L-back.png'), footRBack: require('../../assets/character/footwear/shoe370R-back.png'), feet: { l: { w: 0.4835, dx: -0.2399, top: 0.8925, rot: 0 }, r: { w: 0.4734, dx: 0.2436, top: 0.8968, rot: 0 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf071', label: 'Black skate shoes', family: 'Skate shoes', colorway: 'Black', img: require('../../assets/character/footwear/shoe371.png'), footL: require('../../assets/character/footwear/shoe371L.png'), footR: require('../../assets/character/footwear/shoe371R.png'), footLBack: require('../../assets/character/footwear/shoe371L-back.png'), footRBack: require('../../assets/character/footwear/shoe371R-back.png'), feet: { l: { w: 0.4811, dx: -0.2524, top: 0.8885, rot: 0 }, r: { w: 0.4709, dx: 0.2412, top: 0.8863, rot: 0 } }, layout: { w: 0.7, top: 0.8081 }, rarity: 'common', unlock: free },
  { id: 'wf076', label: 'Tassel loafers', family: 'Tassel loafers', colorway: 'Black', img: require('../../assets/character/footwear/shoe376.png'), footL: require('../../assets/character/footwear/shoe376L.png'), footR: require('../../assets/character/footwear/shoe376R.png'), footLBack: require('../../assets/character/footwear/shoe376L-back.png'), footRBack: require('../../assets/character/footwear/shoe376R-back.png'), feet: { l: { w: 0.5462, dx: -0.296, top: 0.9086, rot: 0 }, r: { w: 0.5374, dx: 0.2732, top: 0.9057, rot: 0 } }, layout: { w: 0.7, top: 0.8075 }, rarity: 'common', unlock: free },
  { id: 'wf078', label: 'Brown work boots', family: 'Work boots', colorway: 'Brown', img: require('../../assets/character/footwear/shoe378.png'), footL: require('../../assets/character/footwear/shoe378L.png'), footR: require('../../assets/character/footwear/shoe378R.png'), footLBack: require('../../assets/character/footwear/shoe378L-back.png'), footRBack: require('../../assets/character/footwear/shoe378R-back.png'), feet: { l: { w: 0.4613, dx: -0.2425, top: 0.8788, rot: 0 }, r: { w: 0.4636, dx: 0.2452, top: 0.8866, rot: -3.5 } }, layout: { w: 0.7, top: 0.8114 }, rarity: 'common', unlock: free },
  { id: 'wf079', label: 'Pink fluffy slippers', family: 'Fluffy slippers', colorway: 'Pink', img: require('../../assets/character/footwear/shoe379.png'), footL: require('../../assets/character/footwear/shoe379L.png'), footR: require('../../assets/character/footwear/shoe379R.png'), footLBack: require('../../assets/character/footwear/shoe379L-back.png'), footRBack: require('../../assets/character/footwear/shoe379R-back.png'), feet: { l: { w: 0.4213, dx: -0.2376, top: 0.8897, rot: 0 }, r: { w: 0.4225, dx: 0.2332, top: 0.8772, rot: 0 } }, layout: { w: 0.7, top: 0.8094 }, rarity: 'common', unlock: free },
  { id: 'wf081', label: 'Peach ballet flats', family: 'Ballet flats', colorway: 'Peach', img: require('../../assets/character/footwear/shoe381.png'), footL: require('../../assets/character/footwear/shoe381L.png'), footR: require('../../assets/character/footwear/shoe381R.png'), footLBack: require('../../assets/character/footwear/shoe381L-back.png'), footRBack: require('../../assets/character/footwear/shoe381R-back.png'), feet: { l: { w: 0.438, dx: -0.2377, top: 0.8941, rot: 0 }, r: { w: 0.4525, dx: 0.2319, top: 0.887, rot: 0 } }, layout: { w: 0.7, top: 0.8068 }, rarity: 'common', unlock: free },
  { id: 'wf083', label: 'Tan Chelsea boots', family: 'Chelsea boots', colorway: 'Tan', img: require('../../assets/character/footwear/shoe383.png'), footL: require('../../assets/character/footwear/shoe383L.png'), footR: require('../../assets/character/footwear/shoe383R.png'), footLBack: require('../../assets/character/footwear/shoe383L-back.png'), footRBack: require('../../assets/character/footwear/shoe383R-back.png'), feet: { l: { w: 0.478, dx: -0.2681, top: 0.8556, rot: 0 }, r: { w: 0.4825, dx: 0.272, top: 0.8507, rot: 0 } }, layout: { w: 0.7, top: 0.8062 }, rarity: 'common', unlock: free },
  { id: 'wf084', label: 'Lime trail runners', family: 'Trail runners', colorway: 'Lime', img: require('../../assets/character/footwear/shoe384.png'), footL: require('../../assets/character/footwear/shoe384L.png'), footR: require('../../assets/character/footwear/shoe384R.png'), footLBack: require('../../assets/character/footwear/shoe384L-back.png'), footRBack: require('../../assets/character/footwear/shoe384R-back.png'), feet: { l: { w: 0.4917, dx: -0.2632, top: 0.9019, rot: 0 }, r: { w: 0.5272, dx: 0.2634, top: 0.8908, rot: 0 } }, layout: { w: 0.7, top: 0.8075 }, rarity: 'common', unlock: free },
  { id: 'wf085', label: 'Burgundy strap heels', family: 'Strap heels', colorway: 'Burgundy', img: require('../../assets/character/footwear/shoe385.png'), footL: require('../../assets/character/footwear/shoe385L.png'), footR: require('../../assets/character/footwear/shoe385R.png'), footLBack: require('../../assets/character/footwear/shoe385L-back.png'), footRBack: require('../../assets/character/footwear/shoe385R-back.png'), feet: { l: { w: 0.5417, dx: -0.2906, top: 0.8605, rot: 0 }, r: { w: 0.4989, dx: 0.276, top: 0.8573, rot: 0 } }, layout: { w: 0.7, top: 0.8081 }, rarity: 'rare', unlock: runs(15, 'Finish 15 runs') },
  { id: 'wf086', label: 'Sky blue slides', family: 'Slides', colorway: 'Sky blue', img: require('../../assets/character/footwear/shoe386.png'), footL: require('../../assets/character/footwear/shoe386L.png'), footR: require('../../assets/character/footwear/shoe386R.png'), footLBack: require('../../assets/character/footwear/shoe386L-back.png'), footRBack: require('../../assets/character/footwear/shoe386R-back.png'), feet: { l: { w: 0.4268, dx: -0.2414, top: 0.9186, rot: 0 }, r: { w: 0.4499, dx: 0.2087, top: 0.9027, rot: 0 } }, layout: { w: 0.7, top: 0.8062 }, rarity: 'common', unlock: free },
  // --- PASER running cosmetics (2026-09-17) ---
  { id: 'dailytrainer', label: 'Daily Trainer', family: 'Trainers', colorway: 'Daily', img: require('../../assets/character/_src/footwear/09_daily_trainer.png'), layout: { w: 0.8967, top: 0.8442, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'maxcushiontrainer', label: 'Max Cushion Trainer', family: 'Trainers', colorway: 'Max cushion', img: require('../../assets/character/_src/footwear/10_max_cushion_trainer.png'), layout: { w: 0.8967, top: 0.8442, dx: 0.0017 }, rarity: 'common', unlock: free },
  { id: 'temposhoe', label: 'Tempo Shoe', family: 'Running shoes', colorway: 'Tempo', img: require('../../assets/character/_src/footwear/11_tempo_shoe.png'), layout: { w: 0.7, top: 0.8094 }, rarity: 'rare', unlock: free },
  { id: 'carbonracer', label: 'Carbon Race Shoe', family: 'Running shoes', colorway: 'Carbon', img: require('../../assets/character/_src/footwear/12_carbon_race_shoe.png'), layout: { w: 0.7, top: 0.8094 }, rarity: 'epic', unlock: free },
  { id: 'trailgripshoe', label: 'Trail Grip Shoe', family: 'Trail shoes', colorway: 'Trail grip', img: require('../../assets/character/_src/footwear/13_trail_grip_shoe.png'), layout: { w: 0.7, top: 0.8114 }, rarity: 'rare', unlock: free },
  { id: 'wetweatherrunner', label: 'Wet Weather Runner', family: 'Running shoes', colorway: 'Wet weather', img: require('../../assets/character/_src/footwear/14_wet_weather_runner.png'), layout: { w: 0.7, top: 0.8094 }, rarity: 'rare', unlock: free },
  { id: 'reflectivenightrunner', label: 'Reflective Night Runner', family: 'Running shoes', colorway: 'Reflective night', img: require('../../assets/character/_src/footwear/15_reflective_night_runner.png'), layout: { w: 0.7, top: 0.8094 }, rarity: 'epic', unlock: free },
  { id: 'recoveryslides', label: 'Recovery Slides', family: 'Slides', colorway: 'Recovery', img: require('../../assets/character/_src/footwear/16_recovery_slides.png'), layout: { w: 0.9071, top: 0.8411, dx: -0.0161 }, rarity: 'rare', unlock: free },
];

export const OUTFIT_SUITS = [
  { id: 'o58o', label: 'Starlit mage robes', img: require('../../assets/character/outfit/ofS2.png'), layout: { w: 1.0267, top: 0.3185, dx: 0.0117 }, fit: 'onepiece', hidesBottom: true, rarity: 'common', unlock: free },
  { id: 'o59o', label: 'Shinobi gi', img: require('../../assets/character/outfit/ofS3.png'), layout: { w: 0.9887, top: 0.3172 }, fit: 'onepiece', hidesBottom: true, rarity: 'common', unlock: free },
  { id: 'o60o', label: 'Astronaut suit', img: require('../../assets/character/outfit/ofS4.png'), layout: { w: 1.0317, top: 0.2919, dx: 0.0033 }, fit: 'onepiece', hidesBottom: true, rarity: 'common', unlock: free },
  { id: 'o61o', label: 'Pirate coat', img: require('../../assets/character/outfit/ofS5.png'), layout: { w: 1.0663, top: 0.3172, dx: 0.0033 }, fit: 'onepiece', hidesBottom: true, rarity: 'rare', unlock: runs(3, 'Finish 3 runs') },
  { id: 'o64o', label: 'Leaf fairy dress', img: require('../../assets/character/outfit/ofS8.png'), layout: { w: 1.024, top: 0.3209, dx: 0.0017 }, fit: 'onepiece', hidesBottom: true, rarity: 'common', unlock: free },
  { id: 'o66o', label: 'Valkyrie armour', img: require('../../assets/character/outfit/ofS9.png'), layout: { w: 1.0456, top: 0.3159, dx: 0.0212 }, fit: 'onepiece', hidesBottom: true, rarity: 'common', unlock: free },
  { id: 'o69o', label: 'Tactical rig', img: require('../../assets/character/outfit/ofS10.png'), layout: { w: 1.0065, top: 0.3053, dx: 0.0117 }, fit: 'onepiece', hidesBottom: true, rarity: 'epic', unlock: dist(25, 'Run 25 km total') },
  { id: 'o79o', label: 'Storm parka', img: require('../../assets/character/outfit/ofS11.png'), layout: { w: 0.9911, top: 0.2772, dx: 0.005 }, fit: 'onepiece', hidesBottom: true, rarity: 'common', unlock: free },
];
