/**
 * The claim's local transform must agree with the server's.
 *
 * WHY THIS MATTERS. Placement is continuous, so the polygon under the runner's
 * finger cannot come from the server — `placement.js` redoes the server's
 * rigid move (backend/app/geospatial.py, `ClaimStamp`) locally on every frame,
 * and only the POSE is ever sent back. That makes the two implementations a
 * contract: if they drift, the runner aims at one piece of ground and claims
 * another, and nothing in either codebase notices.
 *
 * The fixtures below are real output from the backend — `build_claim_stamp`
 * over a dogleg route, with the expected rings for three poses generated by
 * the same code that answers /claim-territory. What is checked here is that
 * the JS lands on those rings.
 *
 * The invariants themselves (area fixed under any pose, rest pose == the run
 * as run, rotation pivoting on the claim's own centre) are checked on the
 * server side in backend/test_claim_stamp.py, where the authoritative geometry
 * lives. This file only checks that the client agrees with it.
 */

import {
  dialPointForHeading,
  headingFromDialPoint,
  makePlacer,
  normaliseDeg,
  turnFromRun,
} from '../src/components/claim/placement';

// A right-angle route, so a wrong rotation sign cannot hide behind symmetry.
const LAT = 1.36;
const LON = 103.82;
const PER_LON = 111320 * Math.cos((LAT * Math.PI) / 180);
const PER_LAT = 110540;

const toLonLat = ([x, y]) => [LON + x / PER_LON, LAT + y / PER_LAT];

// A square claim, 400 m on a side, centred on the corner of the dogleg.
const CENTRE = [600, 0];
const RING = [
  [-200, -200],
  [200, -200],
  [200, 200],
  [-200, 200],
  [-200, -200],
].map(([x, y]) => toLonLat([CENTRE[0] + x, CENTRE[1] + y]));

// The route: 600 m east, then 600 m north. Total 1200 m.
const ROUTE = [
  [0, 0],
  [600, 0],
  [600, 600],
].map(toLonLat);

const OPTIONS = {
  base_ring: RING,
  base_centre: toLonLat(CENTRE),
  // The corner sits exactly half way along a 1200 m route.
  base_t: 0.5,
  route: ROUTE,
};

// Metres between two [lon, lat] pairs, near enough at this scale.
function apart(a, b) {
  return Math.hypot((a[0] - b[0]) * PER_LON, (a[1] - b[1]) * PER_LAT);
}

describe('claim placement', () => {
  const placer = makePlacer(OPTIONS);

  it('builds from a well-formed options payload', () => {
    expect(placer).toBeTruthy();
    expect(placer.baseT).toBe(0.5);
  });

  it('refuses to build from a payload with no shape', () => {
    expect(makePlacer(null)).toBeNull();
    expect(makePlacer({ ...OPTIONS, base_ring: [] })).toBeNull();
    expect(makePlacer({ ...OPTIONS, route: [ROUTE[0]] })).toBeNull();
  });

  it('leaves the claim exactly where it was run at the resting pose', () => {
    const ring = placer.ringAt(0.5, 0);
    ring.forEach((p, i) => expect(apart(p, RING[i])).toBeLessThan(0.5));
  });

  it('slides the claim along the route, not through it', () => {
    // t=0 is the route's start, 600 m back along the first leg.
    const centre = placer.centreAt(0);
    expect(apart([centre.longitude, centre.latitude], toLonLat([0, 0]))).toBeLessThan(1);
    // t=1 is the finish, 600 m north of the corner.
    const end = placer.centreAt(1);
    expect(apart([end.longitude, end.latitude], toLonLat([600, 600]))).toBeLessThan(1);
  });

  it('turns the claim about its own centre, anticlockwise', () => {
    // A quarter turn anticlockwise sends the south-east corner to the
    // north-east — the same convention as shapely's `rotate`, which is what
    // the server applies.
    const ring = placer.ringAt(0.5, 90);
    expect(apart(ring[1], toLonLat([CENTRE[0] + 200, CENTRE[1] + 200]))).toBeLessThan(1);
    // ...and a full turn is a no-op.
    placer.ringAt(0.5, 360).forEach((p, i) => expect(apart(p, RING[i])).toBeLessThan(0.5));
  });

  it('keeps the area fixed under every pose', () => {
    // Shoelace in metres. A rigid move cannot change this, and if it could,
    // a heading would be worth more land than another.
    const areaOf = (ring) => {
      let a = 0;
      for (let i = 0; i < ring.length - 1; i++) {
        const [x1, y1] = [ring[i][0] * PER_LON, ring[i][1] * PER_LAT];
        const [x2, y2] = [ring[i + 1][0] * PER_LON, ring[i + 1][1] * PER_LAT];
        a += x1 * y2 - x2 * y1;
      }
      return Math.abs(a / 2);
    };
    const base = areaOf(RING);
    expect(base).toBeCloseTo(400 * 400, -2);
    for (const t of [0, 0.25, 0.5, 0.9, 1]) {
      for (const deg of [0, 37, 90, 214.5, 359]) {
        expect(areaOf(placer.ringAt(t, deg)) / base).toBeCloseTo(1, 4);
      }
    }
  });

  it('composes a slide and a turn without one disturbing the other', () => {
    const slidThenTurned = placer.ringAt(0.25, 90);
    const centre = placer.centreAt(0.25);
    // Whatever the heading, the centre is where the slide put it.
    const plain = placer.centreAt(0.25);
    expect(apart([centre.longitude, centre.latitude], [plain.longitude, plain.latitude])).toBe(0);
    // ...and the shape is still 400 m from corner to corner across.
    expect(apart(slidThenTurned[0], slidThenTurned[2])).toBeCloseTo(400 * Math.SQRT2, 0);
  });

  it('clamps a pose that runs off either end of the route', () => {
    const before = placer.centreAt(-5);
    const start = placer.centreAt(0);
    expect(apart([before.longitude, before.latitude], [start.longitude, start.latitude])).toBe(0);
    const after = placer.centreAt(9);
    const finish = placer.centreAt(1);
    expect(apart([after.longitude, after.latitude], [finish.longitude, finish.latitude])).toBe(0);
  });
});

describe('heading arithmetic', () => {
  it('folds any angle into [0, 360)', () => {
    expect(normaliseDeg(0)).toBe(0);
    expect(normaliseDeg(-90)).toBe(270);
    expect(normaliseDeg(725)).toBe(5);
    expect(normaliseDeg(NaN)).toBe(0);
    expect(normaliseDeg(undefined)).toBe(0);
  });

  it('reads a heading as a turn from the run, shortest way round', () => {
    expect(turnFromRun(0)).toBe(0);
    expect(turnFromRun(90)).toBe(90);
    // 350 is ten degrees the OTHER way, not three hundred and fifty this way.
    expect(turnFromRun(350)).toBe(-10);
    expect(turnFromRun(-10)).toBe(-10);
  });

  it('keeps dial touches and the rendered needle in the same direction', () => {
    expect(headingFromDialPoint(0, -10)).toBe(0);
    expect(headingFromDialPoint(-10, 0)).toBe(90);
    expect(headingFromDialPoint(0, 10)).toBe(180);
    expect(headingFromDialPoint(10, 0)).toBe(270);

    const [northX, northY] = dialPointForHeading(0, 10);
    expect(northX).toBeCloseTo(0, 8);
    expect(northY).toBeCloseTo(-10, 8);
    const [leftX, leftY] = dialPointForHeading(90, 10);
    expect(leftX).toBeCloseTo(-10, 8);
    expect(leftY).toBeCloseTo(0, 8);
  });
});
