"""GENERATED by frontend/scripts/gen-shop-catalog.py — do not edit.

Server-side mirror of the client cosmetics catalogue, used to price
and validate coin purchases. Regenerate whenever cosmetics.js changes;
`node scripts/check-catalog.js` verifies the two are in sync.
"""

PRICE_BY_RARITY = {
    "common": 150,
    "rare": 400,
    "epic": 900,
    "legendary": 2000,
}

# item_id -> (slot, rarity). Ids are unique across slots (enforced by
# check-catalog.js), so a flat map is safe and keeps lookups simple.
SHOP_ITEMS = {
    # --- accessory ---
    "scarf": ("accessory", "common"),  # Scarf
    "goldmedal": ("accessory", "rare"),  # Gold medal
    "hydropack": ("accessory", "rare"),  # Hydration pack
    "hydrovest": ("accessory", "rare"),  # Race vest
    "cape": ("accessory", "epic"),  # Cape
    "champmedal": ("accessory", "epic"),  # Champion medal
    "angelwings": ("accessory", "epic"),  # Angel wings
    "neonwings": ("accessory", "legendary"),  # Neon wings
    "redcape": ("accessory", "epic"),  # Hero cape
    "capepauldron": ("accessory", "legendary"),  # Champion cape
    "starnecklace": ("accessory", "rare"),  # Star pendant
    "ribbonmedal": ("accessory", "rare"),  # Ribbon medal
    "greenscarf": ("accessory", "common"),  # Knit scarf
    "tealscarf": ("accessory", "common"),  # Winter scarf
    "fannypack": ("accessory", "common"),  # Bum bag
    "gaiter": ("accessory", "common"),  # Neck gaiter
    "headset": ("accessory", "rare"),  # Headset
    "katanas": ("accessory", "epic"),  # Twin blades
    # --- bottom ---
    "pants": ("bottom", "common"),  # Pants
    "shorts": ("bottom", "common"),  # Shorts
    "skirt": ("bottom", "common"),  # Skirt
    "cargos": ("bottom", "rare"),  # Cargos
    "fbtshorts": ("bottom", "common"),  # Runner shorts
    "trackpants": ("bottom", "common"),  # Track pants
    "leggings": ("bottom", "common"),  # Leggings
    "bikeshorts": ("bottom", "common"),  # Bike shorts
    "tennisskirt": ("bottom", "rare"),  # Tennis skirt
    "overalls": ("bottom", "rare"),  # Overalls
    "khakishorts": ("bottom", "common"),  # Khaki shorts
    "rippedjeans": ("bottom", "rare"),  # Ripped jeans
    "cargoshorts": ("bottom", "common"),  # Cargo shorts
    "lightjeans": ("bottom", "common"),  # Light jeans
    "trackpants2": ("bottom", "common"),  # Stripe track pants
    "checkered": ("bottom", "rare"),  # Checkered pants
    "denimshorts": ("bottom", "common"),  # Denim shorts
    "bluejeans": ("bottom", "common"),  # Blue jeans
    "leatherpants": ("bottom", "epic"),  # Leather pants
    "sweatpants": ("bottom", "common"),  # Sweatpants
    # --- face ---
    "smiley": ("face", "common"),  # Smiley
    "neutral": ("face", "common"),  # Neutral
    "chill": ("face", "common"),  # Chill
    "laugh": ("face", "common"),  # Laugh
    "grump": ("face", "common"),  # Grump
    "wink": ("face", "common"),  # Wink
    "whoa": ("face", "rare"),  # Whoa
    "sleepy": ("face", "rare"),  # Sleepy
    "blush": ("face", "epic"),  # Blush
    "content": ("face", "common"),  # Content
    "determined": ("face", "common"),  # Game face
    "tongueout": ("face", "common"),  # Cheeky
    "stareyes": ("face", "rare"),  # Star eyes
    "hearteyes": ("face", "rare"),  # Heart eyes
    "exhausted": ("face", "rare"),  # Cooked
    # --- glasses ---
    "rounds": ("glasses", "common"),  # Rounds
    "rects": ("glasses", "rare"),  # Rects
    "wayfarer": ("glasses", "common"),  # Wayfarers
    "roundgold": ("glasses", "common"),  # Round golds
    "halfframe": ("glasses", "rare"),  # Half-frames
    "heart": ("glasses", "rare"),  # Heart sunnies
    "shieldvisor": ("glasses", "rare"),  # Shield visor
    "cleargoggles": ("glasses", "rare"),  # Clear goggles
    "sportshield": ("glasses", "epic"),  # Sport shield
    "skigoggles": ("glasses", "epic"),  # Ski goggles
    "starglasses": ("glasses", "rare"),  # Star shades
    "steampunk": ("glasses", "epic"),  # Steampunk goggles
    "hexshades": ("glasses", "rare"),  # Hex shades
    "cateye": ("glasses", "rare"),  # Cat-eye
    "pixelshades": ("glasses", "epic"),  # Pixel shades
    "aviators": ("glasses", "common"),  # Aviators
    "eyepatch": ("glasses", "rare"),  # Eyepatch
    "clownglasses": ("glasses", "rare"),  # Clown glasses
    "sleepmask": ("glasses", "common"),  # Sleep mask
    "heromask": ("glasses", "epic"),  # Hero mask
    # --- hair ---
    "curtains": ("hair", "common"),  # Curtains
    "middlepart": ("hair", "common"),  # Middle part
    "swept": ("hair", "common"),  # Swept
    "curls": ("hair", "common"),  # Curls
    "pixie": ("hair", "common"),  # Pixie
    "bluntbob": ("hair", "common"),  # Blunt bob
    "fringebob": ("hair", "common"),  # Fringe bob
    "sleeklong": ("hair", "common"),  # Sleek long
    "messy": ("hair", "common"),  # Messy
    "longwaves": ("hair", "common"),  # Long waves
    "flow": ("hair", "common"),  # Flow
    "ravenlong": ("hair", "common"),  # Straight long
    "bangs": ("hair", "common"),  # Bangs
    "roundfro": ("hair", "rare"),  # Round fro
    "softwaves": ("hair", "rare"),  # Soft waves
    "topknot": ("hair", "rare"),  # Top knot
    "sidepony": ("hair", "rare"),  # Side pony
    "fringebun": ("hair", "rare"),  # Fringe bun
    "highpony": ("hair", "rare"),  # High pony
    "surfer": ("hair", "epic"),  # Surfer
    "spacebuns": ("hair", "epic"),  # Space buns
    "hijab": ("hair", "common"),  # Sports hijab
    "curtainlong": ("hair", "common"),  # Curtain long
    "twoblock": ("hair", "common"),  # Two-block
    "buzz": ("hair", "common"),  # Buzz cut
    "braids": ("hair", "common"),  # Braided pigtails
    "bunstrands": ("hair", "common"),  # Soft bun
    "comma": ("hair", "rare"),  # Comma fringe
    "texturedcrop": ("hair", "rare"),  # Textured crop
    # --- headwear ---
    "cap": ("headwear", "common"),  # Cap
    "sweatband": ("headwear", "common"),  # Sweatband
    "beanie": ("headwear", "common"),  # Beanie
    "bandana": ("headwear", "common"),  # Bandana
    "snapback": ("headwear", "common"),  # Backwards cap
    "bucket": ("headwear", "common"),  # Bucket hat
    "pombeanie": ("headwear", "rare"),  # Pom beanie
    "visor": ("headwear", "rare"),  # Visor
    "skatehelmet": ("headwear", "rare"),  # Skate helmet
    "hardhat": ("headwear", "rare"),  # Hard hat
    "bikehelmet": ("headwear", "epic"),  # Bike helmet
    "crown": ("headwear", "epic"),  # Crown
    "frogbeanie": ("headwear", "rare"),  # Frog beanie
    "wizardhat": ("headwear", "epic"),  # Wizard hat
    "antlers": ("headwear", "rare"),  # Antlers
    "aviatorcap": ("headwear", "rare"),  # Aviator cap
    "chefhat": ("headwear", "rare"),  # Chef hat
    "cowboyhat": ("headwear", "rare"),  # Cowboy hat
    "piratehat": ("headwear", "epic"),  # Pirate hat
    "headdress": ("headwear", "epic"),  # Feather crown
    "gradcap": ("headwear", "rare"),  # Grad cap
    "bowler": ("headwear", "common"),  # Bowler
    "sunhat": ("headwear", "common"),  # Sun hat
    "tiara": ("headwear", "epic"),  # Tiara
    "turban": ("headwear", "rare"),  # Turban
    "catears": ("headwear", "common"),  # Cat ears
    "pinkbow": ("headwear", "common"),  # Bow
    "flowercrown": ("headwear", "common"),  # Flower crown
    "earmuffs": ("headwear", "common"),  # Earmuffs
    # --- top ---
    "tee": ("top", "common"),  # Tee
    "crewtee": ("top", "common"),  # Crew tee
    "pockettee": ("top", "common"),  # Pocket tee
    "stripetee": ("top", "common"),  # Stripe tee
    "daisydress": ("top", "common"),  # Daisy dress
    "overshirt": ("top", "rare"),  # Overshirt
    "sweater": ("top", "rare"),  # Sweater
    "singlet": ("top", "common"),  # Race singlet
    "oversized": ("top", "common"),  # Oversized tee
    "camisole": ("top", "common"),  # Camisole
    "polo": ("top", "common"),  # PE polo
    "croptee": ("top", "common"),  # Crop tee
    "windbreaker": ("top", "rare"),  # Windbreaker
    "stripedtee": ("top", "common"),  # Striped tee
    "sportpolo": ("top", "common"),  # Sport polo
    "greyhoodie": ("top", "common"),  # Hoodie
    "bomber": ("top", "rare"),  # Bomber jacket
    "denimjacket": ("top", "rare"),  # Denim jacket
    "cardigan": ("top", "common"),  # Cardigan
    "labcoat": ("top", "rare"),  # Lab coat
    "judogi": ("top", "rare"),  # Judo gi
    "utilityvest": ("top", "rare"),  # Utility vest
    "sailortop": ("top", "common"),  # Sailor top
    "puffer": ("top", "rare"),  # Puffer jacket
}


def price_of(item_id: str) -> int | None:
    """Coin price, or None if the item isn't purchasable."""
    entry = SHOP_ITEMS.get(item_id)
    if not entry:
        return None
    return PRICE_BY_RARITY.get(entry[1])
