"""GENERATED by frontend/scripts/gen-shop-catalog.py — do not edit.

Server-side mirror of the client cosmetics catalogue, used to price
and validate coin purchases. Regenerate whenever cosmetics.js changes;
`node scripts/check-catalog.js` verifies the two are in sync.
"""

PRICE_BY_RARITY = {
    "common": 150,
    "rare": 400,
    "epic": 900,
    "legendary": 2000,
}

# item_id -> (slot, rarity). Ids are unique across slots (enforced by
# check-catalog.js), so a flat map is safe and keeps lookups simple.
SHOP_ITEMS = {
    # --- accessory ---
    "cape": ("accessory", "epic"),  # Cape
    "angelwings": ("accessory", "epic"),  # Angel wings
    "redcape": ("accessory", "epic"),  # Hero cape
    "starnecklace": ("accessory", "rare"),  # Star pendant
    "greenscarf": ("accessory", "common"),  # Knit scarf
    "tealscarf": ("accessory", "common"),  # Winter scarf
    "gaiter": ("accessory", "common"),  # Neck gaiter
    "lacecollar": ("accessory", "rare"),  # Lace collar
    "dogtags": ("accessory", "rare"),  # Dog tags
    "pearlcollar": ("accessory", "rare"),  # Pearl collar
    "pearls": ("accessory", "common"),  # Pearl strand
    "charmchain": ("accessory", "common"),  # Charm chain
    "lei": ("accessory", "common"),  # Flower lei
    "sailorcollar": ("accessory", "common"),  # Sailor collar
    "bowtie": ("accessory", "common"),  # Bow tie
    "necktie": ("accessory", "common"),  # Necktie
    "medallion": ("accessory", "epic"),  # Medallion
    "trophychain": ("accessory", "epic"),  # Trophy chain
    "silvermedal": ("accessory", "rare"),  # Silver medal
    "wintscarf": ("accessory", "common"),  # Wool scarf
    "candyscarf": ("accessory", "common"),  # Candy scarf
    "redscarf": ("accessory", "common"),  # Red scarf
    "pageantsash": ("accessory", "rare"),  # Pageant sash
    "racesash": ("accessory", "rare"),  # Race sash
    "harness": ("accessory", "rare"),  # Race harness
    "fairywings": ("accessory", "legendary"),  # Fairy wings
    "messengerbag": ("accessory", "common"),  # Messenger bag
    "handbag": ("accessory", "common"),  # Handbag
    "sheriffstar": ("accessory", "rare"),  # Sheriff star
    "royalrobe": ("accessory", "legendary"),  # Royal robe
    "lacebib": ("accessory", "common"),  # Lace bib
    # --- bottom ---
    "wb065": ("bottom", "rare"),  # Yellow cargo shorts
    "wb105": ("bottom", "rare"),  # Sand chinos
    # --- face ---
    "wink": ("face", "common"),  # Wink
    "tongueout": ("face", "common"),  # Cheeky
    "stareyes": ("face", "rare"),  # Star eyes
    "sleepy": ("face", "rare"),  # Sleepy
    "hearteyes": ("face", "rare"),  # Dizzy
    "exhausted": ("face", "rare"),  # Cooked
    "blush": ("face", "epic"),  # Blush
    "smirk": ("face", "common"),  # Smirk
    "beam": ("face", "common"),  # Beaming
    "angry": ("face", "common"),  # Angry
    "joy": ("face", "common"),  # Joy
    "sob": ("face", "rare"),  # Sob
    "sly": ("face", "rare"),  # Sly
    # --- footwear ---
    "wf015": ("footwear", "rare"),  # Black knit runners
    "wf020": ("footwear", "rare"),  # Lavender sneakers
    "wf022": ("footwear", "epic"),  # Black and gold high tops
    "wf025": ("footwear", "rare"),  # Mint canvas sneakers
    "wf030": ("footwear", "rare"),  # Berry sneakers
    "wf040": ("footwear", "rare"),  # Teal trim slip ons
    "wf045": ("footwear", "rare"),  # Bow espadrilles
    "wf050": ("footwear", "rare"),  # Navy clogs
    "wf055": ("footwear", "epic"),  # Lilac Mary Janes
    "wf060": ("footwear", "rare"),  # Red canvas high tops
    "wf070": ("footwear", "rare"),  # Cream strap shoes
    "wf085": ("footwear", "rare"),  # Burgundy strap heels
    # --- glasses ---
    "rounds": ("glasses", "common"),  # Rounds
    "wayfarer": ("glasses", "common"),  # Wayfarers
    "roundgold": ("glasses", "common"),  # Round golds
    "halfframe": ("glasses", "rare"),  # Half frames
    "heart": ("glasses", "rare"),  # Heart sunnies
    "shieldvisor": ("glasses", "rare"),  # Shield visor
    "skigoggles": ("glasses", "epic"),  # Ski goggles
    "starglasses": ("glasses", "rare"),  # Star shades
    "hexshades": ("glasses", "rare"),  # Hex shades
    "cateye": ("glasses", "rare"),  # Cat eye
    "pixelshades": ("glasses", "epic"),  # Pixel shades
    "aviators": ("glasses", "common"),  # Aviators
    "eyepatch": ("glasses", "rare"),  # Eyepatch
    "clownglasses": ("glasses", "rare"),  # Clown glasses
    "sleepmask": ("glasses", "common"),  # Sleep mask
    "heromask": ("glasses", "epic"),  # Hero mask
    "weldgoggles": ("glasses", "epic"),  # Welder goggles
    "pearlspecs": ("glasses", "rare"),  # Pearl specs
    "butterfly": ("glasses", "rare"),  # Butterfly shades
    "tintgoggles": ("glasses", "rare"),  # Tint goggles
    # --- hair ---
    "longwaves": ("hair", "common"),  # Long waves
    "ravenlong": ("hair", "common"),  # Straight long
    "bangs": ("hair", "common"),  # Bangs
    "softwaves": ("hair", "rare"),  # Soft waves
    "sidepony": ("hair", "rare"),  # Side pony
    "fringebun": ("hair", "rare"),  # Fringe bun
    "highpony": ("hair", "rare"),  # High pony
    "spacebuns": ("hair", "epic"),  # Space buns
    "braids": ("hair", "common"),  # Braided pigtails
    "bunstrands": ("hair", "common"),  # Soft bun
    "comma": ("hair", "rare"),  # Comma fringe
    "texturedcrop": ("hair", "rare"),  # Textured crop
    "bigafro": ("hair", "rare"),  # Big afro
    "highbun": ("hair", "rare"),  # High bun
    # --- headwear ---
    "beanie": ("headwear", "common"),  # Beanie
    "snapback": ("headwear", "common"),  # Backwards cap
    "bucket": ("headwear", "common"),  # Bucket hat
    "visor": ("headwear", "rare"),  # Visor
    "skatehelmet": ("headwear", "rare"),  # Skate helmet
    "hardhat": ("headwear", "rare"),  # Hard hat
    "frogbeanie": ("headwear", "rare"),  # Frog beanie
    "wizardhat": ("headwear", "epic"),  # Wizard hat
    "antlers": ("headwear", "rare"),  # Antlers
    "aviatorcap": ("headwear", "rare"),  # Aviator cap
    "chefhat": ("headwear", "rare"),  # Chef hat
    "cowboyhat": ("headwear", "rare"),  # Cowboy hat
    "piratehat": ("headwear", "epic"),  # Pirate hat
    "headdress": ("headwear", "epic"),  # Feather crown
    "gradcap": ("headwear", "rare"),  # Grad cap
    "bowler": ("headwear", "common"),  # Bowler
    "turban": ("headwear", "rare"),  # Turban
    "flowercrown": ("headwear", "common"),  # Flower crown
    "catbeanie": ("headwear", "rare"),  # Cat beanie
    "boater": ("headwear", "common"),  # Boater
    "jockeycap": ("headwear", "common"),  # Jockey cap
    "newsboy": ("headwear", "common"),  # Newsboy cap
    "flatcap": ("headwear", "common"),  # Flat cap
    "captaincap": ("headwear", "rare"),  # Captain cap
    "sailorhat": ("headwear", "common"),  # Sailor hat
    "nursecap": ("headwear", "common"),  # Nurse cap
    "sultanturban": ("headwear", "epic"),  # Jewel turban
    "ushanka": ("headwear", "rare"),  # Ushanka
    "bunnyears": ("headwear", "common"),  # Bunny ears
    "devilhorns": ("headwear", "rare"),  # Devil horns
    "heartbopper": ("headwear", "common"),  # Heart boppers
    "cherrybopper": ("headwear", "common"),  # Cherry boppers
    "spikecrown": ("headwear", "rare"),  # Spike band
    "bowberet": ("headwear", "common"),  # Bow beret
    "bowcap": ("headwear", "common"),  # Bow cap
    "maidband": ("headwear", "common"),  # Maid band
    "angelheart": ("headwear", "epic"),  # Angel heart
    "ballcap": ("headwear", "common"),  # Ball cap
    "canvasbucket": ("headwear", "common"),  # Canvas bucket
    "runvisor": ("headwear", "common"),  # Run visor
    "headphones": ("headwear", "rare"),  # Headphones
    "sitehelmet": ("headwear", "rare"),  # Site helmet
    "witchhat": ("headwear", "epic"),  # Witch hat
    "puffmuffs": ("headwear", "common"),  # Puff earmuffs
    "flatsnap": ("headwear", "common"),  # Flat snapback
    "gardenhat": ("headwear", "common"),  # Garden hat
    "wideband": ("headwear", "common"),  # Wide band
    "tiedbandana": ("headwear", "common"),  # Tied bandana
    "jeweltiara": ("headwear", "epic"),  # Jewel tiara
    "tophat": ("headwear", "epic"),  # Top hat
    "fedora": ("headwear", "rare"),  # Fedora
    "cowpokehat": ("headwear", "rare"),  # Cowpoke hat
    "cheftoque": ("headwear", "rare"),  # Chef toque
    "mortarboard": ("headwear", "rare"),  # Mortarboard
    "bloomcrown": ("headwear", "common"),  # Bloom crown
    "rabbitears": ("headwear", "common"),  # Rabbit ears
    "tricorn": ("headwear", "epic"),  # Tricorn
    "flightcap": ("headwear", "rare"),  # Flight cap
    "firehelmet": ("headwear", "rare"),  # Fire helmet
    "golfcap": ("headwear", "common"),  # Golf cap
    "trapperhat": ("headwear", "rare"),  # Trapper hat
    "unicornhorn": ("headwear", "epic"),  # Unicorn horn
    "haloring": ("headwear", "legendary"),  # Halo ring
    "loveboppers": ("headwear", "common"),  # Love boppers
    "officercap": ("headwear", "rare"),  # Officer cap
    "navycap": ("headwear", "common"),  # Navy cap
    "ribboncap": ("headwear", "common"),  # Ribbon cap
    "scrumcap": ("headwear", "rare"),  # Scrum cap
    "sunbowhat": ("headwear", "common"),  # Sun hat
    "santahat": ("headwear", "rare"),  # Santa hat
    "rodeohat": ("headwear", "rare"),  # Rodeo hat
    "headwrap": ("headwear", "rare"),  # Head wrap
    "vikinghelm": ("headwear", "epic"),  # Viking helm
    "mobcap": ("headwear", "common"),  # Mob cap
    "clochehat": ("headwear", "common"),  # Cloche hat
    "bowwrap": ("headwear", "common"),  # Bow wrap
    "minerhelmet": ("headwear", "rare"),  # Miner helmet
    "fez": ("headwear", "rare"),  # Fez
    "paradeshako": ("headwear", "epic"),  # Parade shako
    "jestercap": ("headwear", "epic"),  # Jester cap
    "weddingveil": ("headwear", "epic"),  # Wedding veil
    "scallopband": ("headwear", "common"),  # Scallop band
    "pinupwrap": ("headwear", "common"),  # Pin up wrap
    "derbyhat": ("headwear", "common"),  # Derby hat
    "laurelcrown": ("headwear", "epic"),  # Laurel crown
    "samuraihelm": ("headwear", "epic"),  # Samurai helm
    "skullcap": ("headwear", "common"),  # Skull cap
    "boaterhat": ("headwear", "common"),  # Boater hat
    "pearltiara": ("headwear", "rare"),  # Pearl tiara
    "swimcap": ("headwear", "common"),  # Swim cap
    "bigbow": ("headwear", "common"),  # Big bow
    # --- top ---
    "daisydress": ("top", "common"),  # Daisy dress
    "overshirt": ("top", "rare"),  # Overshirt
    "sweater": ("top", "rare"),  # Sweater
    "oversized": ("top", "common"),  # Oversized tee
    "camisole": ("top", "common"),  # Camisole
    "polo": ("top", "common"),  # PE polo
    "windbreaker": ("top", "rare"),  # Windbreaker
    "bomber": ("top", "rare"),  # Bomber jacket
    "denimjacket": ("top", "rare"),  # Denim jacket
    "cardigan": ("top", "common"),  # Cardigan
    "judogi": ("top", "rare"),  # Judo gi
    "utilityvest": ("top", "rare"),  # Utility vest
    "sailortop": ("top", "common"),  # Sailor top
    "letterman": ("top", "rare"),  # Letterman jacket
    "teamjersey": ("top", "rare"),  # Team jersey
    "cyclejersey": ("top", "rare"),  # Cycle jersey
    "puffervest": ("top", "rare"),  # Puffer vest
    "blackvest": ("top", "rare"),  # Tech vest
    "pastelcardi": ("top", "common"),  # Pastel cardigan
    "snowpuffer": ("top", "rare"),  # Snow puffer
    "sleevehoodie": ("top", "common"),  # Sleeveless hoodie
    "frilltop": ("top", "common"),  # Frill top
    "maidapron": ("top", "rare"),  # Maid apron
    "bowcami": ("top", "common"),  # Bow cami
    "o3t": ("top", "rare"),  # Yellow zip hoodie
    "o9t": ("top", "epic"),  # Sea glass tee
    "o13t": ("top", "rare"),  # Yellow ringer tee
    "o14t": ("top", "epic"),  # Black loose tee
    "o18t": ("top", "rare"),  # Mint loose tee
    "o48t": ("top", "rare"),  # Lilac polo
    "o54t": ("top", "rare"),  # Blush shrug
    "o68t": ("top", "rare"),  # Black hoodie
    "o78t": ("top", "rare"),  # Jet black hoodie
    "o88t": ("top", "rare"),  # Ash hooded puffer
    "o89t": ("top", "rare"),  # Green bomber jacket
    "o93t": ("top", "rare"),  # Navy blazer
    "o94t": ("top", "rare"),  # Cream striped knit
    "k6t": ("top", "rare"),  # Blue track hoodie
    "k12t": ("top", "rare"),  # Blush crop jacket
    "o61o": ("top", "rare"),  # Pirate coat
    "o69o": ("top", "epic"),  # Tactical rig
}


def price_of(item_id: str) -> int | None:
    """Coin price, or None if the item isn't purchasable."""
    entry = SHOP_ITEMS.get(item_id)
    if not entry:
        return None
    return PRICE_BY_RARITY.get(entry[1])
