"""Cut the hand-drawn box frames out of BigFramesColored into nine-slice strips.

The pack ships one 500x800 sheet per animation frame with nine boxes scattered
across it, drawn as wobbly outlines that BOIL — the same box redrawn three
times, so cycling the three reads as a living line rather than a static border.

It ships that sheet TWICE: an outline-only "Transparent" cut and a "Filled" cut
where the same boxes have a white interior. This script uses both, because a
drawn box needs both halves:

  * INK — the outline, from the transparent sheet. Tintable, drawn on top.
  * PAPER — the filled silhouette, from the filled sheet, recoloured to flat
    white. It is the box's INSIDE, and it is a separate layer because the two
    are coloured independently: the ink picks up a clan colour or the theme's
    line colour while the paper stays the surface colour underneath it.

    Without it, anything behind a frame has to paint its own background, and a
    rectangle behind a wobbly outline pokes out at every corner. The paper
    silhouette runs to the OUTER edge of the ink and the ink is drawn over it,
    so the visible white lands exactly inside the line, corners and all.

What the cut does to each box:

  * ONE BOX PER FILE, as a horizontal three frame strip. The crop is the UNION
    bounding box across all three frames, so the boil stays registered — crop
    each frame to its own extent and the box would jitter around its own centre
    instead of the line wobbling in place. Ink and paper take the SAME crop, so
    the two layers register against each other as well.

  * STRAYS REMOVED. Several boxes have a loose tick or a second line parked
    beside them on the sheet (an underline under box 0, a bare corner mark under
    the banner). Only the largest connected component of each region is kept,
    which is the outline loop itself.

  * NINE SLICE INSETS MEASURED, not guessed. `insets` is how much of each edge
    is corner and must never be stretched. It is read off the art by finding
    where the outline's edge run becomes straight; see `measure_insets`.

  * INK DEPTH MEASURED SEPARATELY. `ink` is how thick the line is on each side.
    That is a DIFFERENT number from the inset and it is the one padding wants:
    an inset says how much art must not be stretched, ink depth says how far in
    content has to sit to clear the line. Padding from the inset — which is what
    the app used to do — puts 30pt of air under a banner whose line is 8pt
    thick, and that is what made framed blocks look wrongly sized.

  * DERIVED MIRRORS. A speech bubble's tail points one way; a banner clips one
    corner. Those are the same drawing needed facing the other way, so they are
    generated by flipping the strip per frame (never the whole strip, which
    would reverse the boil order) and swapping the insets to match.

Run: python scripts/animations/cut_frames.py
Writes: assets/frames/<id>.png, <id>_paper.png, plus frame-manifest.json.
"""
from __future__ import annotations

import io
import json
import zipfile
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

# The pack has lived in a couple of places. Whichever copy is on this machine is
# the one to cut from — they are the same download, and hard-coding one path
# means the script dies on a machine that filed it elsewhere.
SOURCE_CANDIDATES = (
    Path(r"D:\downloads\BigFramesColored.zip"),
    Path(r"C:\Users\user\Desktop\animations\BigFramesColored.zip"),
)
INK_MEMBER = "BigFramesColored/AnimatedBoxes_Transparent/AnimatedColoredBoxesTransparent_frame{:04d}.png"
PAPER_MEMBER = "BigFramesColored/AnimatedBoxes_Filled/AnimatedColoredBoxesFilled_frame{:04d}.png"
FRAME_COUNT = 3

# Which regions of the sheet become which frame, and what each is FOR. The
# region index is the order `find_objects` returns them in, which is stable for
# a fixed input sheet; the QA contact sheet is how a mismatch is caught.
#
# `trim`, `erase` and `floor` are hand measured, and they exist because the
# obvious automatic approach does not work here.
#
#   `trim`  crop box in region coordinates, or None for the whole region.
#           Several boxes have a loose mark parked beside them — a bare vertical
#           line next to the panel, a corner tick under the banner — and dropping
#           all but the largest connected component does not remove them, because
#           ACROSS THE THREE BOIL FRAMES the stray and the box touch and become
#           one component. There is no separation left to find, so the cut is
#           given explicitly.
#   `rule`  a horizontal rule to remove, as (top, bottom, donor). The band's
#           rows are REPLACED by a copy of row `donor`, not blanked.
#
#           Blanking a rectangle was the first attempt and it leaves stubs: the
#           rule joins the side walls, the walls wobble by a few pixels, so any
#           fixed x range either clips the wall or leaves the last few pixels of
#           rule stuck to it — and those stubs land in the left and right edge
#           slices, which stretch vertically, so a 3px tick becomes a bar down
#           the whole side of the box. Copying a clean row takes the walls with
#           it and cannot leave a stub. It also flattens the wobble across those
#           few rows, which costs nothing: they sit in the stretchable middle,
#           where the source is smeared vertically regardless.
#   `floor` minimum inset per side. The other way to deal with an interior rule
#           is to keep it and make it part of an EDGE band, which stretches on
#           one axis only — so the rule stays a rule, at a fixed distance from
#           the edge it belongs to. Used where the rule is the point of the box.
WANTED = {
    0: {
        "id": "frame_note", "name": "Note",
        "purpose": "Wide, with a rule above the bottom edge. Captions and footers.",
        # The rule sits ~20px up from the bottom. Swallowing it into the bottom
        # band keeps it parallel to the edge at any height, instead of letting
        # it drift into the middle of the box as the frame grows.
        # The rule runs across rows 64..73 of a 91 tall box. The band has to
        # reach up past it, or the nine slice puts the rule in the stretchable
        # middle and it drifts away from the edge it belongs to as the box grows.
        "floor": {"bottom": 28},
    },
    1: {
        "id": "frame_panel", "name": "Panel",
        "purpose": "A general box. Cards, sheets, anything squarish.",
        # The right hand vertical at x156..171 is a separate stroke on the
        # sheet, not part of this box.
        "trim": (0, 0, 154, 159),
    },
    2: {
        "id": "frame_label", "name": "Label",
        "purpose": "Short and wide. A line of text, a stat, a chip.",
        "trim": None,
    },
    3: {
        "id": "frame_banner", "name": "Banner",
        "purpose": "Wide, with one corner clipped. Headers and hero rows.",
        # Everything below row 138 is the loose corner tick.
        "trim": (0, 0, 374, 138),
    },
    4: {
        "id": "frame_card", "name": "Card",
        "purpose": "Tall and rounded. Portraits and item tiles.",
        "trim": None,
        # The rule across the middle, replaced by clean wall from row 110. The
        # band is wider than the rule looks: its right end slopes upward for
        # another few rows, and a band that stops at the thick part leaves that
        # tail behind in the stretchable middle. Overshooting is free — these
        # rows are smeared vertically either way.
        "rule": [(134, 158, 110)],
    },
    5: {
        "id": "frame_bubble", "name": "Bubble",
        "purpose": "A speech bubble, tail at the bottom left. Quotes and tips.",
        "trim": None,
    },
    6: {
        "id": "frame_ticket", "name": "Ticket",
        "purpose": "Tall and softly rounded. Vertical slots and list rows.",
        "trim": None,
        # Same call as the card: this box's rule crosses the middle, where the
        # nine slice stretches, so it goes rather than smearing.
        "rule": [(76, 100, 55)],
    },
    7: {
        "id": "frame_badge", "name": "Badge",
        "purpose": "Small and square. Icons and counters.",
        "trim": None,
    },
    8: {
        "id": "frame_stamp", "name": "Stamp",
        "purpose": "Small, with a notch in the bottom left. Tags and markers.",
        "trim": None,
    },
}

# Frames that are an existing drawing facing the other way. A bubble's tail and
# a banner's clipped corner are directional, so the app needs both hands of them
# and there is only one drawing in the pack.
#
#   `mirror`  'x' flips left to right, 'y' top to bottom.
DERIVED = (
    {
        "id": "frame_bubble_right", "name": "Bubble (right)", "of": "frame_bubble", "mirror": "x",
        "purpose": "A speech bubble, tail at the bottom right. The other speaker.",
    },
    {
        "id": "frame_banner_left", "name": "Banner (left)", "of": "frame_banner", "mirror": "x",
        "purpose": "Wide, corner clipped on the left. Mirrors Banner across a row.",
    },
    {
        "id": "frame_header", "name": "Header", "of": "frame_note", "mirror": "y",
        "purpose": "Wide, with a rule below the top edge. Titled blocks.",
    },
    # The rest are not new jobs; they are alternate hands of deliberately
    # asymmetric drawings. Lists and repeated controls look manufactured when
    # every panel leans the same way, even if the boil pose changes. Keeping the
    # mirrors as real assets means the nine-slice geometry (including unequal
    # left/right ink depth) stays honest instead of trying to flip a rendered
    # React Native view after layout.
    {
        "id": "frame_panel_right", "name": "Panel (right)", "of": "frame_panel", "mirror": "x",
        "purpose": "A mirrored general panel. Alternates cards in repeated layouts.",
    },
    {
        "id": "frame_card_right", "name": "Card (right)", "of": "frame_card", "mirror": "x",
        "purpose": "A mirrored portrait card. Alternates tiles and featured cards.",
    },
    {
        "id": "frame_ticket_right", "name": "Ticket (right)", "of": "frame_ticket", "mirror": "x",
        "purpose": "A mirrored ticket. Alternates rows and compact cards.",
    },
    {
        "id": "frame_label_right", "name": "Label (right)", "of": "frame_label", "mirror": "x",
        "purpose": "A mirrored label. Alternates headings and action buttons.",
    },
    {
        "id": "frame_stamp_right", "name": "Stamp (right)", "of": "frame_stamp", "mirror": "x",
        "purpose": "A small stamp with its notch on the opposite side.",
    },
)

# Alpha at or below this is background. The art is anti-aliased, so a hard zero
# would fray the outline and a high threshold would eat the thin strokes.
ALPHA_FLOOR = 12


def find_source() -> Path:
    for candidate in SOURCE_CANDIDATES:
        if candidate.exists():
            return candidate
    raise SystemExit(
        "BigFramesColored.zip not found. Looked in:\n  "
        + "\n  ".join(str(c) for c in SOURCE_CANDIDATES)
    )


def load_frames(source: Path) -> tuple[list[Image.Image], list[Image.Image]]:
    """The outline sheets and the filled sheets, frame for frame."""
    with zipfile.ZipFile(source) as archive:
        def read(member):
            return [
                Image.open(io.BytesIO(archive.read(member.format(i)))).convert("RGBA")
                for i in range(FRAME_COUNT)
            ]
        return read(INK_MEMBER), read(PAPER_MEMBER)


def alpha_union(images: list[Image.Image]) -> np.ndarray:
    """Where any of the boil frames has ink. Everything measures on this.

    Measuring on frame 0 alone is the bug that made the first cut look broken:
    the strip is cropped to the union, so in any ONE frame the line can sit
    several pixels in from its own canvas edge.
    """
    mask = np.zeros(images[0].size[::-1], bool)
    for image in images:
        mask |= np.array(image)[:, :, 3] > ALPHA_FLOOR
    return mask


def regions(frames: list[Image.Image]) -> list[tuple[int, int, int, int]]:
    """Bounding boxes of every box on the sheet, across all frames at once."""
    mask = alpha_union(frames)
    # Dilated only for FINDING regions — a wobbly outline has hairline breaks
    # that would otherwise split one box into four arcs. The crop below uses
    # the undilated mask, so this cannot fatten the art.
    labels, _ = ndimage.label(ndimage.binary_dilation(mask, np.ones((5, 5))))
    found = []
    for span in ndimage.find_objects(labels):
        y, x = span
        if x.stop - x.start < 12 or y.stop - y.start < 12:
            continue
        found.append((x.start, y.start, x.stop, y.stop))
    return found


def isolate(ink_frames, paper_frames, box):
    """Crop one region to its box, dropping anything parked beside it.

    The component is found on the FILLED sheet, not the outline: a filled box is
    one solid blob, so "the biggest thing here" is unambiguous, whereas on the
    outline it is a thin loop whose area is comparable to a stray. The mask is
    then applied to both layers — the outline lives inside the filled silhouette,
    so a mask that keeps the filled box keeps all of its ink too.
    """
    x0, y0, x1, y1 = box
    ink = [f.crop((x0, y0, x1, y1)) for f in ink_frames]
    paper = [f.crop((x0, y0, x1, y1)) for f in paper_frames]

    # NO dilation here, unlike `regions` above. A stray tick can sit within a
    # pixel or two of the box it is parked beside, and dilating merged the two
    # into one component — so "keep the largest" kept both, and the stray came
    # through into the cut. Eight way connectivity is enough to hold a hand
    # drawn line together on its own: the stroke is continuous, it just steps
    # diagonally, which the default four way rule treats as a break.
    labels, count = ndimage.label(alpha_union(paper), structure=np.ones((3, 3)))
    if count > 1:
        sizes = ndimage.sum(np.ones_like(labels), labels, range(1, count + 1))
        keep = int(np.argmax(sizes)) + 1
        ky, kx = ndimage.find_objects(labels)[keep - 1]
        ink = [c.crop((kx.start, ky.start, kx.stop, ky.stop)) for c in ink]
        paper = [c.crop((kx.start, ky.start, kx.stop, ky.stop)) for c in paper]
        # Everything outside the kept component is erased rather than merely
        # cropped around: a stray can share the bounding box with the outline.
        keep_mask = (labels == keep)[ky, kx]
        ink = [mask_alpha(c, keep_mask) for c in ink]
        paper = [mask_alpha(c, keep_mask) for c in paper]
    return ink, paper


def mask_alpha(image: Image.Image, keep: np.ndarray) -> Image.Image:
    pixels = np.array(image)
    pixels[:, :, 3] = np.where(keep, pixels[:, :, 3], 0)
    return Image.fromarray(pixels, "RGBA")


def erase_rule(image: Image.Image, top: int, bottom: int, donor: int) -> Image.Image:
    """Replace rows [top, bottom) with a copy of row `donor`. See `rule` above."""
    pixels = np.array(image)
    pixels[top:bottom] = pixels[donor]
    return Image.fromarray(pixels, "RGBA")


def to_paper(image: Image.Image) -> Image.Image:
    """The filled silhouette as flat white, keeping its anti-aliased edge.

    Flat white so the layer reads correctly with no tint at all, which is the
    common case in light mode; a tint recolours it for dark mode or for a
    coloured card without needing a second cut.
    """
    pixels = np.array(image)
    pixels[:, :, :3] = 255
    return Image.fromarray(pixels, "RGBA")


def union_bbox(images: list[Image.Image]):
    union = None
    for image in images:
        box = image.getbbox()
        if box is None:
            continue
        union = box if union is None else (
            min(union[0], box[0]), min(union[1], box[1]),
            max(union[2], box[2]), max(union[3], box[3]),
        )
    return union


def edge_depth(alpha: np.ndarray) -> int:
    """How far in from the top the ink reaches, along the middle third.

    The middle third is edge and nothing but edge — the corners are what the
    inset measurement is for, and including them here would report a whole
    corner curve as line thickness. Measured on the boil union, so it covers
    where the line wanders to at its furthest, which is what content has to
    clear.
    """
    span = alpha.shape[1]
    middle = alpha[:, span // 3: 2 * span // 3]
    limit = max(2, alpha.shape[0] // 3)
    deepest = 0
    for depth in range(limit):
        if middle[depth].any():
            deepest = depth
    return deepest


def measure_insets(alpha: np.ndarray) -> dict:
    """How much of each edge is CORNER and must not be stretched.

    Found by walking in from each side until the outline's own offset from that
    side stops changing — that is where the rounded corner ends and the straight
    run begins. A stretched corner is the one artefact that makes a nine slice
    frame look broken, so this errs generous: whatever it finds, plus a couple
    of pixels of the boil's own wander.

    An inset has to satisfy BOTH constraints: cover the corner curve, and be
    deep enough that the edge band contains the line in every frame — hence the
    `edge_depth` term, and hence measuring on the union rather than on frame 0.
    """
    height, width = alpha.shape
    slack = 3

    def run(profile):
        """First index where the outline settles onto its straight run.

        profile[i] = how far the ink sits from the edge at position i. Along a
        straight edge that is near constant; through a rounded or clipped
        corner it is much larger, because the first ink found scanning inwards
        is the ADJACENT edge rather than this one.

        The tolerance is taken from the art itself. These lines are drawn by
        hand and boil, so they wander by several pixels everywhere — a fixed
        tolerance either never triggers (which is what returned a 124px inset
        on a 374px banner) or triggers inside the corner. The 90th percentile
        of the middle third's own deviation IS the wobble amplitude, so
        anything within it is straight edge by definition.
        """
        span = len(profile)
        middle = np.asarray(profile[span // 3: 2 * span // 3], float)
        base = np.median(middle)
        tolerance = max(3.0, float(np.percentile(np.abs(middle - base), 90)))
        # Has to STAY settled: a corner can clip the tolerance for one column
        # on its way past, and stopping there puts the slice mid curve.
        hold = 5
        for i in range(span - hold):
            if all(abs(profile[j] - base) <= tolerance for j in range(i, i + hold)):
                return i
        return span // 4

    def depth(line):
        hit = np.flatnonzero(line)
        return hit[0] if hit.size else 0

    top = [depth(alpha[:, x]) for x in range(width)]
    bottom = [depth(alpha[::-1, x]) for x in range(width)]
    left = [depth(alpha[y, :]) for y in range(height)]
    right = [depth(alpha[y, ::-1]) for y in range(height)]

    # Each corner inset is bounded by both edges meeting there, and by a third
    # of the box: past that there is no middle left to stretch.
    return {
        "left": min(width // 3, max(run(top), run(bottom), edge_depth(alpha.T)) + slack),
        "right": min(width // 3, max(run(top[::-1]), run(bottom[::-1]), edge_depth(alpha.T[::-1])) + slack),
        "top": min(height // 3, max(run(left), run(right), edge_depth(alpha)) + slack),
        "bottom": min(height // 3, max(run(left[::-1]), run(right[::-1]), edge_depth(alpha[::-1])) + slack),
    }


def clear_middle(alpha: np.ndarray, insets: dict) -> dict:
    """Deepen the insets until no ink is left in the stretchable middle.

    An inset means "everything outside this must not be stretched", so ink
    inside it is a contradiction, not a matter of taste. `measure_insets` finds
    where each edge SETTLES, which is the right answer for a big box but runs a
    pixel or two shallow on the small ones: the badge is 44px across with a 12px
    line, so the outline's own wobble crosses the boundary. Left alone, that
    stray pixel lands in an edge band and smears into a bar down the side.

    Grown a pixel at a time on all four sides together, so the frame keeps its
    proportions rather than developing one fat edge. Capped at 40% per side —
    past that there is too little middle left to stretch, and a frame that
    cannot be stretched is one that can only be drawn at its source size.
    """
    height, width = alpha.shape
    grown = dict(insets)
    for _ in range(max(width, height)):
        inner = alpha[
            grown["top"]:height - grown["bottom"],
            grown["left"]:width - grown["right"],
        ]
        if not inner.any():
            return grown
        if (grown["left"] + 1 > width * 0.4 or grown["right"] + 1 > width * 0.4
                or grown["top"] + 1 > height * 0.4 or grown["bottom"] + 1 > height * 0.4):
            break
        for side in grown:
            grown[side] += 1
    return grown


def measure_ink(alpha: np.ndarray) -> dict:
    """Line thickness on each side, which is the clearance padding needs."""
    return {
        "left": edge_depth(alpha.T) + 1,
        "right": edge_depth(alpha.T[::-1]) + 1,
        "top": edge_depth(alpha) + 1,
        "bottom": edge_depth(alpha[::-1]) + 1,
    }


def strip(crops: list[Image.Image]) -> Image.Image:
    width, height = crops[0].size
    sheet = Image.new("RGBA", (width * FRAME_COUNT, height))
    for i, crop in enumerate(crops):
        sheet.alpha_composite(crop, (width * i, 0))
    return sheet


def flip_strip(sheet: Image.Image, axis: str) -> Image.Image:
    """Mirror a filmstrip frame by frame.

    Flipping the WHOLE strip horizontally would also reverse the frame order,
    so the boil would run backwards — harmless on a three frame cycle, but it
    would also put frame 2's art where the manifest says frame 0 is, which is
    the sort of thing that only shows up as a one frame stutter much later.
    """
    width = sheet.width // FRAME_COUNT
    out = Image.new("RGBA", sheet.size)
    for i in range(FRAME_COUNT):
        cell = sheet.crop((width * i, 0, width * (i + 1), sheet.height))
        cell = cell.transpose(
            Image.FLIP_LEFT_RIGHT if axis == "x" else Image.FLIP_TOP_BOTTOM
        )
        out.alpha_composite(cell, (width * i, 0))
    return out


def flip_sides(sides: dict, axis: str) -> dict:
    if axis == "x":
        return {**sides, "left": sides["right"], "right": sides["left"]}
    return {**sides, "top": sides["bottom"], "bottom": sides["top"]}


def entry(frame_id, name, purpose, ink_strip, paper_strip, insets, ink, out_dir):
    width = ink_strip.width // FRAME_COUNT
    height = ink_strip.height
    ink_path = out_dir / f"{frame_id}.png"
    paper_path = out_dir / f"{frame_id}_paper.png"
    ink_strip.save(ink_path)
    paper_strip.save(paper_path)
    return {
        "id": frame_id,
        "name": name,
        "purpose": purpose,
        "frameWidth": width,
        "frameHeight": height,
        "frameCount": FRAME_COUNT,
        "insets": insets,
        # How thick the line is, per side. Padding clears the ink; it does not
        # clear the inset, which is a nine slice measurement and much larger.
        "ink": ink,
        # Below this the corners have to share the box and start overlapping
        # into each other, so the frame stops looking like its own drawing.
        "minWidth": insets["left"] + insets["right"],
        "minHeight": insets["top"] + insets["bottom"],
        "fileSize": ink_path.stat().st_size + paper_path.stat().st_size,
    }


def main() -> int:
    source = find_source()
    frontend = Path(__file__).resolve().parents[2]
    out_dir = frontend / "assets" / "frames"
    out_dir.mkdir(parents=True, exist_ok=True)

    ink_frames, paper_frames = load_frames(source)
    found = regions(ink_frames)
    manifest = {}
    cut = {}

    for index, spec in sorted(WANTED.items()):
        frame_id, name, purpose = spec["id"], spec["name"], spec["purpose"]
        ink, paper = isolate(ink_frames, paper_frames, found[index])
        if spec.get("trim"):
            ink = [c.crop(spec["trim"]) for c in ink]
            paper = [c.crop(spec["trim"]) for c in paper]
        # Ink only: the paper under a rule is interior and has to stay filled.
        for top, bottom, donor in spec.get("rule", []):
            ink = [erase_rule(c, top, bottom, donor) for c in ink]

        # Re-tighten: trimming can leave a rim of empty pixels, and a frame with
        # slack around it draws its border inside the box it was given rather
        # than on it. Both layers take the SAME box — the paper is the outline's
        # own silhouette, so they agree, and cropping them apart by even a pixel
        # would show as white creeping past the ink on one side.
        union = union_bbox(ink + paper)
        ink = [c.crop(union) for c in ink]
        paper = [to_paper(c.crop(union)) for c in paper]

        alpha = alpha_union(ink)
        insets = measure_insets(alpha)
        for side, floor in (spec.get("floor") or {}).items():
            insets[side] = max(insets[side], floor)
        insets = clear_middle(alpha, insets)

        row = entry(
            frame_id, name, purpose, strip(ink), strip(paper),
            insets, measure_ink(alpha), out_dir,
        )
        manifest[frame_id] = row
        cut[frame_id] = (strip(ink), strip(paper))
        print(f"  {frame_id:<20} {row['frameWidth']}x{row['frameHeight']} x{FRAME_COUNT}"
              f"  insets={insets}  ink={row['ink']}")

    for spec in DERIVED:
        base = manifest[spec["of"]]
        ink_strip, paper_strip = cut[spec["of"]]
        axis = spec["mirror"]
        row = entry(
            spec["id"], spec["name"], spec["purpose"],
            flip_strip(ink_strip, axis), flip_strip(paper_strip, axis),
            flip_sides(base["insets"], axis), flip_sides(base["ink"], axis), out_dir,
        )
        manifest[spec["id"]] = row
        print(f"  {spec['id']:<20} {row['frameWidth']}x{row['frameHeight']} x{FRAME_COUNT}"
              f"  mirror={axis} of {spec['of']}")

    (out_dir / "frame-manifest.json").write_text(
        json.dumps(
            {
                "schemaVersion": 2,
                "source": str(source),
                # Recorded here rather than in animation-selection.json because
                # these are not effects: they never play on a timeline, they are
                # nine slice UI art with insets, and the effect importer has
                # nothing to say about them. Same provenance discipline though.
                "license": {
                    "package": "BigFramesColored",
                    "file": "See source pack; no licence file shipped in the download.",
                    "releaseApproved": True,
                    "note": "Terms verified by the project owner 2026-08-11.",
                },
                "frames": manifest,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print(f"Wrote {len(manifest)} frames to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
