#!/usr/bin/env python3
"""Copy PASER's reviewed FX subset and generate the static Metro registry."""

from __future__ import annotations

import argparse
import io
import json
import math
import re
import shutil
import zipfile
from collections import Counter
from pathlib import Path

from PIL import Image
from scan import build_summary


# Metro selects @2x/@3x siblings for the device pixel ratio. Without them a
# 96 px capture frame rendered at 280 logical points is enlarged yet again on
# a Retina screen, and native texture filtering turns intentional pixel edges
# into blur. Nearest-neighbour derivatives preserve the authored pixels while
# giving iOS and Android a density-matched texture.
DENSITY_SCALES = (2, 3)


def load_json(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def natural_key(value: str):
    return [int(part) if part.isdigit() else part.lower() for part in re.split(r"(\d+)", value)]


def read_member(source_root: Path, package: dict, effect: dict) -> tuple[bytes, str]:
    if effect.get("path"):
        path = source_root / effect["path"]
        return path.read_bytes(), str(path.resolve())
    archive = source_root / package["container"]
    with zipfile.ZipFile(archive) as bundle:
        return bundle.read(effect["entry"]), f"{archive.resolve()}::{effect['entry']}"


def pack_sequence(source_root: Path, package: dict, effect: dict) -> tuple[bytes, str]:
    archive = source_root / package["container"]
    spec = effect["sequence"]
    with zipfile.ZipFile(archive) as bundle:
        names = sorted(
            (
                name for name in bundle.namelist()
                if name.startswith(spec["prefix"]) and name.lower().endswith(spec["extension"].lower())
            ),
            key=natural_key,
        )
        if len(names) != effect["frameCount"]:
            raise ValueError(f"{effect['id']}: expected {effect['frameCount']} frames, found {len(names)}")
        frames = [Image.open(io.BytesIO(bundle.read(name))).convert("RGBA") for name in names]
    fw, fh = effect["frameWidth"], effect["frameHeight"]
    if any(frame.size != (fw, fh) for frame in frames):
        raise ValueError(f"{effect['id']}: sequence frame dimensions are not consistently {fw}x{fh}")
    columns = spec["columns"]
    rows = math.ceil(len(frames) / columns)
    sheet = Image.new("RGBA", (columns * fw, rows * fh), (0, 0, 0, 0))
    for index, frame in enumerate(frames):
        sheet.paste(frame, ((index % columns) * fw, (index // columns) * fh), frame)
    output = io.BytesIO()
    sheet.save(output, format="PNG", optimize=True)
    return output.getvalue(), f"{archive.resolve()}::{spec['prefix']}*{spec['extension']}"


def js_value(value):
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def generate_density_variants(target: Path) -> dict[str, dict]:
    variants = {}
    with Image.open(target) as source:
        base = source.convert("RGBA")
        for scale in DENSITY_SCALES:
            path = target.with_name(f"{target.stem}@{scale}x{target.suffix}")
            width, height = base.width * scale, base.height * scale
            density_image = base.resize((width, height), Image.Resampling.NEAREST)
            density_image.save(path, format="PNG", optimize=True)
            variants[str(scale)] = {
                "path": str(path.resolve()),
                "width": width,
                "height": height,
                "fileSize": path.stat().st_size,
            }
    return variants


def generate_registry(effects: list[dict], output: Path):
    lines = [
        "// Generated by scripts/animations/import_assets.py. Do not edit by hand.",
        "// Metro requires literal require() calls, so the reviewed selection is emitted here.",
        "",
        "export const GENERATED_EFFECTS = {",
    ]
    for effect in effects:
        metadata = {
            key: value for key, value in effect.items()
            if key not in {
                "entry", "path", "sequence", "package", "importedPath",
                "densityVariants", "runtimeBytes",
            }
        }
        metadata.update({
            "type": "sprite",
            "sourcePackage": effect["package"],
            "originalName": Path(effect.get("entry") or effect.get("path") or effect["id"]).name,
            "sourcePath": effect["sourcePath"],
        })
        source = effect["requirePath"]
        lines.append(f"  {json.dumps(effect['id'])}: {{")
        lines.append(f"    ...{js_value(metadata)},")
        lines.append(f"    source: require({json.dumps(source)}),")
        lines.append("  },")
    lines += ["};", ""]
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    script = Path(__file__).resolve()
    frontend = script.parents[2]
    repo = frontend.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--selection", type=Path, default=script.with_name("animation-selection.json"))
    parser.add_argument("--source", type=Path)
    args = parser.parse_args()

    selection = load_json(args.selection)
    source_root = (args.source or Path(selection["sourceRoot"])).resolve()
    packages = selection["packages"]
    destination = frontend / "assets" / "effects"
    registry_path = frontend / "src" / "effects" / "generatedEffectRegistry.js"
    imported = []
    blocked = []

    # This directory contains generated derivatives only. Pruning it makes a
    # second import deterministic and, critically, removes files whose package
    # was later blocked from release instead of leaving stale assets behind.
    destination.mkdir(parents=True, exist_ok=True)
    if destination.resolve().parent != (frontend / "assets").resolve():
        raise ValueError(f"Refusing to prune unexpected effects directory: {destination}")
    for stale in destination.rglob("*.png"):
        stale.unlink()

    for effect in selection["effects"]:
        package = packages[effect["package"]]
        if package.get("releaseApproved") is not True:
            blocked.append({
                "id": effect["id"],
                "name": effect["name"],
                "package": effect["package"],
                "reason": package.get("releaseBlockReason") or "Package is not release-approved.",
            })
            continue
        payload, provenance = (
            pack_sequence(source_root, package, effect)
            if effect.get("sequence") else read_member(source_root, package, effect)
        )
        category_dir = destination / effect["category"]
        category_dir.mkdir(parents=True, exist_ok=True)
        target = category_dir / f"{effect['id']}.png"
        target.write_bytes(payload)
        with Image.open(target) as image:
            expected = (effect["columns"] * effect["frameWidth"], effect["rows"] * effect["frameHeight"])
            if image.size != expected:
                target.unlink(missing_ok=True)
                raise ValueError(f"{effect['id']}: sheet is {image.size}, metadata expects {expected}")
        density_variants = generate_density_variants(target)
        item = dict(effect)
        item["releaseApproved"] = True
        item["sourcePath"] = provenance
        item["importedPath"] = str(target.resolve())
        item["requirePath"] = "../../assets/effects/" + f"{effect['category']}/{effect['id']}.png"
        item["fileSize"] = target.stat().st_size
        item["densityScales"] = [1, *DENSITY_SCALES]
        item["densityVariants"] = density_variants
        item["runtimeBytes"] = item["fileSize"] + sum(
            variant["fileSize"] for variant in density_variants.values()
        )
        imported.append(item)

    generate_registry(imported, registry_path)
    manifest = {
        "schemaVersion": 1,
        "sourceRoot": str(source_root),
        "curatedAssets": len(selection["effects"]),
        "selectedAssets": len(imported),
        "selectedBaseBytes": sum(item["fileSize"] for item in imported),
        "selectedBytes": sum(item["runtimeBytes"] for item in imported),
        "densityScales": [1, *DENSITY_SCALES],
        "releaseApprovedOnly": True,
        "blockedAssets": blocked,
        "effects": imported,
        "packages": packages,
    }
    (destination / "import-manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    inventory_path = repo / "docs" / "animation-library-inventory.json"
    if inventory_path.exists():
        inventory = load_json(inventory_path)
        inventory["summary"]["selectedForImport"] = len(imported)
        inventory["selection"] = {
            "manifest": str(args.selection.resolve()),
            "selectedAssets": len(imported),
            "selectedBytes": manifest["selectedBytes"],
            "licenseBlockedAssets": blocked,
        }
        inventory_path.write_text(json.dumps(inventory, indent=2, ensure_ascii=False), encoding="utf-8")
        (repo / "docs" / "ANIMATION_LIBRARY.md").write_text(build_summary(inventory), encoding="utf-8")

        excluded = len(inventory["files"]) - len(imported)
        report = {
            "selectedAssets": len(imported),
            "selectedBytes": manifest["selectedBytes"],
            "excludedRecords": excluded,
            "exclusionSummary": {
                "not-curated-for-production": max(0, excluded - inventory["summary"]["unsupportedFiles"] - inventory["summary"]["oversizedFiles"]),
                "unsupported-or-broken": inventory["summary"]["unsupportedFiles"],
                "oversized": inventory["summary"]["oversizedFiles"],
                "exact-duplicate-files": inventory["summary"]["exactDuplicateFiles"],
            },
            "selectedByCategory": dict(Counter(item["category"] for item in imported)),
            "selected": [
                {key: item[key] for key in (
                    "id", "name", "category", "tags", "sourcePath", "importedPath",
                    "fileSize", "densityScales", "runtimeBytes",
                )}
                for item in imported
            ],
        }
        (repo / "docs" / "animation-import-report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"Imported {len(imported)} release-approved effects ({manifest['selectedBytes'] / 1024:.1f} KiB).")
    print(f"Blocked {len(blocked)} curated effects pending license verification.")
    print(f"Registry: {registry_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
