// The hand-drawn box frames, and where their nine slice cuts fall.
//
// Metro needs literal require() calls, so the sources are written out here and
// the geometry is read from the manifest the cutter emits — one file, generated
// by scripts/animations/cut_frames.py, so the insets can never drift from the
// art they were measured on.
//
// Each frame is TWO drawings: the ink (the outline) and the paper (the same box
// filled). They are separate layers because they are coloured separately — the
// ink takes a clan colour or the theme's line colour, the paper takes whatever
// surface the box is sitting on. See ArtFrame for how they stack.

import manifest from '../../assets/frames/frame-manifest.json';

const SOURCES = {
  frame_panel: [require('../../assets/frames/frame_panel.png'), require('../../assets/frames/frame_panel_paper.png')],
  frame_banner: [require('../../assets/frames/frame_banner.png'), require('../../assets/frames/frame_banner_paper.png')],
  frame_banner_left: [require('../../assets/frames/frame_banner_left.png'), require('../../assets/frames/frame_banner_left_paper.png')],
  frame_label: [require('../../assets/frames/frame_label.png'), require('../../assets/frames/frame_label_paper.png')],
  frame_card: [require('../../assets/frames/frame_card.png'), require('../../assets/frames/frame_card_paper.png')],
  frame_badge: [require('../../assets/frames/frame_badge.png'), require('../../assets/frames/frame_badge_paper.png')],
  frame_note: [require('../../assets/frames/frame_note.png'), require('../../assets/frames/frame_note_paper.png')],
  frame_header: [require('../../assets/frames/frame_header.png'), require('../../assets/frames/frame_header_paper.png')],
  frame_ticket: [require('../../assets/frames/frame_ticket.png'), require('../../assets/frames/frame_ticket_paper.png')],
  frame_bubble: [require('../../assets/frames/frame_bubble.png'), require('../../assets/frames/frame_bubble_paper.png')],
  frame_bubble_right: [require('../../assets/frames/frame_bubble_right.png'), require('../../assets/frames/frame_bubble_right_paper.png')],
  frame_stamp: [require('../../assets/frames/frame_stamp.png'), require('../../assets/frames/frame_stamp_paper.png')],
  frame_panel_right: [require('../../assets/frames/frame_panel_right.png'), require('../../assets/frames/frame_panel_right_paper.png')],
  frame_card_right: [require('../../assets/frames/frame_card_right.png'), require('../../assets/frames/frame_card_right_paper.png')],
  frame_ticket_right: [require('../../assets/frames/frame_ticket_right.png'), require('../../assets/frames/frame_ticket_right_paper.png')],
  frame_label_right: [require('../../assets/frames/frame_label_right.png'), require('../../assets/frames/frame_label_right_paper.png')],
  frame_stamp_right: [require('../../assets/frames/frame_stamp_right.png'), require('../../assets/frames/frame_stamp_right_paper.png')],
};

// Friendly names, so callers say what they MEAN rather than which drawing they
// happened to like. Swapping which art backs `panel` is then a one line change
// here instead of a sweep through every screen.
// The same seventeen frames again, cut into ONE FILE PER POSE.
//
// The strips above are three drawings side by side, which is why a frame is
// drawn as eight clipped slices: showing pose 1 means cropping the middle
// third of the sheet. iOS can nine-slice an image natively (`capInsets`, see
// ui/ArtFrame.js) for one view instead of sixteen, but it stretches the middle
// of the WHOLE image — and the middle of a strip is the next drawing along. So
// the native path needs the poses apart, and that is all this is.
//
// Generated by scripts/split-frame-poses.py; `--check` verifies they still
// match the strips they were cut from. The strips stay because the boil still
// runs off them: cycling the three drawings is a translate on the UI thread,
// which cannot swap an image source per frame.
const POSES = {
  frame_note: {
    ink: [require('../../assets/frames/poses/frame_note_p0.png'), require('../../assets/frames/poses/frame_note_p1.png'), require('../../assets/frames/poses/frame_note_p2.png')],
    paper: [require('../../assets/frames/poses/frame_note_paper_p0.png'), require('../../assets/frames/poses/frame_note_paper_p1.png'), require('../../assets/frames/poses/frame_note_paper_p2.png')],
  },
  frame_panel: {
    ink: [require('../../assets/frames/poses/frame_panel_p0.png'), require('../../assets/frames/poses/frame_panel_p1.png'), require('../../assets/frames/poses/frame_panel_p2.png')],
    paper: [require('../../assets/frames/poses/frame_panel_paper_p0.png'), require('../../assets/frames/poses/frame_panel_paper_p1.png'), require('../../assets/frames/poses/frame_panel_paper_p2.png')],
  },
  frame_label: {
    ink: [require('../../assets/frames/poses/frame_label_p0.png'), require('../../assets/frames/poses/frame_label_p1.png'), require('../../assets/frames/poses/frame_label_p2.png')],
    paper: [require('../../assets/frames/poses/frame_label_paper_p0.png'), require('../../assets/frames/poses/frame_label_paper_p1.png'), require('../../assets/frames/poses/frame_label_paper_p2.png')],
  },
  frame_banner: {
    ink: [require('../../assets/frames/poses/frame_banner_p0.png'), require('../../assets/frames/poses/frame_banner_p1.png'), require('../../assets/frames/poses/frame_banner_p2.png')],
    paper: [require('../../assets/frames/poses/frame_banner_paper_p0.png'), require('../../assets/frames/poses/frame_banner_paper_p1.png'), require('../../assets/frames/poses/frame_banner_paper_p2.png')],
  },
  frame_card: {
    ink: [require('../../assets/frames/poses/frame_card_p0.png'), require('../../assets/frames/poses/frame_card_p1.png'), require('../../assets/frames/poses/frame_card_p2.png')],
    paper: [require('../../assets/frames/poses/frame_card_paper_p0.png'), require('../../assets/frames/poses/frame_card_paper_p1.png'), require('../../assets/frames/poses/frame_card_paper_p2.png')],
  },
  frame_bubble: {
    ink: [require('../../assets/frames/poses/frame_bubble_p0.png'), require('../../assets/frames/poses/frame_bubble_p1.png'), require('../../assets/frames/poses/frame_bubble_p2.png')],
    paper: [require('../../assets/frames/poses/frame_bubble_paper_p0.png'), require('../../assets/frames/poses/frame_bubble_paper_p1.png'), require('../../assets/frames/poses/frame_bubble_paper_p2.png')],
  },
  frame_ticket: {
    ink: [require('../../assets/frames/poses/frame_ticket_p0.png'), require('../../assets/frames/poses/frame_ticket_p1.png'), require('../../assets/frames/poses/frame_ticket_p2.png')],
    paper: [require('../../assets/frames/poses/frame_ticket_paper_p0.png'), require('../../assets/frames/poses/frame_ticket_paper_p1.png'), require('../../assets/frames/poses/frame_ticket_paper_p2.png')],
  },
  frame_badge: {
    ink: [require('../../assets/frames/poses/frame_badge_p0.png'), require('../../assets/frames/poses/frame_badge_p1.png'), require('../../assets/frames/poses/frame_badge_p2.png')],
    paper: [require('../../assets/frames/poses/frame_badge_paper_p0.png'), require('../../assets/frames/poses/frame_badge_paper_p1.png'), require('../../assets/frames/poses/frame_badge_paper_p2.png')],
  },
  frame_stamp: {
    ink: [require('../../assets/frames/poses/frame_stamp_p0.png'), require('../../assets/frames/poses/frame_stamp_p1.png'), require('../../assets/frames/poses/frame_stamp_p2.png')],
    paper: [require('../../assets/frames/poses/frame_stamp_paper_p0.png'), require('../../assets/frames/poses/frame_stamp_paper_p1.png'), require('../../assets/frames/poses/frame_stamp_paper_p2.png')],
  },
  frame_bubble_right: {
    ink: [require('../../assets/frames/poses/frame_bubble_right_p0.png'), require('../../assets/frames/poses/frame_bubble_right_p1.png'), require('../../assets/frames/poses/frame_bubble_right_p2.png')],
    paper: [require('../../assets/frames/poses/frame_bubble_right_paper_p0.png'), require('../../assets/frames/poses/frame_bubble_right_paper_p1.png'), require('../../assets/frames/poses/frame_bubble_right_paper_p2.png')],
  },
  frame_banner_left: {
    ink: [require('../../assets/frames/poses/frame_banner_left_p0.png'), require('../../assets/frames/poses/frame_banner_left_p1.png'), require('../../assets/frames/poses/frame_banner_left_p2.png')],
    paper: [require('../../assets/frames/poses/frame_banner_left_paper_p0.png'), require('../../assets/frames/poses/frame_banner_left_paper_p1.png'), require('../../assets/frames/poses/frame_banner_left_paper_p2.png')],
  },
  frame_header: {
    ink: [require('../../assets/frames/poses/frame_header_p0.png'), require('../../assets/frames/poses/frame_header_p1.png'), require('../../assets/frames/poses/frame_header_p2.png')],
    paper: [require('../../assets/frames/poses/frame_header_paper_p0.png'), require('../../assets/frames/poses/frame_header_paper_p1.png'), require('../../assets/frames/poses/frame_header_paper_p2.png')],
  },
  frame_panel_right: {
    ink: [require('../../assets/frames/poses/frame_panel_right_p0.png'), require('../../assets/frames/poses/frame_panel_right_p1.png'), require('../../assets/frames/poses/frame_panel_right_p2.png')],
    paper: [require('../../assets/frames/poses/frame_panel_right_paper_p0.png'), require('../../assets/frames/poses/frame_panel_right_paper_p1.png'), require('../../assets/frames/poses/frame_panel_right_paper_p2.png')],
  },
  frame_card_right: {
    ink: [require('../../assets/frames/poses/frame_card_right_p0.png'), require('../../assets/frames/poses/frame_card_right_p1.png'), require('../../assets/frames/poses/frame_card_right_p2.png')],
    paper: [require('../../assets/frames/poses/frame_card_right_paper_p0.png'), require('../../assets/frames/poses/frame_card_right_paper_p1.png'), require('../../assets/frames/poses/frame_card_right_paper_p2.png')],
  },
  frame_ticket_right: {
    ink: [require('../../assets/frames/poses/frame_ticket_right_p0.png'), require('../../assets/frames/poses/frame_ticket_right_p1.png'), require('../../assets/frames/poses/frame_ticket_right_p2.png')],
    paper: [require('../../assets/frames/poses/frame_ticket_right_paper_p0.png'), require('../../assets/frames/poses/frame_ticket_right_paper_p1.png'), require('../../assets/frames/poses/frame_ticket_right_paper_p2.png')],
  },
  frame_label_right: {
    ink: [require('../../assets/frames/poses/frame_label_right_p0.png'), require('../../assets/frames/poses/frame_label_right_p1.png'), require('../../assets/frames/poses/frame_label_right_p2.png')],
    paper: [require('../../assets/frames/poses/frame_label_right_paper_p0.png'), require('../../assets/frames/poses/frame_label_right_paper_p1.png'), require('../../assets/frames/poses/frame_label_right_paper_p2.png')],
  },
  frame_stamp_right: {
    ink: [require('../../assets/frames/poses/frame_stamp_right_p0.png'), require('../../assets/frames/poses/frame_stamp_right_p1.png'), require('../../assets/frames/poses/frame_stamp_right_p2.png')],
    paper: [require('../../assets/frames/poses/frame_stamp_right_paper_p0.png'), require('../../assets/frames/poses/frame_stamp_right_paper_p1.png'), require('../../assets/frames/poses/frame_stamp_right_paper_p2.png')],
  },
};

export const FRAME = Object.freeze({
  // Boxes to put things in.
  panel: 'frame_panel',
  panelRight: 'frame_panel_right',
  card: 'frame_card',
  cardRight: 'frame_card_right',
  ticket: 'frame_ticket',
  ticketRight: 'frame_ticket_right',
  // Wide runs: a heading, a hero row, a stat line.
  banner: 'frame_banner',
  bannerLeft: 'frame_banner_left',
  label: 'frame_label',
  labelRight: 'frame_label_right',
  // Wide, with a rule drawn parallel to one edge — a heading with a line under
  // it, or a caption with a line over it, without needing a second element.
  header: 'frame_header',
  note: 'frame_note',
  // Small squares. Three of them, and they are DELIBERATELY interchangeable:
  // see `frameVariant`.
  badge: 'frame_badge',
  stamp: 'frame_stamp',
  stampRight: 'frame_stamp_right',
  // Speech. The tail is at the bottom on the side the name says.
  bubble: 'frame_bubble',
  bubbleRight: 'frame_bubble_right',
});

export const FRAMES = Object.freeze(
  Object.fromEntries(
    Object.entries(manifest.frames)
      .filter(([id]) => SOURCES[id])
      .map(([id, spec]) => [id, Object.freeze({
        ...spec,
        // `source` is the ink, because that is the layer every caller draws;
        // the paper is optional and only appears when a fill is asked for.
        source: SOURCES[id][0],
        paper: SOURCES[id][1],
        // The same two layers with the poses apart, for the native nine slice.
        // Indexed by pose, so asking for pose 2 of a frame that only has one
        // drawing gives undefined rather than the wrong box — ArtFrame reads a
        // missing pose as "no fast path here" and falls back to slicing.
        posesInk: Object.freeze(POSES[id]?.ink || []),
        posesPaper: Object.freeze(POSES[id]?.paper || []),
      })])
  )
);

export function getFrame(name) {
  if (!name) return null;
  return FRAMES[FRAME[name] || name] || null;
}

// Groups of frames that are interchangeable — same job, different drawing.
//
// This is the point of having three small squares that are nearly the same box.
// A row of eight badges all cut from ONE drawing reads as eight copies of a
// sticker, which is the giveaway that the hand-drawn look is a texture rather
// than a drawing. Dealing them round the group breaks that up.
export const FRAME_GROUP = Object.freeze({
  action: ['label', 'labelRight', 'banner', 'bannerLeft'],
  heading: ['label', 'labelRight'],
  chip: ['badge', 'stamp', 'stampRight'],
  box: ['panel', 'panelRight', 'card', 'cardRight', 'ticket', 'ticketRight'],
  featured: ['banner', 'bannerLeft', 'panel', 'panelRight'],
  bubble: ['bubble', 'bubbleRight'],
});

function seedHash(seed) {
  const key = String(seed ?? '');
  let hash = 0;
  for (let i = 0; i < key.length; i += 1) hash = (hash * 31 + key.charCodeAt(i)) | 0;
  return Math.abs(hash);
}

/**
 * Pick a frame from a group, the same way every time for the same `seed`.
 *
 * Deterministic on purpose: a list that re-rolled its frames on every render
 * would flicker between drawings as it re-renders, and a list that re-rolled on
 * scroll would do it while you watch. Seed it with whatever identifies the row
 * — an id, a name, an index.
 */
export function frameVariant(group, seed) {
  const names = FRAME_GROUP[group];
  if (!names?.length) return null;
  return names[seedHash(seed) % names.length];
}

/**
 * Pick one of the pack's three hand-redrawn poses without animating it.
 * Repeated frames therefore vary even when reduced motion is enabled and when
 * a full boil would be too busy. Like `frameVariant`, this is deterministic so
 * a row never changes shape while it re-renders or scrolls.
 */
export function framePose(seed, frameCount = 3) {
  const count = Math.max(1, Math.trunc(frameCount) || 1);
  return seedHash(`pose:${seed ?? ''}`) % count;
}

// INK WEIGHT.
//
// Every drawing in the pack was made at its own size, so at scale 1 they do not
// agree about how thick a line is: the banner is a 370px drawing with a 19px
// stroke, the badge a 44px drawing with a 12px one. Drawn at their natural size
// side by side, a full width hero wears a 19pt line and the chip next to it a
// 12pt one, and nothing on the screen looks like it came from the same pen.
//
// So a frame is scaled to a LINE WEIGHT rather than to a size. `weightScale`
// works out what scale makes a given drawing come out at `weight` points thick,
// and everything else — the corners, the padding — follows from that. The
// corners shrink with the line, which is right: a fine line drawn round a big
// box has small corners, exactly as it would on paper.
// The numbers are POINTS OF DRAWN LINE, so they read directly: `base` is a
// 5pt stroke, whichever of the pack's drawings is behind it.
//
// The first pass at this set was a third finer (2 / 2.75 / 3.5 / 4.5 / 6) and
// it was too timid — normalising the weights fixed the mismatch but left every
// box looking like a hairline sketch of itself rather than the confident marker
// line the art was drawn with. These are the drawn line's own proportions on a
// phone: a chip carries 3.5pt, a button 5, a hero 6.5.
export const INK = Object.freeze({
  hairline: 3,
  thin: 3.75,
  base: 5,
  // The selected/emphasised step, between base and bold, on the same roughly
  // 1.3x spacing as the rest of the ladder.
  //
  // IT WAS MISSING, and seven call sites were already asking for it — the
  // selected tile in the shop and the studio, the claimable reward, the club
  // header, the active attack option. `weightScale` reads a falsy weight as
  // "draw the art at its own size", so every one of those was rendering at
  // scale 1: a 12 to 19pt stroke where 3.75 to 6.5 was intended, which is the
  // one thing this whole scale exists to prevent. An undefined lookup on a
  // frozen object is silent, so nothing anywhere reported it.
  medium: 5.75,
  bold: 6.5,
  heavy: 8.5,
});

function inkMean(name) {
  const ink = getFrame(name)?.ink;
  if (!ink) return 0;
  return (ink.left + ink.right + ink.top + ink.bottom) / 4;
}

/**
 * The scale at which `name` draws a line `weight` points thick.
 *
 * `weight={false}` is the ONE way to ask for the art at its own size, and it
 * has to be spelled that way. It used to be any falsy value, which made a typo
 * on the INK scale (`INK.medium`, which did not exist until it was added) mean
 * "draw a 44px badge with its natural 12pt stroke" — a silent three times too
 * heavy, at seven call sites, for as long as nobody looked closely. A weight
 * that is neither false nor a usable number is a mistake, so it says so in dev
 * and falls back to the base line rather than to the art's own.
 */
export function weightScale(name, weight) {
  // Asking for no weight: `false` is what the docs say, `0` reads the same way
  // and some callers write it. Both are somebody stating an intention.
  if (weight === false || weight === 0) return 1;
  const mean = inkMean(name);
  // Not stating one at all is different, and it is where the bug lived. A
  // `weight` that arrives undefined came from a property that is not on the INK
  // scale — there is no way to write that on purpose.
  if (!Number.isFinite(weight) || weight < 0) {
    if (__DEV__) {
      console.warn(
        `[frames] ${name}: weight is ${String(weight)}. Pass a number from INK, or ` +
        'weight={false} for the art at its own size.'
      );
    }
    // Fall back to the BASE line rather than to the drawing's own size. A box
    // at slightly the wrong weight is still a box; a 44px badge drawn at scale
    // 1 is a blot with text in it.
    return mean ? INK.base / mean : 1;
  }
  if (!mean) return 1;
  return weight / mean;
}

/**
 * How far content has to sit from each edge to clear the drawn line.
 *
 * This is the frame's measured INK depth, and it is deliberately not its inset.
 * The two get confused because both are "a number per side measured off the
 * art", but they answer different questions: an inset is how much of the
 * drawing must not be stretched, ink depth is how thick the line is. The banner
 * is the case that shows the difference — a 45pt bottom inset over a 16pt line,
 * because the inset also has to cover the clipped corner. Padding by the inset
 * put 30pt of dead space under every banner and still let text touch the ink on
 * frames where the ratio went the other way.
 *
 * `extra` is the caller's own breathing room, on top of the clearance.
 */
export function framePadding(name, extra = 0, scale = 1) {
  const ink = getFrame(name)?.ink;
  if (!ink) return { padding: extra };
  const at = (side) => Math.round(ink[side] * scale) + extra;
  return {
    paddingLeft: at('left'),
    paddingRight: at('right'),
    paddingTop: at('top'),
    paddingBottom: at('bottom'),
  };
}
